import React, { useState, useMemo } from 'react';
import {
  Ear,
  Copy,
  Check,
  RotateCcw,
  Sparkles,
  Calculator,
  BarChart2,
  FileText,
  Activity,
  Info,
  CheckCircle2,
  AlertTriangle,
  Stethoscope,
} from 'lucide-react';
import { AttendanceRecord } from '../types';
import { saveAutoGeneratedResume } from '../utils/medicalResumeGenerator';
import { AudiogramVisualChart } from './AudiogramVisualChart';

interface AudiometriFormProps {
  patient: AttendanceRecord;
  examinerDoctor?: string;
  onSave?: (data: any) => void;
  onNotify: (message: string) => void;
}

// 11 Frekuensi Standar
export const AUDIOMETRI_FREQUENCIES = [
  '125',
  '250',
  '500',
  '1000',
  '2000',
  '3000',
  '4000',
  '6000',
  '8000',
] as const;

export type FrequencyKey = typeof AUDIOMETRI_FREQUENCIES[number];

export interface EarThresholds {
  [freq: string]: number | undefined;
}

export interface AudiometriData {
  kananAC: EarThresholds;
  kananBC: EarThresholds;
  kiriAC: EarThresholds;
  kiriBC: EarThresholds;
}

// Preset kasus klinis untuk kemudahan demo / pengujian
const PRESET_CASES: { name: string; desc: string; data: AudiometriData }[] = [
  {
    name: 'Normal Bilateral (≤ 25 dB)',
    desc: 'Kedua telinga dalam batas normal (AC & BC ≤ 25 dB)',
    data: {
      kananAC: { '125': 10, '250': 15, '500': 15, '1000': 15, '2000': 20, '3000': 20, '4000': 20, '6000': 20, '8000': 15 },
      kananBC: { '125': 5,  '250': 10, '500': 10, '1000': 10, '2000': 15, '3000': 15, '4000': 15, '6000': 15, '8000': 10 },
      kiriAC:  { '125': 15, '250': 15, '500': 20, '1000': 20, '2000': 20, '3000': 20, '4000': 25, '6000': 20, '8000': 20 },
      kiriBC:  { '125': 10, '250': 10, '500': 15, '1000': 15, '2000': 15, '3000': 15, '4000': 20, '6000': 15, '8000': 15 },
    },
  },
  {
    name: 'Tuli Konduktif Kanan (Air-Bone Gap > 10 dB, BC Normal)',
    desc: 'AC Kanan > 25 dB, BC Kanan ≤ 25 dB, ABG > 10 dB (Otitis / Serumen)',
    data: {
      kananAC: { '125': 35, '250': 40, '500': 45, '1000': 40, '2000': 35, '3000': 35, '4000': 35, '6000': 30, '8000': 25 },
      kananBC: { '125': 10, '250': 15, '500': 15, '1000': 15, '2000': 15, '3000': 15, '4000': 15, '6000': 15, '8000': 10 },
      kiriAC:  { '125': 15, '250': 15, '500': 15, '1000': 20, '2000': 20, '3000': 20, '4000': 20, '6000': 15, '8000': 15 },
      kiriBC:  { '125': 10, '250': 10, '500': 10, '1000': 15, '2000': 15, '3000': 15, '4000': 15, '6000': 10, '8000': 10 },
    },
  },
  {
    name: 'Tuli Sensorineural Kiri (Noise-Induced Hearing Loss 4 kHz)',
    desc: 'AC & BC Kiri > 25 dB tanpa air-bone gap (NIHL akibat bising kerja)',
    data: {
      kananAC: { '125': 15, '250': 15, '500': 20, '1000': 20, '2000': 20, '3000': 25, '4000': 25, '6000': 20, '8000': 20 },
      kananBC: { '125': 10, '250': 10, '500': 15, '1000': 15, '2000': 15, '3000': 20, '4000': 20, '6000': 15, '8000': 15 },
      kiriAC:  { '125': 20, '250': 25, '500': 30, '1000': 35, '2000': 45, '3000': 55, '4000': 60, '6000': 50, '8000': 40 },
      kiriBC:  { '125': 15, '250': 20, '500': 25, '1000': 30, '2000': 40, '3000': 50, '4000': 55, '6000': 45, '8000': 35 },
    },
  },
  {
    name: 'Tuli Campuran (Mixed Hearing Loss)',
    desc: 'AC & BC > 25 dB dan terdapat Air-Bone Gap > 10 dB',
    data: {
      kananAC: { '125': 45, '250': 50, '500': 55, '1000': 55, '2000': 50, '3000': 50, '4000': 55, '6000': 50, '8000': 45 },
      kananBC: { '125': 25, '250': 30, '500': 35, '1000': 35, '2000': 30, '3000': 35, '4000': 35, '6000': 30, '8000': 25 },
      kiriAC:  { '125': 20, '250': 20, '500': 25, '1000': 20, '2000': 25, '3000': 25, '4000': 25, '6000': 20, '8000': 20 },
      kiriBC:  { '125': 15, '250': 15, '500': 20, '1000': 15, '2000': 20, '3000': 20, '4000': 20, '6000': 15, '8000': 15 },
    },
  },
];

// Perhitungan PTA WHO (500, 1000, 2000, 4000 Hz)
export function calculatePTA(thresholds: EarThresholds): { pta: number; values: number[] } {
  const f500 = thresholds['500'] ?? 20;
  const f1000 = thresholds['1000'] ?? 20;
  const f2000 = thresholds['2000'] ?? 20;
  const f4000 = thresholds['4000'] ?? 20;
  const values = [f500, f1000, f2000, f4000];
  const pta = values.reduce((a, b) => a + b, 0) / 4;
  return { pta: Math.round(pta * 10) / 10, values };
}

// Klasifikasi Derajat Ketulian Standar Medis K3
export function getDerajatKetulian(pta: number): string {
  if (pta <= 25) return 'Normal';
  if (pta <= 40) return 'Derajat Ringan';
  if (pta <= 55) return 'Derajat Sedang';
  if (pta <= 70) return 'Derajat Sedang-Berat';
  if (pta <= 90) return 'Derajat Berat';
  return 'Derajat Sangat Berat';
}

// Evaluasi Diagnosis Otomatis dari Hasil Penginputan Ambang Batas Pendengaran
export function evaluateEarDiagnosis(
  acThresholds: EarThresholds,
  bcThresholds: EarThresholds
): { diagnosis: string; derajat: string; abg: number; fullText: string } {
  const ptaACResult = calculatePTA(acThresholds);
  const ptaBCResult = calculatePTA(bcThresholds);
  const acPta = ptaACResult.pta;
  const bcPta = ptaBCResult.pta;
  const abg = Math.round((acPta - bcPta) * 10) / 10;

  // Cek jika ada drop nada tinggi (3000, 4000, 6000 Hz) khas bising kerja / NIHL
  const f3000 = acThresholds['3000'];
  const f4000 = acThresholds['4000'];
  const f6000 = acThresholds['6000'];
  const highVals = [f3000, f4000, f6000]
    .filter((v) => v !== undefined && !isNaN(Number(v)))
    .map(Number);
  const maxHigh = highVals.length > 0 ? Math.max(...highVals) : 0;

  // Jika frekuensi bicara normal (<= 25 dB) tapi frekuensi 3000/4000/6000 Hz > 25 dB
  if (acPta <= 25 && bcPta <= 25 && maxHigh > 25) {
    return {
      diagnosis: 'Tuli Sensorineural Frekuensi Tinggi',
      derajat: maxHigh <= 40 ? 'Derajat Ringan' : 'Derajat Sedang',
      abg,
      fullText: 'Tuli Sensorineural Frekuensi Tinggi (Suspek NIHL)',
    };
  }

  // Jika semua dalam batas normal
  if (acPta <= 25 && bcPta <= 25) {
    return {
      diagnosis: 'Normal',
      derajat: 'Normal',
      abg,
      fullText: 'Pendengaran dalam batas normal',
    };
  }

  const derajat = getDerajatKetulian(acPta);
  let tipe = 'Tuli Sensorineural';
  if (acPta > 25 && bcPta <= 25 && abg > 10) {
    tipe = 'Tuli Konduktif';
  } else if (acPta > 25 && bcPta > 25 && abg <= 10) {
    tipe = 'Tuli Sensorineural';
  } else if (acPta > 25 && bcPta > 25 && abg > 10) {
    tipe = 'Tuli Campuran';
  } else if (abg > 10) {
    tipe = 'Tuli Konduktif';
  }

  return {
    diagnosis: tipe,
    derajat,
    abg,
    fullText: `${tipe} ${derajat}`,
  };
}

export function getAudiometryDiagnosis(
  acPta: number,
  bcPta: number
): { diagnosis: string; derajat: string; abg: number; fullText: string } {
  const abg = Math.round((acPta - bcPta) * 10) / 10;
  if (acPta <= 25 && bcPta <= 25) {
    return { diagnosis: 'Normal', derajat: 'Normal', abg, fullText: 'Pendengaran dalam batas normal' };
  }
  const derajat = getDerajatKetulian(acPta);
  let tipe = 'Tuli Sensorineural';
  if (acPta > 25 && bcPta <= 25 && abg > 10) {
    tipe = 'Tuli Konduktif';
  } else if (acPta > 25 && bcPta > 25 && abg <= 10) {
    tipe = 'Tuli Sensorineural';
  } else if (acPta > 25 && bcPta > 25 && abg > 10) {
    tipe = 'Tuli Campuran';
  } else if (abg > 10) {
    tipe = 'Tuli Konduktif';
  }
  return { diagnosis: tipe, derajat, abg, fullText: `${tipe} ${derajat}` };
}

// Generate ASCII Art Chart
export function generateAsciiChart(
  earName: 'Kanan' | 'Kiri',
  acSymbol: string,
  bcSymbol: string,
  acThresholds: EarThresholds,
  bcThresholds: EarThresholds
): string {
  const freqs = ['250', '500', '1000', '2000', '4000', '8000'];
  const dbSteps = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100];

  let out = `Grafik Audiogram Telinga ${earName} (${acSymbol} / ${bcSymbol}):\n`;
  out += `dB | 250Hz | 500Hz | 1000Hz | 2000Hz | 4000Hz | 8000Hz\n`;
  out += `-------------------------------------------------------\n`;

  for (const db of dbSteps) {
    const dbLabel = String(db).padStart(2, ' ');
    const rowCols = freqs.map((f) => {
      const acVal = acThresholds[f];
      const bcVal = bcThresholds[f];

      // Toleransi ±5 dB untuk mapping ke baris step 10 dB
      const hasAc = acVal !== undefined && Math.round(acVal / 10) * 10 === db;
      const hasBc = bcVal !== undefined && Math.round(bcVal / 10) * 10 === db;

      if (hasAc && hasBc) {
        return `${acSymbol} ${bcSymbol}`.padEnd(6, ' ');
      } else if (hasAc) {
        return `  ${acSymbol}   `;
      } else if (hasBc) {
        return `  ${bcSymbol}   `;
      }
      return `       `;
    });

    out += `${dbLabel} |${rowCols.join('|')}\n`;
  }

  return out;
}

export const AudiometriForm: React.FC<AudiometriFormProps> = ({
  patient,
  examinerDoctor,
  onSave,
  onNotify,
}) => {
  // Initial state: Default Case 1 (Normal)
  const [data, setData] = useState<AudiometriData>(PRESET_CASES[0].data);
  const [doctorName, setDoctorName] = useState<string>(
    examinerDoctor || 'dr. Bambang Hermanto, Sp.THT-BKL'
  );
  const [copied, setCopied] = useState(false);

  // Kesimpulan diagnosis telinga kanan & kiri yang disesuaikan secara real-time dari penginputan
  const [kesimpulanKanan, setKesimpulanKanan] = useState<string>('Pendengaran dalam batas normal');
  const [kesimpulanKiri, setKesimpulanKiri] = useState<string>('Pendengaran dalam batas normal');
  const [catatanDokter, setCatatanDokter] = useState<string>('');
  const [isManualOverride, setIsManualOverride] = useState<boolean>(false);

  React.useEffect(() => {
    if (examinerDoctor) {
      setDoctorName(examinerDoctor);
    }
  }, [examinerDoctor]);

  React.useEffect(() => {
    if (!patient?.mcuNo) return;
    try {
      const saved = localStorage.getItem(`simreg_audiometri_${patient.mcuNo}`);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed.data) {
          setData(parsed.data);
        } else if (parsed.kananAC) {
          setData(parsed);
        }
        if (parsed.diagKanan) {
          setKesimpulanKanan(parsed.diagKanan);
          setIsManualOverride(true);
        }
        if (parsed.diagKiri) {
          setKesimpulanKiri(parsed.diagKiri);
          setIsManualOverride(true);
        }
        if (parsed.kesimpulan) {
          setCatatanDokter(parsed.kesimpulan);
        }
      }
    } catch (e) {}
  }, [patient?.mcuNo]);

  // Simple raw text input for quick batch parse
  const [rawTextInput, setRawTextInput] = useState(`Kanan AC: [15, 15, 20, 20]
Kanan BC: [10, 10, 15, 15]
Kiri AC: [20, 20, 20, 25]
Kiri BC: [15, 15, 15, 20]`);

  const [activeTab, setActiveTab] = useState<'interactive' | 'raw' | 'output'>('interactive');

  // Calculations
  const kananAC_PTA = useMemo(() => calculatePTA(data.kananAC), [data.kananAC]);
  const kananBC_PTA = useMemo(() => calculatePTA(data.kananBC), [data.kananBC]);
  const kiriAC_PTA = useMemo(() => calculatePTA(data.kiriAC), [data.kiriAC]);
  const kiriBC_PTA = useMemo(() => calculatePTA(data.kiriBC), [data.kiriBC]);

  // Evaluasi Otomatis Diagnosis Sesuai Penginputan
  const autoEvalKanan = useMemo(
    () => evaluateEarDiagnosis(data.kananAC, data.kananBC),
    [data.kananAC, data.kananBC]
  );
  const autoEvalKiri = useMemo(
    () => evaluateEarDiagnosis(data.kiriAC, data.kiriBC),
    [data.kiriAC, data.kiriBC]
  );

  // Reaktif update kesimpulan saat hasil input berubah (kecuali jika dokter manual override)
  React.useEffect(() => {
    if (!isManualOverride) {
      setKesimpulanKanan(autoEvalKanan.fullText);
      setKesimpulanKiri(autoEvalKiri.fullText);
    }
  }, [autoEvalKanan.fullText, autoEvalKiri.fullText, isManualOverride]);

  // Update cell in interactive matrix
  const handleCellChange = (
    channel: 'kananAC' | 'kananBC' | 'kiriAC' | 'kiriBC',
    freq: FrequencyKey,
    valueStr: string
  ) => {
    const val = valueStr === '' ? undefined : parseInt(valueStr, 10);
    setData((prev) => ({
      ...prev,
      [channel]: {
        ...prev[channel],
        [freq]: isNaN(val as number) ? undefined : val,
      },
    }));
  };

  // Parse user's raw text format:
  // Kanan AC: [500Hz, 1000Hz, 2000Hz, 4000Hz]
  // Kanan BC: [500Hz, 1000Hz, 2000Hz, 4000Hz]
  // Kiri AC: [500Hz, 1000Hz, 2000Hz, 4000Hz]
  // Kiri BC: [500Hz, 1000Hz, 2000Hz, 4000Hz]
  const handleParseRawText = () => {
    try {
      const lines = rawTextInput.split('\n');
      const nextData: AudiometriData = { ...data };

      const parseNumbersFromLine = (line: string): number[] => {
        const bracketMatch = line.match(/\[(.*?)\]/);
        const content = bracketMatch ? bracketMatch[1] : line.split(':')[1] || '';
        const numbers = content
          .replace(/hz/gi, '')
          .split(/[,;\s]+/)
          .map((s) => s.trim())
          .filter((s) => s !== '' && !isNaN(Number(s)))
          .map(Number);
        return numbers;
      };

      for (const line of lines) {
        const lower = line.toLowerCase();
        const nums = parseNumbersFromLine(line);
        if (nums.length === 0) continue;

        const targetFreqs = ['500', '1000', '2000', '4000'];
        const targetChannel =
          lower.includes('kanan') && lower.includes('ac')
            ? 'kananAC'
            : lower.includes('kanan') && lower.includes('bc')
            ? 'kananBC'
            : lower.includes('kiri') && lower.includes('ac')
            ? 'kiriAC'
            : lower.includes('kiri') && lower.includes('bc')
            ? 'kiriBC'
            : null;

        if (targetChannel) {
          nums.forEach((num, idx) => {
            if (idx < targetFreqs.length) {
              nextData[targetChannel][targetFreqs[idx]] = num;
            }
          });
        }
      }

      setData(nextData);
      onNotify('Data format input teks berhasil diproses dan dihitung!');
    } catch {
      onNotify('Gagal memproses format teks. Pastikan format sesuai contoh.');
    }
  };

  // Generate ASCII charts
  const asciiKanan = useMemo(
    () => generateAsciiChart('Kanan', 'O', '<', data.kananAC, data.kananBC),
    [data.kananAC, data.kananBC]
  );
  const asciiKiri = useMemo(
    () => generateAsciiChart('Kiri', 'X', '>', data.kiriAC, data.kiriBC),
    [data.kiriAC, data.kiriBC]
  );

  // Generate Section A Markdown Table
  const generateMarkdownOutput = (): string => {
    const renderRow = (
      channelName: string,
      earSymbol: string,
      thresholds: EarThresholds
    ) => {
      const cols = AUDIOMETRI_FREQUENCIES.map((f) => thresholds[f] ?? '-').join(' | ');
      return `| ${channelName} | ${earSymbol} | ${cols} |`;
    };

    return `### A. TABEL DATA AMBANG DENGAR AUDIOMETRI
| Jenis Hantaran | Telinga | 125 Hz | 250 Hz | 500 Hz | 1000 Hz | 2000 Hz | 3000 Hz | 4000 Hz | 6000 Hz | 8000 Hz |
| :--- | :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
${renderRow('Air Conduction (AC)', 'Kanan (● AC)', data.kananAC)}
${renderRow('Bone Conduction (BC)', 'Kanan (✚ BC)', data.kananBC)}
| **KESIMPULAN TELINGA KANAN** | **KANAN** | **${kesimpulanKanan}** | | | | | | | | |
${renderRow('Air Conduction (AC)', 'Kiri (◆ AC)', data.kiriAC)}
${renderRow('Bone Conduction (BC)', 'Kiri (▲ BC)', data.kiriBC)}
| **KESIMPULAN TELINGA KIRI** | **KIRI** | **${kesimpulanKiri}** | | | | | | | | |

### B. KESIMPULAN HASIL PEMERIKSAAN
- **Dokter Spesialis THT-KL:** **${doctorName}**
- **Kesimpulan Telinga Kanan:** **${kesimpulanKanan}**
- **Kesimpulan Telinga Kiri:** **${kesimpulanKiri}**
${catatanDokter ? `- **Catatan & Rekomendasi:** ${catatanDokter}\n` : ''}
### C. GRAFIK VISUAL AUDIOGRAM (ASCII ART)
\`\`\`text
${asciiKanan}
\`\`\`

\`\`\`text
${asciiKiri}
\`\`\`
`;
  };

  const handleCopyMarkdown = async () => {
    const text = generateMarkdownOutput();
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      onNotify('Laporan format Markdown & ASCII Art berhasil disalin ke clipboard!');
      setTimeout(() => setCopied(false), 2500);
    } catch {
      onNotify('Gagal menyalin otomatis ke clipboard.');
    }
  };

  const handleSaveAll = () => {
    const payload = {
      data,
      kananAC_PTA: kananAC_PTA.pta,
      kananBC_PTA: kananBC_PTA.pta,
      kiriAC_PTA: kiriAC_PTA.pta,
      kiriBC_PTA: kiriBC_PTA.pta,
      diagKanan: kesimpulanKanan,
      diagKiri: kesimpulanKiri,
      kesimpulan: catatanDokter,
    };
    try {
      localStorage.setItem(`simreg_audiometri_${patient.mcuNo}`, JSON.stringify(payload));
      saveAutoGeneratedResume(patient.mcuNo);
    } catch (e) {}

    onSave?.(payload);
    onNotify(
      `Hasil pemeriksaan Audiometri untuk ${patient.nama} (#${patient.mcuNo}) berhasil disimpan!`
    );
  };

  return (
    <div className="space-y-6">
      {/* 1. PERINTAH AWAL / PETUNJUK FORMAT CEPAT */}
      <div className="p-4 sm:p-5 rounded-2xl bg-gradient-to-r from-cyan-50 via-teal-50 to-blue-50 border border-cyan-200 shadow-xs">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-xl bg-cyan-600 text-white flex items-center justify-center shrink-0 shadow-md">
            <Ear className="w-5 h-5" />
          </div>
          <div className="space-y-2 flex-1">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <h4 className="font-extrabold text-[15px] text-cyan-950 flex items-center gap-2">
                Pemeriksaan Ambang Dengar Audiometri Nada Murni (PTA WHO Standard)
              </h4>
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-1 rounded-lg text-[11.5px] font-bold bg-white text-cyan-900 border border-cyan-200 shadow-2xs flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                  Dokter THT: <b>{doctorName}</b>
                </span>
                <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-cyan-100 text-cyan-800 border border-cyan-300">
                  Standar Okupasi K3
                </span>
              </div>
            </div>
            <p className="text-[13px] text-slate-700 leading-relaxed">
              Halo! Silakan masukkan data ambang batas pendengaran (dalam <b>dB HL</b>) untuk telinga kanan dan kiri.
              Anda dapat mengisi langsung pada tabel interaktif 11 frekuensi, memilih contoh preset kasus, atau memasukkan format teks cepat di bawah ini:
            </p>

            <div className="p-3 bg-white/90 rounded-xl border border-cyan-200 font-mono text-[12px] text-slate-800 space-y-0.5 shadow-2xs">
              <div className="text-[11px] font-sans font-bold text-cyan-800 mb-1">
                📋 Format Input Teks Cepat (Ambang 500 Hz, 1000 Hz, 2000 Hz, 4000 Hz):
              </div>
              <div className="text-emerald-700">Kanan AC: [500Hz, 1000Hz, 2000Hz, 4000Hz]</div>
              <div className="text-emerald-700">Kanan BC: [500Hz, 1000Hz, 2000Hz, 4000Hz]</div>
              <div className="text-blue-700">Kiri AC: [500Hz, 1000Hz, 2000Hz, 4000Hz]</div>
              <div className="text-blue-700">Kiri BC: [500Hz, 1000Hz, 2000Hz, 4000Hz]</div>
            </div>
          </div>
        </div>

        {/* Quick Presets Buttons */}
        <div className="mt-4 pt-3 border-t border-cyan-200/60 flex flex-wrap items-center gap-2">
          <span className="text-xs font-bold text-cyan-900 flex items-center gap-1">
            <Sparkles className="w-3.5 h-3.5 text-cyan-600" />
            Muat Contoh Kasus Klinis:
          </span>
          {PRESET_CASES.map((preset, idx) => (
            <button
              key={idx}
              type="button"
              onClick={() => {
                setData(preset.data);
                setIsManualOverride(false);
                const evR = evaluateEarDiagnosis(preset.data.kananAC, preset.data.kananBC);
                const evL = evaluateEarDiagnosis(preset.data.kiriAC, preset.data.kiriBC);
                setKesimpulanKanan(evR.fullText);
                setKesimpulanKiri(evL.fullText);
                onNotify(`Memuat contoh: ${preset.name}`);
              }}
              className="px-2.5 py-1 rounded-lg bg-white hover:bg-cyan-100/60 text-slate-800 border border-cyan-200 text-xs font-semibold transition-colors cursor-pointer shadow-2xs"
              title={preset.desc}
            >
              {preset.name}
            </button>
          ))}
        </div>
      </div>

      {/* Tab Navigasi Mode Input & Hasil */}
      <div className="flex items-center justify-between border-b border-slate-200 pb-2">
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => setActiveTab('interactive')}
            className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
              activeTab === 'interactive'
                ? 'bg-cyan-700 text-white shadow-xs'
                : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
            }`}
          >
            <BarChart2 className="w-4 h-4" />
            Tabel Input 11 Frekuensi
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('raw')}
            className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
              activeTab === 'raw'
                ? 'bg-cyan-700 text-white shadow-xs'
                : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
            }`}
          >
            <FileText className="w-4 h-4" />
            Input Teks Sederhana
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('output')}
            className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
              activeTab === 'output'
                ? 'bg-cyan-700 text-white shadow-xs'
                : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
            }`}
          >
            <Calculator className="w-4 h-4" />
            Output Markdown &amp; ASCII Art
          </button>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="px-3 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-bold flex items-center gap-1.5 border border-slate-300 cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Tersalin!' : 'Salin Laporan Markdown'}
          </button>
        </div>
      </div>

      {/* TAB 1: INTERACTIVE 11 FREQUENCY MATRIX */}
      {activeTab === 'interactive' && (
        <div className="space-y-4">
          <div className="overflow-x-auto rounded-xl border border-slate-200 shadow-2xs">
            <table className="w-full text-center text-[12.5px] border-collapse min-w-[760px]">
              <thead>
                <tr className="bg-slate-800 text-white font-bold text-[12px]">
                  <th className="py-3 px-3 text-left w-44">Jenis Hantaran</th>
                  <th className="py-3 px-2 w-28">Telinga</th>
                  {AUDIOMETRI_FREQUENCIES.map((freq) => (
                    <th key={freq} className="py-3 px-2 border-l border-slate-700 font-mono">
                      {freq} Hz
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 bg-white">
                {/* 1. Kanan AC */}
                <tr className="hover:bg-red-50/40">
                  <td className="py-2.5 px-3 text-left font-bold text-red-950">Air Conduction (AC)</td>
                  <td className="py-2.5 px-2 font-bold text-red-700 bg-red-50/50">
                    Kanan (● AC)
                  </td>
                  {AUDIOMETRI_FREQUENCIES.map((freq) => (
                    <td key={freq} className="py-1 px-1 border-l border-slate-200">
                      <input
                        type="number"
                        min="-10"
                        max="120"
                        step="5"
                        value={data.kananAC[freq] ?? ''}
                        onChange={(e) => handleCellChange('kananAC', freq, e.target.value)}
                        placeholder="-"
                        className={`w-12 py-1 text-center font-mono text-xs font-bold rounded-lg border transition-all ${
                          ['500', '1000', '2000', '4000'].includes(freq)
                            ? 'bg-red-50 border-red-300 text-red-900 focus:ring-1 focus:ring-red-500'
                            : 'bg-white border-slate-300 text-slate-800 focus:ring-1 focus:ring-slate-400'
                        }`}
                      />
                    </td>
                  ))}
                </tr>

                {/* 2. Kanan BC */}
                <tr className="hover:bg-red-50/40">
                  <td className="py-2.5 px-3 text-left font-bold text-red-900">Bone Conduction (BC)</td>
                  <td className="py-2.5 px-2 font-bold text-red-700 bg-red-50/50">
                    Kanan (✚ BC)
                  </td>
                  {AUDIOMETRI_FREQUENCIES.map((freq) => (
                    <td key={freq} className="py-1 px-1 border-l border-slate-200">
                      <input
                        type="number"
                        min="-10"
                        max="80"
                        step="5"
                        value={data.kananBC[freq] ?? ''}
                        onChange={(e) => handleCellChange('kananBC', freq, e.target.value)}
                        placeholder="-"
                        className={`w-12 py-1 text-center font-mono text-xs font-bold rounded-lg border transition-all ${
                          ['500', '1000', '2000', '4000'].includes(freq)
                            ? 'bg-red-50 border-red-300 text-red-900 focus:ring-1 focus:ring-red-500'
                            : 'bg-white border-slate-300 text-slate-800 focus:ring-1 focus:ring-slate-400'
                        }`}
                      />
                    </td>
                  ))}
                </tr>

                {/* Baris Kesimpulan Telinga Kanan Sesuai Hasil Penginputan */}
                <tr className="bg-red-50/90 font-bold border-y-2 border-red-300 text-red-950">
                  <td className="py-2 px-3 text-left uppercase tracking-wide text-[11.5px]">
                    KESIMPULAN TELINGA KANAN
                  </td>
                  <td className="py-2 px-2 uppercase font-black text-red-700">KANAN</td>
                  <td colSpan={AUDIOMETRI_FREQUENCIES.length} className="py-2.5 px-3 text-left text-[12.5px]">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <div className="flex items-center gap-2">
                        <span className="w-2.5 h-2.5 rounded-full bg-red-600"></span>
                        <span className="font-extrabold text-red-950">
                          {kesimpulanKanan}
                        </span>
                      </div>
                      <span
                        className={`text-[11px] px-2.5 py-0.5 rounded-full font-bold border ${
                          kesimpulanKanan.toLowerCase().includes('normal')
                            ? 'bg-emerald-50 text-emerald-800 border-emerald-300'
                            : 'bg-red-100 text-red-900 border-red-300'
                        }`}
                      >
                        {kesimpulanKanan.toLowerCase().includes('normal')
                          ? '✓ Batas Normal'
                          : '⚠ Evaluasi Medis'}
                      </span>
                    </div>
                  </td>
                </tr>

                {/* 3. Kiri AC */}
                <tr className="hover:bg-blue-50/40">
                  <td className="py-2.5 px-3 text-left font-bold text-blue-950">Air Conduction (AC)</td>
                  <td className="py-2.5 px-2 font-bold text-blue-700 bg-blue-50/50">
                    Kiri (◆ AC)
                  </td>
                  {AUDIOMETRI_FREQUENCIES.map((freq) => (
                    <td key={freq} className="py-1 px-1 border-l border-slate-200">
                      <input
                        type="number"
                        min="-10"
                        max="120"
                        step="5"
                        value={data.kiriAC[freq] ?? ''}
                        onChange={(e) => handleCellChange('kiriAC', freq, e.target.value)}
                        placeholder="-"
                        className={`w-12 py-1 text-center font-mono text-xs font-bold rounded-lg border transition-all ${
                          ['500', '1000', '2000', '4000'].includes(freq)
                            ? 'bg-blue-50 border-blue-300 text-blue-900 focus:ring-1 focus:ring-blue-500'
                            : 'bg-white border-slate-300 text-slate-800 focus:ring-1 focus:ring-slate-400'
                        }`}
                      />
                    </td>
                  ))}
                </tr>

                {/* 4. Kiri BC */}
                <tr className="hover:bg-blue-50/40">
                  <td className="py-2.5 px-3 text-left font-bold text-blue-900">Bone Conduction (BC)</td>
                  <td className="py-2.5 px-2 font-bold text-blue-700 bg-blue-50/50">
                    Kiri (▲ BC)
                  </td>
                  {AUDIOMETRI_FREQUENCIES.map((freq) => (
                    <td key={freq} className="py-1 px-1 border-l border-slate-200">
                      <input
                        type="number"
                        min="-10"
                        max="80"
                        step="5"
                        value={data.kiriBC[freq] ?? ''}
                        onChange={(e) => handleCellChange('kiriBC', freq, e.target.value)}
                        placeholder="-"
                        className={`w-12 py-1 text-center font-mono text-xs font-bold rounded-lg border transition-all ${
                          ['500', '1000', '2000', '4000'].includes(freq)
                            ? 'bg-blue-50 border-blue-300 text-blue-900 focus:ring-1 focus:ring-blue-500'
                            : 'bg-white border-slate-300 text-slate-800 focus:ring-1 focus:ring-slate-400'
                        }`}
                      />
                    </td>
                  ))}
                </tr>

                {/* Baris Kesimpulan Telinga Kiri Sesuai Hasil Penginputan */}
                <tr className="bg-blue-50/90 font-bold border-y-2 border-blue-300 text-blue-950">
                  <td className="py-2 px-3 text-left uppercase tracking-wide text-[11.5px]">
                    KESIMPULAN TELINGA KIRI
                  </td>
                  <td className="py-2 px-2 uppercase font-black text-blue-700">KIRI</td>
                  <td colSpan={AUDIOMETRI_FREQUENCIES.length} className="py-2.5 px-3 text-left text-[12.5px]">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <div className="flex items-center gap-2">
                        <span className="w-2.5 h-2.5 rounded-full bg-blue-600"></span>
                        <span className="font-extrabold text-blue-950">
                          {kesimpulanKiri}
                        </span>
                      </div>
                      <span
                        className={`text-[11px] px-2.5 py-0.5 rounded-full font-bold border ${
                          kesimpulanKiri.toLowerCase().includes('normal')
                            ? 'bg-emerald-50 text-emerald-800 border-emerald-300'
                            : 'bg-blue-100 text-blue-900 border-blue-300'
                        }`}
                      >
                        {kesimpulanKiri.toLowerCase().includes('normal')
                          ? '✓ Batas Normal'
                          : '⚠ Evaluasi Medis'}
                      </span>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div className="text-[11.5px] text-slate-500 flex items-center gap-1.5">
            <Info className="w-3.5 h-3.5 text-cyan-700 shrink-0" />
            <span>
              Kolom dengan latar belakang warna merupakan 4 frekuensi standar WHO (500 Hz, 1000 Hz, 2000 Hz, 4000 Hz) yang digunakan dalam kalkulasi Pure Tone Average (PTA).
            </span>
          </div>
        </div>
      )}

      {/* TAB 2: RAW TEXT INPUT */}
      {activeTab === 'raw' && (
        <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-3">
          <label className="block text-xs font-bold text-slate-700">
            Ketik atau Paste Data Ambang Dengar (dB HL):
          </label>
          <textarea
            rows={5}
            value={rawTextInput}
            onChange={(e) => setRawTextInput(e.target.value)}
            className="w-full p-3 font-mono text-xs bg-white border border-slate-300 rounded-xl focus:ring-2 focus:ring-cyan-500 text-slate-900"
            placeholder={`Kanan AC: [500Hz, 1000Hz, 2000Hz, 4000Hz]\nKanan BC: [500Hz, 1000Hz, 2000Hz, 4000Hz]\nKiri AC: [500Hz, 1000Hz, 2000Hz, 4000Hz]\nKiri BC: [500Hz, 1000Hz, 2000Hz, 4000Hz]`}
          />
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleParseRawText}
              className="px-4 py-2 rounded-xl bg-cyan-700 hover:bg-cyan-800 text-white text-xs font-bold flex items-center gap-1.5 shadow-xs cursor-pointer"
            >
              <Calculator className="w-3.5 h-3.5" />
              Proses &amp; Hitung PTA Otomatis
            </button>
            <button
              type="button"
              onClick={() => {
                setRawTextInput(`Kanan AC: [15, 20, 20, 25]\nKanan BC: [10, 15, 15, 20]\nKiri AC: [20, 20, 25, 25]\nKiri BC: [15, 20, 20, 20]`);
              }}
              className="px-3 py-2 rounded-xl bg-white border border-slate-300 hover:bg-slate-100 text-slate-700 text-xs font-semibold"
            >
              Reset Format Contoh
            </button>
          </div>
        </div>
      )}

      {/* SECTION B: KESIMPULAN TELINGA KANAN & TELINGA KIRI SESUAI HASIL PENGINPUTAN */}
      <div className="space-y-3">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div>
            <h4 className="font-bold text-[14.5px] text-slate-900 flex items-center gap-2">
              <Stethoscope className="w-4 h-4 text-cyan-700" />
              Kesimpulan Pemeriksaan Telinga Kanan &amp; Kiri
            </h4>
            <p className="text-xs text-slate-500 mt-0.5">
              Kesimpulan diagnosis terintegrasi langsung dan otomatis tersinkronisasi dengan data ambang dengar yang diinput.
            </p>
          </div>
          <div className="flex items-center gap-2">
            {isManualOverride ? (
              <button
                type="button"
                onClick={() => {
                  setIsManualOverride(false);
                  setKesimpulanKanan(autoEvalKanan.fullText);
                  setKesimpulanKiri(autoEvalKiri.fullText);
                  onNotify('Kesimpulan dikembalikan ke perhitungan otomatis.');
                }}
                className="text-[11px] px-2.5 py-1 rounded-lg bg-amber-50 text-amber-900 border border-amber-300 font-bold flex items-center gap-1 hover:bg-amber-100 cursor-pointer shadow-2xs"
              >
                <RotateCcw className="w-3 h-3" />
                Reset ke Hitungan Otomatis
              </button>
            ) : (
              <span className="text-[11px] px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-800 border border-emerald-200 font-bold flex items-center gap-1.5 shadow-2xs">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span>
                Tersinkronisasi Otomatis
              </span>
            )}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Kesimpulan Telinga Kanan */}
          <div className="p-4 rounded-2xl bg-gradient-to-br from-red-50/80 to-rose-50/50 border border-red-200 shadow-2xs space-y-3">
            <div className="flex items-center justify-between border-b border-red-200/80 pb-2">
              <h5 className="font-extrabold text-[13.5px] text-red-950 flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-red-600 shadow-xs"></span>
                Kesimpulan Telinga Kanan (Right Ear)
              </h5>
              <span
                className={`px-2.5 py-0.5 rounded-full text-[11px] font-black border ${
                  kesimpulanKanan.toLowerCase().includes('normal')
                    ? 'bg-emerald-100 text-emerald-900 border-emerald-300'
                    : 'bg-red-100 text-red-900 border-red-300'
                }`}
              >
                {kesimpulanKanan.toLowerCase().includes('normal') ? 'Normal' : 'Perlu Evaluasi'}
              </span>
            </div>

            <div className="space-y-1.5">
              <label className="text-[11.5px] font-bold text-slate-600 block">
                Diagnosis Klinis Telinga Kanan:
              </label>
              <input
                type="text"
                value={kesimpulanKanan}
                onChange={(e) => {
                  setKesimpulanKanan(e.target.value);
                  setIsManualOverride(true);
                }}
                className="w-full px-3 py-2 text-xs font-bold text-red-950 bg-white border border-red-300 rounded-xl focus:ring-2 focus:ring-red-500 shadow-2xs"
                placeholder="Contoh: Pendengaran dalam batas normal"
              />
            </div>

            <div className="pt-2 border-t border-red-200/60 flex flex-wrap items-center gap-1.5 text-[11px]">
              <span className="text-slate-500 font-semibold">Pilihan Cepat:</span>
              {[
                'Pendengaran dalam batas normal',
                'Tuli Konduktif Derajat Ringan',
                'Tuli Sensorineural Derajat Ringan',
                'Tuli Sensorineural Frekuensi Tinggi (Suspek NIHL)',
              ].map((diag) => (
                <button
                  key={diag}
                  type="button"
                  onClick={() => {
                    setKesimpulanKanan(diag);
                    setIsManualOverride(true);
                  }}
                  className="px-2 py-0.5 rounded-md bg-white hover:bg-red-100 text-red-900 border border-red-200 text-[10.5px] font-medium transition-colors cursor-pointer"
                >
                  {diag}
                </button>
              ))}
            </div>
          </div>

          {/* Kesimpulan Telinga Kiri */}
          <div className="p-4 rounded-2xl bg-gradient-to-br from-blue-50/80 to-cyan-50/50 border border-blue-200 shadow-2xs space-y-3">
            <div className="flex items-center justify-between border-b border-blue-200/80 pb-2">
              <h5 className="font-extrabold text-[13.5px] text-blue-950 flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-blue-600 shadow-xs"></span>
                Kesimpulan Telinga Kiri (Left Ear)
              </h5>
              <span
                className={`px-2.5 py-0.5 rounded-full text-[11px] font-black border ${
                  kesimpulanKiri.toLowerCase().includes('normal')
                    ? 'bg-emerald-100 text-emerald-900 border-emerald-300'
                    : 'bg-blue-100 text-blue-900 border-blue-300'
                }`}
              >
                {kesimpulanKiri.toLowerCase().includes('normal') ? 'Normal' : 'Perlu Evaluasi'}
              </span>
            </div>

            <div className="space-y-1.5">
              <label className="text-[11.5px] font-bold text-slate-600 block">
                Diagnosis Klinis Telinga Kiri:
              </label>
              <input
                type="text"
                value={kesimpulanKiri}
                onChange={(e) => {
                  setKesimpulanKiri(e.target.value);
                  setIsManualOverride(true);
                }}
                className="w-full px-3 py-2 text-xs font-bold text-blue-950 bg-white border border-blue-300 rounded-xl focus:ring-2 focus:ring-blue-500 shadow-2xs"
                placeholder="Contoh: Pendengaran dalam batas normal"
              />
            </div>

            <div className="pt-2 border-t border-blue-200/60 flex flex-wrap items-center gap-1.5 text-[11px]">
              <span className="text-slate-500 font-semibold">Pilihan Cepat:</span>
              {[
                'Pendengaran dalam batas normal',
                'Tuli Konduktif Derajat Ringan',
                'Tuli Sensorineural Derajat Ringan',
                'Tuli Sensorineural Frekuensi Tinggi (Suspek NIHL)',
              ].map((diag) => (
                <button
                  key={diag}
                  type="button"
                  onClick={() => {
                    setKesimpulanKiri(diag);
                    setIsManualOverride(true);
                  }}
                  className="px-2 py-0.5 rounded-md bg-white hover:bg-blue-100 text-blue-900 border border-blue-200 text-[10.5px] font-medium transition-colors cursor-pointer"
                >
                  {diag}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Catatan / Saran Tambahan Dokter */}
        <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 flex flex-col sm:flex-row items-start sm:items-center gap-3">
          <label className="text-xs font-bold text-slate-700 shrink-0">
            Catatan / Saran Medis Dokter:
          </label>
          <input
            type="text"
            value={catatanDokter}
            onChange={(e) => setCatatanDokter(e.target.value)}
            placeholder="Contoh: Hindari paparan bising > 85 dB tanpa Ear Plug / Ear Muff, evaluasi ulang 6-12 bulan"
            className="flex-1 w-full px-3 py-1.5 text-xs text-slate-800 bg-white border border-slate-300 rounded-lg focus:ring-1 focus:ring-cyan-500"
          />
        </div>
      </div>

      {/* SECTION C: GRAFIK VISUAL AUDIOGRAM (MODERN SVG & FORMAT RESMI) */}
      <div className="space-y-3">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div>
            <h4 className="font-bold text-[14.5px] text-slate-900 flex items-center gap-2">
              <span className="w-3 h-3 rounded-full bg-cyan-600 shadow-xs"></span>
              Grafik Visual Audiogram Nada Murni (Plotting Standar K3)
            </h4>
            <p className="text-xs text-slate-500 mt-0.5">
              Plot kurva ambang dengar telinga kanan (merah) dan kiri (biru) terhubung langsung secara real-time dengan tabel di atas.
            </p>
          </div>
          <span className="text-[11px] px-2.5 py-1 rounded-full bg-cyan-50 text-cyan-800 border border-cyan-200 font-bold flex items-center gap-1.5 shadow-2xs">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
            Real-Time Vector SVG
          </span>
        </div>

        {/* Modernized Graphic Visual matching uploaded file */}
        <div className="p-4 sm:p-5 rounded-2xl bg-white border border-slate-300 shadow-xs">
          <AudiogramVisualChart
            data={data}
            diagKanan={kesimpulanKanan}
            diagKiri={kesimpulanKiri}
            kesimpulan={catatanDokter}
            patientInfo={{
              nama: patient.nama,
              mcuNo: patient.mcuNo,
              pt: patient.pt,
              tglMcu: patient.tglMcu,
            }}
            showHeaderBanner={true}
            interactive={true}
          />
        </div>
      </div>

      {/* Action Buttons */}
      <div className="pt-2 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200">
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleSaveAll}
            className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-cyan-700 to-teal-700 hover:from-cyan-800 hover:to-teal-800 text-white font-bold text-xs flex items-center gap-2 shadow-md shadow-cyan-900/20 cursor-pointer"
          >
            <CheckCircle2 className="w-4 h-4" />
            Simpan Hasil Audiometri Pasien #{patient.mcuNo}
          </button>
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="px-4 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold text-xs flex items-center gap-1.5 border border-slate-300 cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            Salin Tabel Markdown &amp; ASCII Art
          </button>
        </div>

        <div className="text-xs text-slate-500 font-medium">
          Pasien: <b className="text-slate-800">{patient.nama}</b> ({patient.pt}) • No. MCU #{patient.mcuNo}
        </div>
      </div>
    </div>
  );
};
