import React, { useState, useMemo } from 'react';
import {
  HeartPulse,
  Copy,
  Check,
  RotateCcw,
  Sparkles,
  CheckCircle2,
  AlertTriangle,
  FileText,
  Info,
  Activity,
} from 'lucide-react';
import { AttendanceRecord } from '../types';
import { saveAutoGeneratedResume } from '../utils/medicalResumeGenerator';

interface EKGFormProps {
  patient: AttendanceRecord;
  examinerDoctor?: string;
  onSave?: (data: any) => void;
  onNotify: (message: string) => void;
}

export interface EKGData {
  hr: number; // bpm
  irama: string; // e.g. 'Sinus Rhythm'
  pr: number; // det, e.g. 0.16
  qrs: number; // det, e.g. 0.08
  axis: number; // derajat, e.g. 45
  stT: string; // e.g. 'Isoelektris (Normal)'
  diagnosisCustom?: string;
  saranCustom?: string;
}

// Nilai DEFAULT NORMAL sesuai spesifikasi
export const DEFAULT_NORMAL_EKG: EKGData = {
  hr: 75,
  irama: 'Sinus Rhythm',
  pr: 0.16,
  qrs: 0.08,
  axis: 45,
  stT: 'Isoelektris (Normal)',
  diagnosisCustom: '',
  saranCustom: '',
};

export const EKGForm: React.FC<EKGFormProps> = ({
  patient,
  examinerDoctor,
  onSave,
  onNotify,
}) => {
  const [ekg, setEkg] = useState<EKGData>(DEFAULT_NORMAL_EKG);
  const [doctorName, setDoctorName] = useState<string>(
    examinerDoctor || 'dr. Anisa Rahmawati'
  );
  const [quickInputText, setQuickInputText] = useState<string>('NORMAL');
  const [copied, setCopied] = useState(false);

  React.useEffect(() => {
    if (examinerDoctor) {
      setDoctorName(examinerDoctor);
    }
  }, [examinerDoctor]);

  React.useEffect(() => {
    if (!patient?.mcuNo) return;
    try {
      const saved = localStorage.getItem(`simreg_ekg_${patient.mcuNo}`);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed.ekg) setEkg(parsed.ekg);
      }
    } catch (e) {}
  }, [patient?.mcuNo]);

  // Evaluasi Tiap Parameter
  // 1. HR
  const hrStatus = useMemo(() => {
    if (ekg.hr < 60) return 'Bradikardia';
    if (ekg.hr > 100) return 'Takikardia';
    return 'Normal';
  }, [ekg.hr]);

  const hrInterpretasiString = useMemo(() => {
    return `${hrStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      hrStatus === 'Takikardia' ? '[X]' : '[ ]'
    } Takikardia / ${hrStatus === 'Bradikardia' ? '[X]' : '[ ]'} Bradikardia`;
  }, [hrStatus]);

  // 2. Irama
  const iramaStatus = useMemo(() => {
    const s = ekg.irama.toLowerCase();
    if (s.includes('sinus') && !s.includes('aritmia')) return 'Sinus Rhythm';
    return 'Aritmia';
  }, [ekg.irama]);

  const iramaInterpretasiString = useMemo(() => {
    return `${iramaStatus === 'Sinus Rhythm' ? '[X]' : '[ ]'} Sinus Rhythm / ${
      iramaStatus === 'Aritmia' ? '[X]' : '[ ]'
    } Aritmia`;
  }, [iramaStatus]);

  // 3. PR Interval
  const prStatus = useMemo(() => {
    if (ekg.pr < 0.12) return 'Memendek';
    if (ekg.pr > 0.2) return 'Memanjang';
    return 'Normal';
  }, [ekg.pr]);

  const prInterpretasiString = useMemo(() => {
    return `${prStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      prStatus === 'Memanjang' ? '[X]' : '[ ]'
    } Memanjang / ${prStatus === 'Memendek' ? '[X]' : '[ ]'} Memendek`;
  }, [prStatus]);

  // 4. Durasi QRS
  const qrsStatus = useMemo(() => {
    if (ekg.qrs > 0.12) return 'Melebar';
    return 'Normal';
  }, [ekg.qrs]);

  const qrsInterpretasiString = useMemo(() => {
    return `${qrsStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      qrsStatus === 'Melebar' ? '[X]' : '[ ]'
    } Melebar`;
  }, [qrsStatus]);

  // 5. Sumbu Axis (-30 s.d +90)
  const axisStatus = useMemo(() => {
    if (ekg.axis < -30) return 'LAD';
    if (ekg.axis > 90) return 'RAD';
    return 'Normal';
  }, [ekg.axis]);

  const axisInterpretasiString = useMemo(() => {
    return `${axisStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      axisStatus === 'LAD' ? '[X]' : '[ ]'
    } LAD / ${axisStatus === 'RAD' ? '[X]' : '[ ]'} RAD`;
  }, [axisStatus]);

  // 6. ST & T
  const stTStatus = useMemo(() => {
    const s = ekg.stT.toLowerCase();
    if (s.includes('elevasi')) return 'ST Elevasi';
    if (s.includes('depresi')) return 'ST Depresi';
    if (s.includes('inverted') || s.includes('terbalik')) return 'T Inverted';
    return 'Normal';
  }, [ekg.stT]);

  const stTInterpretasiString = useMemo(() => {
    return `${stTStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      stTStatus === 'ST Elevasi' ? '[X]' : '[ ]'
    } ST Elevasi / ${stTStatus === 'ST Depresi' ? '[X]' : '[ ]'} ST Depresi / ${
      stTStatus === 'T Inverted' ? '[X]' : '[ ]'
    } T Inverted`;
  }, [stTStatus]);

  // Overall EKG Normal vs Abnormal
  const isOverallNormal = useMemo(() => {
    return (
      hrStatus === 'Normal' &&
      iramaStatus === 'Sinus Rhythm' &&
      prStatus === 'Normal' &&
      qrsStatus === 'Normal' &&
      axisStatus === 'Normal' &&
      stTStatus === 'Normal'
    );
  }, [hrStatus, iramaStatus, prStatus, qrsStatus, axisStatus, stTStatus]);

  // Diagnosis Auto-Generation
  const autoDiagnosis = useMemo(() => {
    if (ekg.diagnosisCustom && ekg.diagnosisCustom.trim() !== '') {
      return ekg.diagnosisCustom;
    }
    if (isOverallNormal) {
      return 'Normal Sinus Rhythm, EKG dalam batas normal';
    }
    const abnormalities: string[] = [];
    if (hrStatus === 'Takikardia') abnormalities.push('Sinus Takikardia');
    if (hrStatus === 'Bradikardia') abnormalities.push('Sinus Bradikardia');
    if (iramaStatus === 'Aritmia') abnormalities.push('Aritmia');
    if (prStatus === 'Memanjang') abnormalities.push('Interval PR Memanjang (Suspek AV Block Derajat 1)');
    if (prStatus === 'Memendek') abnormalities.push('Interval PR Memendek (Suspek Pre-eksitasi / WPW)');
    if (qrsStatus === 'Melebar') abnormalities.push('Durasi QRS Melebar (Suspek Bundle Branch Block)');
    if (axisStatus === 'LAD') abnormalities.push('Left Axis Deviation (LAD)');
    if (axisStatus === 'RAD') abnormalities.push('Right Axis Deviation (RAD)');
    if (stTStatus === 'ST Elevasi') abnormalities.push('ST Segment Elevasi (Suspek Iskemia Akut/Injury)');
    if (stTStatus === 'ST Depresi') abnormalities.push('ST Segment Depresi (Suspek Iskemia Miokard)');
    if (stTStatus === 'T Inverted') abnormalities.push('T Wave Inversion (Suspek Iskemia)');

    return abnormalities.join(', ');
  }, [
    ekg.diagnosisCustom,
    isOverallNormal,
    hrStatus,
    iramaStatus,
    prStatus,
    qrsStatus,
    axisStatus,
    stTStatus,
  ]);

  // Saran Auto-Generation
  const autoSaran = useMemo(() => {
    if (ekg.saranCustom && ekg.saranCustom.trim() !== '') {
      return ekg.saranCustom;
    }
    if (isOverallNormal) {
      return 'Pertahankan gaya hidup sehat dan lakukan pemeriksaan berkala.';
    }
    return 'Konsultasi lebih lanjut dengan dokter spesialis jantung & pembuluh darah (Sp.JP) serta evaluasi kardiologi berkala.';
  }, [ekg.saranCustom, isOverallNormal]);

  // Handler Proses Quick Input Text (e.g. "NORMAL" or raw inputs)
  const handleApplyQuickInput = (textToProcess?: string) => {
    const raw = (textToProcess ?? quickInputText).trim();
    if (!raw || raw.toUpperCase() === 'NORMAL') {
      setEkg(DEFAULT_NORMAL_EKG);
      onNotify('Parameter EKG diisi dengan nilai DEFAULT NORMAL!');
      return;
    }

    // Try parsing custom entries like "HR=80, Irama=Sinus, PR=0.18, QRS=0.09, Axis=30, ST=Normal"
    const next = { ...ekg };
    const lower = raw.toLowerCase();

    // HR match
    const hrMatch = raw.match(/hr\s*[:=]\s*(\d+)/i) || raw.match(/(\d+)\s*bpm/i);
    if (hrMatch) next.hr = parseInt(hrMatch[1], 10);

    // PR match
    const prMatch = raw.match(/pr\s*[:=]\s*([\d.]+)/i);
    if (prMatch) next.pr = parseFloat(prMatch[1]);

    // QRS match
    const qrsMatch = raw.match(/qrs\s*[:=]\s*([\d.]+)/i);
    if (qrsMatch) next.qrs = parseFloat(qrsMatch[1]);

    // Axis match
    const axisMatch = raw.match(/axis\s*[:=]\s*([+-]?\d+)/i);
    if (axisMatch) next.axis = parseInt(axisMatch[1], 10);

    if (lower.includes('aritmia')) next.irama = 'Aritmia';
    if (lower.includes('sinus')) next.irama = 'Sinus Rhythm';
    if (lower.includes('st elevasi')) next.stT = 'ST Elevasi';
    if (lower.includes('st depresi')) next.stT = 'ST Depresi';
    if (lower.includes('t inverted')) next.stT = 'T Inverted';

    setEkg(next);
    onNotify('Data EKG kustom berhasil diterapkan!');
  };

  // Generate exact Markdown matching prompt specification
  const generateMarkdownOutput = (): string => {
    const kesimpulanAkhirStr = isOverallNormal
      ? '[X] EKG NORMAL (Normal Sinus Rhythm) <br> [ ] EKG ABNORMAL'
      : '[ ] EKG NORMAL (Normal Sinus Rhythm) <br> [X] EKG ABNORMAL';

    return `### Tabel Input & Interpretasi EKG

| Parameter EKG | Hasil Input | Nilai Normal | Interpretasi |
| :--- | :---: | :--- | :--- |
| **Laju Jantung (HR)** | ${ekg.hr} bpm | 60 – 100 bpm | ${hrInterpretasiString} |
| **Irama (Rhythm)** | ${ekg.irama} | Regular (Sinus) | ${iramaInterpretasiString} |
| **Interval PR** | ${ekg.pr.toFixed(2).replace('.', ',')} det | 0,12 – 0,20 detik | ${prInterpretasiString} |
| **Durasi QRS** | ${ekg.qrs.toFixed(2).replace('.', ',')} det | 0,06 – 0,12 detik | ${qrsInterpretasiString} |
| **Sumbu (Axis)** | ${ekg.axis > 0 ? `+${ekg.axis}` : ekg.axis}° | -30° s.d. +90° | ${axisInterpretasiString} |
| **Segmen ST & T** | ${ekg.stT} | Isoelektris / Normal | ${stTInterpretasiString} |

### 📋 KESIMPULAN DIAGNOSIS FINAL

| Kesimpulan Akhir: | ${kesimpulanAkhirStr} |
| :--- | :--- |
| **Dokter Pemeriksa/Verifikator:** | ${doctorName} |
| **Diagnosis/Temuan:** | ${autoDiagnosis} |
| **Saran Klinis:** | ${autoSaran} |
`;
  };

  const handleCopyMarkdown = async () => {
    try {
      await navigator.clipboard.writeText(generateMarkdownOutput());
      setCopied(true);
      onNotify('Tabel Input & Interpretasi EKG format Markdown berhasil disalin!');
      setTimeout(() => setCopied(false), 2500);
    } catch {
      onNotify('Gagal menyalin otomatis ke clipboard.');
    }
  };

  const handleSaveToRecord = () => {
    const payload = {
      ekg,
      isOverallNormal,
      diagnosis: autoDiagnosis,
      saran: autoSaran,
      markdown: generateMarkdownOutput(),
    };
    try {
      localStorage.setItem(`simreg_ekg_${patient.mcuNo}`, JSON.stringify(payload));
      saveAutoGeneratedResume(patient.mcuNo);
    } catch (e) {}

    onSave?.(payload);
    onNotify(
      `Hasil EKG (${isOverallNormal ? 'Normal' : 'Abnormal'}) untuk ${patient.nama} (#${patient.mcuNo}) berhasil disimpan!`
    );
  };

  return (
    <div className="space-y-6">
      {/* 1. PERINTAH AWAL (Menunggu Input) */}
      <div className="p-4 sm:p-5 rounded-2xl bg-gradient-to-r from-rose-50 via-red-50 to-pink-50 border border-rose-200 shadow-xs">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-xl bg-rose-600 text-white flex items-center justify-center shrink-0 shadow-md">
            <HeartPulse className="w-5 h-5 animate-pulse" />
          </div>
          <div className="space-y-2 flex-1">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <h4 className="font-extrabold text-[15px] text-rose-950 flex items-center gap-2">
                Pemeriksaan Elektrokardiografi (EKG 12-Lead)
              </h4>
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-1 rounded-lg text-[11.5px] font-bold bg-white text-rose-900 border border-rose-200 shadow-2xs flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                  Dokter Pemeriksa: <b>{doctorName}</b>
                </span>
                <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-rose-100 text-rose-800 border border-rose-300">
                  Kardiologi Okupasi
                </span>
              </div>
            </div>
            <p className="text-[13px] text-slate-700 leading-relaxed">
              Halo! Silakan masukkan data parameter EKG pasien di bawah ini, atau cukup ketik{' '}
              <b className="font-mono text-rose-800 bg-rose-100/80 px-1.5 py-0.5 rounded">
                "NORMAL"
              </b>{' '}
              untuk mengisi seluruh parameter secara otomatis dengan nilai default normal (HR 75 bpm, Sinus Rhythm, PR 0.16 det, QRS 0.08 det, Axis +45°, ST &amp; T Isoelektris).
            </p>

            {/* Quick action bar */}
            <div className="flex flex-wrap items-center gap-2 pt-2">
              <input
                type="text"
                value={quickInputText}
                onChange={(e) => setQuickInputText(e.target.value)}
                placeholder='Ketik "NORMAL" atau custom (e.g. HR=80, Axis=-45)'
                className="px-3 py-1.5 bg-white border border-rose-300 rounded-xl text-xs font-mono font-bold text-slate-800 w-64 focus:ring-2 focus:ring-rose-500 shadow-2xs"
              />
              <button
                type="button"
                onClick={() => handleApplyQuickInput()}
                className="px-3.5 py-1.5 rounded-xl bg-rose-700 hover:bg-rose-800 text-white font-bold text-xs flex items-center gap-1.5 shadow-xs cursor-pointer"
              >
                <Activity className="w-3.5 h-3.5" />
                Terapkan Data
              </button>
              <button
                type="button"
                onClick={() => {
                  setQuickInputText('NORMAL');
                  handleApplyQuickInput('NORMAL');
                }}
                className="px-3 py-1.5 rounded-xl bg-white hover:bg-rose-100 text-rose-800 border border-rose-300 font-bold text-xs flex items-center gap-1 cursor-pointer"
              >
                <Sparkles className="w-3.5 h-3.5 text-rose-600" />
                Isi Default NORMAL
              </button>
            </div>
          </div>
        </div>

        {/* Contoh Preset Klinis */}
        <div className="mt-4 pt-3 border-t border-rose-200/60 flex flex-wrap items-center gap-2">
          <span className="text-xs font-bold text-rose-900 flex items-center gap-1">
            <Sparkles className="w-3.5 h-3.5 text-rose-600" />
            Contoh Kasus Lain:
          </span>
          <button
            type="button"
            onClick={() => {
              setEkg({
                hr: 115,
                irama: 'Sinus Rhythm',
                pr: 0.15,
                qrs: 0.08,
                axis: 50,
                stT: 'Isoelektris (Normal)',
                diagnosisCustom: 'Sinus Takikardia (HR 115 bpm)',
                saranCustom: 'Evaluasi hidrasi, istirahat, hindari kafein, dan re-evaluasi EKG.',
              });
              onNotify('Memuat contoh: Sinus Takikardia (HR 115 bpm)');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-rose-100 text-slate-800 border border-rose-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Sinus Takikardia (115 bpm)
          </button>
          <button
            type="button"
            onClick={() => {
              setEkg({
                hr: 52,
                irama: 'Sinus Rhythm',
                pr: 0.16,
                qrs: 0.08,
                axis: 40,
                stT: 'Isoelektris (Normal)',
                diagnosisCustom: 'Sinus Bradikardia (HR 52 bpm)',
                saranCustom: 'Evaluasi klinis keluhan pusing/lemas, kaji riwayat aktivitas atletik.',
              });
              onNotify('Memuat contoh: Sinus Bradikardia (HR 52 bpm)');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-rose-100 text-slate-800 border border-rose-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Sinus Bradikardia (52 bpm)
          </button>
          <button
            type="button"
            onClick={() => {
              setEkg({
                hr: 82,
                irama: 'Sinus Rhythm',
                pr: 0.16,
                qrs: 0.08,
                axis: -45,
                stT: 'Isoelektris (Normal)',
                diagnosisCustom: 'Left Axis Deviation (LAD -45°)',
                saranCustom: 'Echocardiografi dan evaluasi riwayat hipertensi sistemik.',
              });
              onNotify('Memuat contoh: Left Axis Deviation (LAD -45°)');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-rose-100 text-slate-800 border border-rose-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Left Axis Deviation (LAD)
          </button>
          <button
            type="button"
            onClick={() => {
              setEkg({
                hr: 78,
                irama: 'Sinus Rhythm',
                pr: 0.24,
                qrs: 0.09,
                axis: 45,
                stT: 'Isoelektris (Normal)',
                diagnosisCustom: 'Interval PR Memanjang (AV Block Derajat 1)',
                saranCustom: 'Monitoring konduksi jantung berkala dan evaluasi konsumsi obat.',
              });
              onNotify('Memuat contoh: AV Block Derajat 1 (PR 0.24 det)');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-rose-100 text-slate-800 border border-rose-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            AV Block Derajat 1 (PR Memanjang)
          </button>
        </div>
      </div>

      {/* 2 & 3. TABEL INPUT & INTERPRETASI EKG */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h4 className="font-extrabold text-[15px] text-slate-900 flex items-center gap-2">
            <span>🫀</span>
            Tabel Input &amp; Interpretasi EKG
          </h4>
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="px-3.5 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-bold flex items-center gap-1.5 border border-slate-300 cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Tersalin!' : 'Salin Format Markdown'}
          </button>
        </div>

        <div className="overflow-x-auto rounded-xl border border-slate-200 shadow-2xs">
          <table className="w-full text-left text-[13px] border-collapse min-w-[720px]">
            <thead>
              <tr className="bg-slate-800 text-white font-bold text-[12px]">
                <th className="py-3 px-4 w-48">Parameter EKG</th>
                <th className="py-3 px-4 w-44 text-center">Hasil Input</th>
                <th className="py-3 px-4 w-40">Nilai Normal</th>
                <th className="py-3 px-4">Interpretasi</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 bg-white">
              {/* 1. Laju Jantung (HR) */}
              <tr className={`hover:bg-slate-50/80 ${hrStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Laju Jantung (HR)</td>
                <td className="py-2.5 px-4 text-center">
                  <div className="inline-flex items-center gap-1.5">
                    <input
                      type="number"
                      min="30"
                      max="250"
                      value={ekg.hr}
                      onChange={(e) =>
                        setEkg((prev) => ({
                          ...prev,
                          hr: parseInt(e.target.value, 10) || 0,
                          diagnosisCustom: '',
                        }))
                      }
                      className="w-20 px-2 py-1 text-center font-mono font-bold text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-rose-500"
                    />
                    <span className="text-xs text-slate-600 font-medium">bpm</span>
                  </div>
                </td>
                <td className="py-3 px-4 text-slate-600 font-mono text-xs">60 – 100 bpm</td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-2 text-xs font-mono">
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        hrStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {hrStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        hrStatus === 'Takikardia'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {hrStatus === 'Takikardia' ? '[X]' : '[ ]'} Takikardia
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        hrStatus === 'Bradikardia'
                          ? 'bg-blue-100 text-blue-800 border border-blue-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {hrStatus === 'Bradikardia' ? '[X]' : '[ ]'} Bradikardia
                    </span>
                  </div>
                </td>
              </tr>

              {/* 2. Irama (Rhythm) */}
              <tr className={`hover:bg-slate-50/80 ${iramaStatus !== 'Sinus Rhythm' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Irama (Rhythm)</td>
                <td className="py-2.5 px-4 text-center">
                  <select
                    value={ekg.irama}
                    onChange={(e) =>
                      setEkg((prev) => ({
                        ...prev,
                        irama: e.target.value,
                        diagnosisCustom: '',
                      }))
                    }
                    className="w-36 px-2 py-1 text-center font-bold text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-rose-500"
                  >
                    <option value="Sinus Rhythm">Sinus Rhythm</option>
                    <option value="Aritmia">Aritmia</option>
                    <option value="Atrial Fibrilasi">Atrial Fibrilasi</option>
                    <option value="Sinus Aritmia">Sinus Aritmia</option>
                  </select>
                </td>
                <td className="py-3 px-4 text-slate-600 font-mono text-xs">Regular (Sinus)</td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-2 text-xs font-mono">
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        iramaStatus === 'Sinus Rhythm'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {iramaStatus === 'Sinus Rhythm' ? '[X]' : '[ ]'} Sinus Rhythm
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        iramaStatus === 'Aritmia'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {iramaStatus === 'Aritmia' ? '[X]' : '[ ]'} Aritmia
                    </span>
                  </div>
                </td>
              </tr>

              {/* 3. Interval PR */}
              <tr className={`hover:bg-slate-50/80 ${prStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Interval PR</td>
                <td className="py-2.5 px-4 text-center">
                  <div className="inline-flex items-center gap-1.5">
                    <input
                      type="number"
                      step="0.01"
                      min="0.05"
                      max="0.40"
                      value={ekg.pr}
                      onChange={(e) =>
                        setEkg((prev) => ({
                          ...prev,
                          pr: parseFloat(e.target.value) || 0,
                          diagnosisCustom: '',
                        }))
                      }
                      className="w-20 px-2 py-1 text-center font-mono font-bold text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-rose-500"
                    />
                    <span className="text-xs text-slate-600 font-medium">det</span>
                  </div>
                </td>
                <td className="py-3 px-4 text-slate-600 font-mono text-xs">0,12 – 0,20 detik</td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-2 text-xs font-mono">
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        prStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {prStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        prStatus === 'Memanjang'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {prStatus === 'Memanjang' ? '[X]' : '[ ]'} Memanjang
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        prStatus === 'Memendek'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {prStatus === 'Memendek' ? '[X]' : '[ ]'} Memendek
                    </span>
                  </div>
                </td>
              </tr>

              {/* 4. Durasi QRS */}
              <tr className={`hover:bg-slate-50/80 ${qrsStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Durasi QRS</td>
                <td className="py-2.5 px-4 text-center">
                  <div className="inline-flex items-center gap-1.5">
                    <input
                      type="number"
                      step="0.01"
                      min="0.02"
                      max="0.30"
                      value={ekg.qrs}
                      onChange={(e) =>
                        setEkg((prev) => ({
                          ...prev,
                          qrs: parseFloat(e.target.value) || 0,
                          diagnosisCustom: '',
                        }))
                      }
                      className="w-20 px-2 py-1 text-center font-mono font-bold text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-rose-500"
                    />
                    <span className="text-xs text-slate-600 font-medium">det</span>
                  </div>
                </td>
                <td className="py-3 px-4 text-slate-600 font-mono text-xs">0,06 – 0,12 detik</td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-2 text-xs font-mono">
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        qrsStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {qrsStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        qrsStatus === 'Melebar'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {qrsStatus === 'Melebar' ? '[X]' : '[ ]'} Melebar
                    </span>
                  </div>
                </td>
              </tr>

              {/* 5. Sumbu (Axis) */}
              <tr className={`hover:bg-slate-50/80 ${axisStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Sumbu (Axis)</td>
                <td className="py-2.5 px-4 text-center">
                  <div className="inline-flex items-center gap-1.5">
                    <input
                      type="number"
                      min="-180"
                      max="180"
                      value={ekg.axis}
                      onChange={(e) =>
                        setEkg((prev) => ({
                          ...prev,
                          axis: parseInt(e.target.value, 10) || 0,
                          diagnosisCustom: '',
                        }))
                      }
                      className="w-20 px-2 py-1 text-center font-mono font-bold text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-rose-500"
                    />
                    <span className="text-xs text-slate-600 font-medium">°</span>
                  </div>
                </td>
                <td className="py-3 px-4 text-slate-600 font-mono text-xs">-30° s.d. +90°</td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-2 text-xs font-mono">
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        axisStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {axisStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        axisStatus === 'LAD'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {axisStatus === 'LAD' ? '[X]' : '[ ]'} LAD
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        axisStatus === 'RAD'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {axisStatus === 'RAD' ? '[X]' : '[ ]'} RAD
                    </span>
                  </div>
                </td>
              </tr>

              {/* 6. Segmen ST & T */}
              <tr className={`hover:bg-slate-50/80 ${stTStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Segmen ST &amp; T</td>
                <td className="py-2.5 px-4 text-center">
                  <select
                    value={ekg.stT}
                    onChange={(e) =>
                      setEkg((prev) => ({
                        ...prev,
                        stT: e.target.value,
                        diagnosisCustom: '',
                      }))
                    }
                    className="w-40 px-2 py-1 text-center font-bold text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-rose-500"
                  >
                    <option value="Isoelektris (Normal)">Isoelektris (Normal)</option>
                    <option value="ST Elevasi">ST Elevasi</option>
                    <option value="ST Depresi">ST Depresi</option>
                    <option value="T Inverted">T Inverted</option>
                    <option value="Non Spesifik ST-T Changes">Non Spesifik ST-T</option>
                  </select>
                </td>
                <td className="py-3 px-4 text-slate-600 font-mono text-xs">Isoelektris / Normal</td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-2 text-xs font-mono">
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        stTStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {stTStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        stTStatus === 'ST Elevasi'
                          ? 'bg-red-100 text-red-800 border border-red-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {stTStatus === 'ST Elevasi' ? '[X]' : '[ ]'} ST Elevasi
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        stTStatus === 'ST Depresi'
                          ? 'bg-red-100 text-red-800 border border-red-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {stTStatus === 'ST Depresi' ? '[X]' : '[ ]'} ST Depresi
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        stTStatus === 'T Inverted'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {stTStatus === 'T Inverted' ? '[X]' : '[ ]'} T Inverted
                    </span>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* 4. 📋 KESIMPULAN DIAGNOSIS FINAL */}
      <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-4">
        <h4 className="font-extrabold text-[15px] text-slate-900 flex items-center gap-2 border-b border-slate-200 pb-2">
          <span>📋</span>
          KESIMPULAN DIAGNOSIS FINAL
        </h4>

        <div className="overflow-x-auto rounded-xl border border-slate-200">
          <table className="w-full text-left text-[13px]">
            <tbody className="divide-y divide-slate-200 bg-white">
              {/* Kesimpulan Akhir */}
              <tr>
                <td className="py-3 px-4 font-bold text-slate-900 w-48 bg-slate-50/80">
                  Kesimpulan Akhir:
                </td>
                <td className="py-3 px-4 font-mono font-bold text-[13px]">
                  <div className="flex flex-col gap-1">
                    <span
                      className={`${
                        isOverallNormal
                          ? 'text-emerald-700 bg-emerald-50 px-2 py-1 rounded border border-emerald-200 w-fit'
                          : 'text-slate-400'
                      }`}
                    >
                      {isOverallNormal ? '[X]' : '[ ]'} EKG NORMAL (Normal Sinus Rhythm)
                    </span>
                    <span
                      className={`${
                        !isOverallNormal
                          ? 'text-rose-700 bg-rose-50 px-2 py-1 rounded border border-rose-200 w-fit'
                          : 'text-slate-400'
                      }`}
                    >
                      {!isOverallNormal ? '[X]' : '[ ]'} EKG ABNORMAL
                    </span>
                  </div>
                </td>
              </tr>

              {/* Diagnosis/Temuan */}
              <tr>
                <td className="py-3 px-4 font-bold text-slate-900 bg-slate-50/80">
                  Diagnosis/Temuan:
                </td>
                <td className="py-3 px-4">
                  <div className="space-y-1.5">
                    <input
                      type="text"
                      value={autoDiagnosis}
                      onChange={(e) =>
                        setEkg((prev) => ({
                          ...prev,
                          diagnosisCustom: e.target.value,
                        }))
                      }
                      className="w-full px-3 py-1.5 font-bold text-slate-900 bg-slate-50 border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-rose-500"
                    />
                    <div className="text-[11px] text-slate-500">
                      Diagnosis dapat diedit manual atau akan otomatis menyesuaikan parameter input.
                    </div>
                  </div>
                </td>
              </tr>

              {/* Saran Klinis */}
              <tr>
                <td className="py-3 px-4 font-bold text-slate-900 bg-slate-50/80">
                  Saran Klinis:
                </td>
                <td className="py-3 px-4">
                  <div className="space-y-1.5">
                    <input
                      type="text"
                      value={autoSaran}
                      onChange={(e) =>
                        setEkg((prev) => ({
                          ...prev,
                          saranCustom: e.target.value,
                        }))
                      }
                      className="w-full px-3 py-1.5 text-slate-900 bg-slate-50 border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-rose-500"
                    />
                    <div className="text-[11px] text-slate-500">
                      Saran rekomendasi tindak lanjut bagi dokter pemeriksa &amp; rekam medis.
                    </div>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="pt-2 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200">
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleSaveToRecord}
            className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-rose-700 to-red-700 hover:from-rose-800 hover:to-red-800 text-white font-bold text-xs flex items-center gap-2 shadow-md shadow-rose-900/20 cursor-pointer"
          >
            <CheckCircle2 className="w-4 h-4" />
            Simpan Hasil EKG Pasien #{patient.mcuNo}
          </button>
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="px-4 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold text-xs flex items-center gap-1.5 border border-slate-300 cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            Salin Tabel Markdown EKG
          </button>
        </div>

        <div className="text-xs text-slate-500 font-medium">
          Pasien: <b className="text-slate-800">{patient.nama}</b> ({patient.pt}) • No. MCU #{patient.mcuNo}
        </div>
      </div>
    </div>
  );
};
