import React, { useState, useMemo, useEffect } from 'react';
import {
  FlaskConical,
  Droplets,
  CheckCircle2,
  AlertTriangle,
  RotateCcw,
  Sparkles,
  FileText,
  Copy,
  Check,
  Stethoscope,
  Info,
  ShieldCheck,
  Search,
} from 'lucide-react';
import { AttendanceRecord } from '../types';
import { saveAutoGeneratedResume } from '../utils/medicalResumeGenerator';
import { evaluateLabItemStatus } from '../utils/labEvaluator';

interface LaboratoriumFormProps {
  patient: AttendanceRecord;
  examinerDoctor?: string;
  onNotify: (msg: string) => void;
  onSave?: (result: any) => void;
}

export interface LabItem {
  id: string;
  category: 'Hematologi' | 'Kimia Darah' | 'Urinalisis';
  subCategory?: string;
  name: string;
  value: string;
  unit: string;
  refRange: string;
  status: 'Normal' | 'Tinggi' | 'Rendah' | 'Abnormal';
}

export const DEFAULT_LAB_ITEMS: LabItem[] = [
  // 1. HEMATOLOGI LENGKAP
  { id: 'hb', category: 'Hematologi', subCategory: 'Darah Rutin', name: 'Hemoglobin (Hb)', value: '14.8', unit: 'g/dL', refRange: '13.5 - 17.5', status: 'Normal' },
  { id: 'leuko', category: 'Hematologi', subCategory: 'Darah Rutin', name: 'Leukosit (WBC)', value: '6.800', unit: '/µL', refRange: '4.500 - 10.000', status: 'Normal' },
  { id: 'eri', category: 'Hematologi', subCategory: 'Darah Rutin', name: 'Eritrosit (RBC)', value: '4.85', unit: 'juta/µL', refRange: '4.50 - 5.50', status: 'Normal' },
  { id: 'ht', category: 'Hematologi', subCategory: 'Darah Rutin', name: 'Hematokrit (Ht)', value: '44.0', unit: '%', refRange: '40.0 - 52.0', status: 'Normal' },
  { id: 'trombo', category: 'Hematologi', subCategory: 'Darah Rutin', name: 'Trombosit (PLT)', value: '245.000', unit: '/µL', refRange: '150.000 - 450.000', status: 'Normal' },
  { id: 'led', category: 'Hematologi', subCategory: 'Darah Rutin', name: 'Laju Endap Darah (LED)', value: '8', unit: 'mm/jam', refRange: '0 - 15', status: 'Normal' },
  
  // Hitung Jenis Leukosit (Diff Count)
  { id: 'baso', category: 'Hematologi', subCategory: 'Hitung Jenis (Diff Count)', name: 'Basofil', value: '0', unit: '%', refRange: '0 - 1', status: 'Normal' },
  { id: 'eosi', category: 'Hematologi', subCategory: 'Hitung Jenis (Diff Count)', name: 'Eosinofil', value: '2', unit: '%', refRange: '1 - 3', status: 'Normal' },
  { id: 'batang', category: 'Hematologi', subCategory: 'Hitung Jenis (Diff Count)', name: 'Neutrofil Batang', value: '3', unit: '%', refRange: '2 - 6', status: 'Normal' },
  { id: 'segmen', category: 'Hematologi', subCategory: 'Hitung Jenis (Diff Count)', name: 'Neutrofil Segmen', value: '62', unit: '%', refRange: '50 - 70', status: 'Normal' },
  { id: 'limfosit', category: 'Hematologi', subCategory: 'Hitung Jenis (Diff Count)', name: 'Limfosit', value: '28', unit: '%', refRange: '20 - 40', status: 'Normal' },
  { id: 'monosit', category: 'Hematologi', subCategory: 'Hitung Jenis (Diff Count)', name: 'Monosit', value: '5', unit: '%', refRange: '2 - 8', status: 'Normal' },

  // 2. KIMIA DARAH
  // Fungsi Hati
  { id: 'sgot', category: 'Kimia Darah', subCategory: 'Fungsi Hati', name: 'SGOT (AST)', value: '22', unit: 'U/L', refRange: '< 37', status: 'Normal' },
  { id: 'sgpt', category: 'Kimia Darah', subCategory: 'Fungsi Hati', name: 'SGPT (ALT)', value: '25', unit: 'U/L', refRange: '< 42', status: 'Normal' },
  { id: 'bili_tot', category: 'Kimia Darah', subCategory: 'Fungsi Hati', name: 'Bilirubin Total', value: '0.8', unit: 'mg/dL', refRange: '0.2 - 1.2', status: 'Normal' },
  
  // Fungsi Ginjal & Asam Urat
  { id: 'ureum', category: 'Kimia Darah', subCategory: 'Fungsi Ginjal & Asam Urat', name: 'Ureum', value: '28', unit: 'mg/dL', refRange: '15 - 45', status: 'Normal' },
  { id: 'kreatinin', category: 'Kimia Darah', subCategory: 'Fungsi Ginjal & Asam Urat', name: 'Kreatinin', value: '0.9', unit: 'mg/dL', refRange: '0.7 - 1.3', status: 'Normal' },
  { id: 'asam_urat', category: 'Kimia Darah', subCategory: 'Fungsi Ginjal & Asam Urat', name: 'Asam Urat', value: '5.4', unit: 'mg/dL', refRange: '3.4 - 7.0', status: 'Normal' },
  
  // Profil Lemak
  { id: 'kol_tot', category: 'Kimia Darah', subCategory: 'Profil Lemak (Lipid)', name: 'Kolesterol Total', value: '175', unit: 'mg/dL', refRange: '< 200', status: 'Normal' },
  { id: 'trigliserida', category: 'Kimia Darah', subCategory: 'Profil Lemak (Lipid)', name: 'Trigliserida', value: '120', unit: 'mg/dL', refRange: '< 150', status: 'Normal' },
  { id: 'hdl', category: 'Kimia Darah', subCategory: 'Profil Lemak (Lipid)', name: 'Kolesterol HDL', value: '52', unit: 'mg/dL', refRange: '> 40', status: 'Normal' },
  { id: 'ldl', category: 'Kimia Darah', subCategory: 'Profil Lemak (Lipid)', name: 'Kolesterol LDL', value: '99', unit: 'mg/dL', refRange: '< 100', status: 'Normal' },
  
  // Glukosa Darah
  { id: 'gdp', category: 'Kimia Darah', subCategory: 'Metabolisme Glukosa', name: 'Gula Darah Puasa (GDP)', value: '88', unit: 'mg/dL', refRange: '70 - 100', status: 'Normal' },
  { id: 'gds', category: 'Kimia Darah', subCategory: 'Metabolisme Glukosa', name: 'Gula Darah Sewaktu (GDS)', value: '110', unit: 'mg/dL', refRange: '< 140', status: 'Normal' },

  // 3. URINALISIS (URINE LENGKAP)
  // Makroskopis
  { id: 'warna', category: 'Urinalisis', subCategory: 'Fisik / Makroskopis', name: 'Warna Urine', value: 'Kuning Muda', unit: '-', refRange: 'Kuning Muda / Jernih', status: 'Normal' },
  { id: 'kejernihan', category: 'Urinalisis', subCategory: 'Fisik / Makroskopis', name: 'Kejernihan', value: 'Jernih', unit: '-', refRange: 'Jernih', status: 'Normal' },
  { id: 'bj', category: 'Urinalisis', subCategory: 'Fisik / Makroskopis', name: 'Berat Jenis (BJ)', value: '1.015', unit: '-', refRange: '1.005 - 1.030', status: 'Normal' },
  { id: 'ph', category: 'Urinalisis', subCategory: 'Fisik / Makroskopis', name: 'pH Urine', value: '6.5', unit: '-', refRange: '4.8 - 7.5', status: 'Normal' },
  
  // Kimia Urine
  { id: 'u_protein', category: 'Urinalisis', subCategory: 'Kimia Urin', name: 'Protein (Albumin)', value: 'Negatif', unit: '-', refRange: 'Negatif', status: 'Normal' },
  { id: 'u_glukosa', category: 'Urinalisis', subCategory: 'Kimia Urin', name: 'Glukosa (Reduksi)', value: 'Negatif', unit: '-', refRange: 'Negatif', status: 'Normal' },
  { id: 'u_bilirubin', category: 'Urinalisis', subCategory: 'Kimia Urin', name: 'Bilirubin Urine', value: 'Negatif', unit: '-', refRange: 'Negatif', status: 'Normal' },
  { id: 'u_urobilinogen', category: 'Urinalisis', subCategory: 'Kimia Urin', name: 'Urobilinogen', value: 'Normal', unit: 'E.U/dL', refRange: '0.1 - 1.0', status: 'Normal' },
  { id: 'u_keton', category: 'Urinalisis', subCategory: 'Kimia Urin', name: 'Keton', value: 'Negatif', unit: '-', refRange: 'Negatif', status: 'Normal' },
  { id: 'u_nitrit', category: 'Urinalisis', subCategory: 'Kimia Urin', name: 'Nitrit', value: 'Negatif', unit: '-', refRange: 'Negatif', status: 'Normal' },
  { id: 'u_blood', category: 'Urinalisis', subCategory: 'Kimia Urin', name: 'Darah Samar (Blood)', value: 'Negatif', unit: '-', refRange: 'Negatif', status: 'Normal' },

  // Sedimen Mikroskopis
  { id: 'u_sed_leuko', category: 'Urinalisis', subCategory: 'Sedimen Mikroskopis', name: 'Leukosit Urine', value: '1 - 2', unit: '/LPB', refRange: '0 - 5', status: 'Normal' },
  { id: 'u_sed_eri', category: 'Urinalisis', subCategory: 'Sedimen Mikroskopis', name: 'Eritrosit Urine', value: '0 - 1', unit: '/LPB', refRange: '0 - 2', status: 'Normal' },
  { id: 'u_sed_epitel', category: 'Urinalisis', subCategory: 'Sedimen Mikroskopis', name: 'Sel Epitel Gepeng', value: 'Positif (+)', unit: '-', refRange: 'Positif (+)', status: 'Normal' },
  { id: 'u_sed_kristal', category: 'Urinalisis', subCategory: 'Sedimen Mikroskopis', name: 'Kristal Urine', value: 'Negatif', unit: '-', refRange: 'Negatif', status: 'Normal' },
  { id: 'u_sed_bakteri', category: 'Urinalisis', subCategory: 'Sedimen Mikroskopis', name: 'Bakteri', value: 'Negatif', unit: '-', refRange: 'Negatif', status: 'Normal' },

  // Skrining Narkoba K3
  { id: 'narkoba_amp', category: 'Urinalisis', subCategory: 'Skrining Narkoba K3', name: 'Amphetamine (AMP)', value: 'Negatif', unit: '-', refRange: 'Negatif', status: 'Normal' },
  { id: 'narkoba_thc', category: 'Urinalisis', subCategory: 'Skrining Narkoba K3', name: 'THC / Ganja (Marijuana)', value: 'Negatif', unit: '-', refRange: 'Negatif', status: 'Normal' },
];

export const LaboratoriumForm: React.FC<LaboratoriumFormProps> = ({
  patient,
  examinerDoctor = 'dr. Kevin Hendrawan, Sp.PK',
  onNotify,
  onSave,
}) => {
  const [activeTab, setActiveTab] = useState<'SEMUA' | 'Hematologi' | 'Kimia Darah' | 'Urinalisis'>('SEMUA');
  const [labItems, setLabItems] = useState<LabItem[]>(DEFAULT_LAB_ITEMS);
  const [searchTerm, setSearchTerm] = useState('');
  const [doctorName, setDoctorName] = useState(examinerDoctor);
  const [kesimpulanCustom, setKesimpulanCustom] = useState('');
  const [copied, setCopied] = useState(false);

  // Load saved lab data for patient
  useEffect(() => {
    if (!patient?.mcuNo) return;
    try {
      const saved = localStorage.getItem(`simreg_lab_${patient.mcuNo}`);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed.items && Array.isArray(parsed.items)) {
          const recheckedItems = parsed.items.map((it: LabItem) => {
            const autoStatus = evaluateLabItemStatus(it);
            let effectiveStatus = it.status;
            if (!effectiveStatus) {
              effectiveStatus = autoStatus;
            } else if (
              (it.id === 'bj' || (it.name && it.name.toLowerCase().includes('berat jenis'))) &&
              it.status === 'Tinggi' &&
              autoStatus === 'Normal'
            ) {
              // Pulihkan data BJ yang sempat salah tersimpan sebagai Tinggi karena bug parser
              effectiveStatus = 'Normal';
            }
            return {
              ...it,
              status: effectiveStatus,
            };
          });
          setLabItems(recheckedItems);
        }
        if (parsed.doctor) setDoctorName(parsed.doctor);
        if (parsed.summary) setKesimpulanCustom(parsed.summary);
      }
    } catch (e) {}
  }, [patient?.mcuNo]);

  // Update item value and automatically determine status
  const handleValueChange = (id: string, newValue: string) => {
    setLabItems((prev) =>
      prev.map((item) => {
        if (item.id === id) {
          const autoStatus = evaluateLabItemStatus({ ...item, value: newValue });
          return { ...item, value: newValue, status: autoStatus };
        }
        return item;
      })
    );
  };

  const handleStatusChange = (id: string, newStatus: LabItem['status']) => {
    setLabItems((prev) =>
      prev.map((item) => {
        if (item.id === id) {
          return { ...item, status: newStatus };
        }
        return item;
      })
    );
  };

  // Reset all to standard healthy normal
  const handleResetNormal = () => {
    setLabItems(DEFAULT_LAB_ITEMS);
    setKesimpulanCustom('');
    onNotify('Semua parameter Laboratorium (Hematologi, Kimia Darah, Urinalisis) diatur ke Nilai Rujukan Sehat.');
  };

  // Summary counts
  const countAbnormal = useMemo(() => {
    return labItems.filter((i) => i.status !== 'Normal').length;
  }, [labItems]);

  const isAllNormal = countAbnormal === 0;

  // Filtered items
  const filteredItems = useMemo(() => {
    return labItems.filter((item) => {
      const matchCategory = activeTab === 'SEMUA' || item.category === activeTab;
      const matchSearch =
        searchTerm === '' ||
        item.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        (item.subCategory && item.subCategory.toLowerCase().includes(searchTerm.toLowerCase()));
      return matchCategory && matchSearch;
    });
  }, [labItems, activeTab, searchTerm]);

  // Grouped by subCategory for clean rendering
  const groupedItems: Record<string, LabItem[]> = useMemo(() => {
    const groups: Record<string, LabItem[]> = {};
    filteredItems.forEach((item) => {
      const key = `${item.category} - ${item.subCategory || 'Umum'}`;
      if (!groups[key]) groups[key] = [];
      groups[key].push(item);
    });
    return groups;
  }, [filteredItems]);

  // Auto-generate text summary
  const generatedSummary = useMemo(() => {
    if (isAllNormal) {
      return `Hasil pemeriksaan Laboratorium lengkap (Hematologi rutin & hitung jenis, Kimia Darah meliputi profil lipid, fungsi hati, ginjal, gula darah, serta Urinalisis lengkap dan skrining narkoba) seluruhnya berada dalam BATAS NORMAL (Normal Limits). Tidak ditemukan kelainan patologis klinis yang signifikan.`;
    }
    const abnormalList = labItems
      .filter((i) => i.status !== 'Normal')
      .map((i) => `${i.name}: ${i.value} ${i.unit} (${i.status})`)
      .join(', ');
    return `Ditemukan parameter laboratorium di luar nilai rujukan normal: ${abnormalList}. Disarankan evaluasi klinis berkala dan konsultasi lanjutan dengan dokter spesialis patologi klinik.`;
  }, [isAllNormal, labItems]);

  const handleCopySummary = () => {
    const textToCopy = `LABORATORIUM REPORT (${patient.nama} - #${patient.mcuNo})\nDokter Patologi Klinik: ${doctorName}\nStatus: ${isAllNormal ? 'NORMAL' : 'ABNORMAL'}\n\nRingkasan:\n${kesimpulanCustom || generatedSummary}`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    onNotify('Ringkasan hasil laboratorium berhasil disalin ke clipboard!');
  };

  const handleSave = () => {
    // Pastikan seluruh item tersimpan dengan status pilihan pengguna (jangan menimpa pilihan manual 'Normal' yang dipilih dokter)
    const finalItems = labItems.map((item) => {
      // Prioritaskan status yang saat ini aktif di tabel / dropdown
      const effectiveStatus = item.status || evaluateLabItemStatus(item);
      return { ...item, status: effectiveStatus };
    });

    const finalAbnormalCount = finalItems.filter((i) => i.status !== 'Normal').length;
    const finalIsAllNormal = finalAbnormalCount === 0;

    let finalSummary = kesimpulanCustom;
    // Jika ringkasan kosong atau ringkasan lama menyebutkan abnormal padahal sekarang sudah normal semua, atau menyebutkan Berat Jenis abnormal padahal sekarang normal
    const hasStaleBjSummary =
      finalSummary.includes('Berat Jenis') &&
      !finalItems.some(
        (i) =>
          (i.id === 'bj' || (i.name && i.name.toLowerCase().includes('berat jenis'))) &&
          i.status !== 'Normal'
      );

    if (
      !finalSummary ||
      (finalIsAllNormal && finalSummary.includes('di luar nilai rujukan normal')) ||
      hasStaleBjSummary
    ) {
      if (finalIsAllNormal) {
        finalSummary = `Hasil pemeriksaan Laboratorium lengkap (Hematologi rutin & hitung jenis, Kimia Darah meliputi profil lipid, fungsi hati, ginjal, gula darah, serta Urinalisis lengkap dan skrining narkoba) seluruhnya berada dalam BATAS NORMAL (Normal Limits). Tidak ditemukan kelainan patologis klinis yang signifikan.`;
      } else {
        const abnormalList = finalItems
          .filter((i) => i.status !== 'Normal')
          .map((i) => `${i.name}: ${i.value} ${i.unit} (${i.status})`)
          .join(', ');
        finalSummary = `Ditemukan parameter laboratorium di luar nilai rujukan normal: ${abnormalList}. Disarankan evaluasi klinis berkala dan konsultasi lanjutan dengan dokter spesialis patologi klinik.`;
      }
      setKesimpulanCustom(finalSummary);
    }

    const resultPayload = {
      patientMcuNo: patient.mcuNo,
      patientName: patient.nama,
      doctor: doctorName,
      isAllNormal: finalIsAllNormal,
      abnormalCount: finalAbnormalCount,
      summary: finalSummary,
      items: finalItems,
      date: new Date().toISOString(),
    };

    try {
      localStorage.setItem(`simreg_lab_${patient.mcuNo}`, JSON.stringify(resultPayload));
      // Otomatis kalkulasi dan sinkronkan ke Resume Medis Okupasi
      saveAutoGeneratedResume(patient.mcuNo);
    } catch (e) {}

    onSave?.(resultPayload);
    onNotify(`Hasil Laboratorium Terpadu untuk ${patient.nama} (${patient.mcuNo}) berhasil disimpan ke Rekam Medis & sinkron otomatis ke Resume Medis!`);
  };

  return (
    <div className="space-y-6">
      {/* 1. Header Banner & Doctor Stamp */}
      <div className="bg-gradient-to-r from-slate-900 via-slate-800 to-indigo-950 border border-slate-700/80 rounded-2xl p-5 shadow-lg text-white">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
          <div className="flex items-start sm:items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-indigo-500 to-cyan-500 text-white flex items-center justify-center text-2xl shrink-0 shadow-md">
              🧪
            </div>
            <div>
              <div className="flex flex-wrap items-center gap-2 mb-1">
                <span className="text-xs font-mono font-bold text-indigo-400 uppercase tracking-wider">
                  [SIMREG] Modul Laboratorium Terpadu
                </span>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 font-semibold border border-emerald-500/30">
                  Hema + Kimia + Urine (Unified)
                </span>
              </div>
              <h3 className="text-lg font-bold tracking-tight">
                Pemeriksaan Laboratorium: {patient.nama} ({patient.mcuNo})
              </h3>
              <p className="text-xs text-slate-300">
                PT: <span className="font-semibold text-white">{patient.pt}</span> &bull; Departemen: {patient.dept || '-'} &bull; Status Puasa: {patient.tidakPuasa ? '❌ Tidak Puasa' : '✅ Puasa'}
              </p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <button
              type="button"
              onClick={handleResetNormal}
              className="px-3 py-1.5 bg-slate-700/80 hover:bg-slate-700 text-slate-200 hover:text-white rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer border border-slate-600"
            >
              <RotateCcw className="w-3.5 h-3.5 text-cyan-400" />
              <span>Set Semua Normal</span>
            </button>
            <button
              type="button"
              onClick={handleCopySummary}
              className="px-3 py-1.5 bg-slate-700/80 hover:bg-slate-700 text-slate-200 hover:text-white rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer border border-slate-600"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-indigo-300" />}
              <span>{copied ? 'Tersalin' : 'Salin Resume'}</span>
            </button>
          </div>
        </div>

        {/* Doctor Verification Row */}
        <div className="mt-4 pt-3 border-t border-slate-700/60 flex flex-wrap items-center justify-between gap-3 text-xs">
          <div className="flex items-center gap-2">
            <Stethoscope className="w-4 h-4 text-cyan-400" />
            <span className="text-slate-400">Dokter Patologi Klinik (Sp.PK):</span>
            <input
              type="text"
              value={doctorName}
              onChange={(e) => setDoctorName(e.target.value)}
              className="px-2.5 py-0.5 bg-slate-800 border border-slate-600 rounded-lg text-white font-semibold text-xs focus:outline-none focus:border-cyan-400"
            />
          </div>

          <div className="flex items-center gap-3 font-mono">
            <span className="text-slate-400 text-[11px]">Status Evaluasi:</span>
            {isAllNormal ? (
              <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 font-bold text-[11px] border border-emerald-500/30">
                <CheckCircle2 className="w-3.5 h-3.5" />
                Semua Parameter Normal (30 Item)
              </span>
            ) : (
              <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-rose-500/20 text-rose-300 font-bold text-[11px] border border-rose-500/30">
                <AlertTriangle className="w-3.5 h-3.5" />
                {countAbnormal} Parameter Di Luar Batas Normal
              </span>
            )}
          </div>
        </div>
      </div>

      {/* 2. Navigation Category Tabs & Search */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3">
        {/* Category Tabs */}
        <div className="inline-flex p-1 bg-slate-100 rounded-xl border border-slate-200 text-xs font-semibold overflow-x-auto">
          {[
            { id: 'SEMUA', label: 'Semua Item Lab', count: labItems.length },
            { id: 'Hematologi', label: '1. Hematologi Lengkap', count: labItems.filter((i) => i.category === 'Hematologi').length },
            { id: 'Kimia Darah', label: '2. Kimia Darah & Lemak', count: labItems.filter((i) => i.category === 'Kimia Darah').length },
            { id: 'Urinalisis', label: '3. Urinalisis & Narkoba', count: labItems.filter((i) => i.category === 'Urinalisis').length },
          ].map((tab) => (
            <button
              key={tab.id}
              type="button"
              onClick={() => setActiveTab(tab.id as any)}
              className={`px-3.5 py-1.5 rounded-lg transition-all cursor-pointer whitespace-nowrap flex items-center gap-1.5 ${
                activeTab === tab.id
                  ? 'bg-white text-indigo-900 shadow-xs font-bold border border-slate-200'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <span>{tab.label}</span>
              <span className={`text-[10px] px-1.5 py-0.2 rounded-full ${activeTab === tab.id ? 'bg-indigo-100 text-indigo-700' : 'bg-slate-200 text-slate-500'}`}>
                {tab.count}
              </span>
            </button>
          ))}
        </div>

        {/* Quick Search */}
        <div className="relative w-full sm:w-64">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none" />
          <input
            type="text"
            placeholder="Cari parameter lab..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-9 pr-3 py-1.5 bg-white border border-slate-200 rounded-xl text-xs text-slate-800 placeholder-slate-400 focus:outline-none focus:border-indigo-500 shadow-2xs"
          />
        </div>
      </div>

      {/* 3. Tables by Grouped Subcategories */}
      <div className="space-y-5">
        {Object.keys(groupedItems).length === 0 ? (
          <div className="p-8 text-center bg-slate-50 border border-dashed border-slate-200 rounded-2xl text-slate-500 text-xs">
            Tidak ada parameter laboratorium yang cocok dengan pencarian "{searchTerm}".
          </div>
        ) : (
          (Object.entries(groupedItems) as [string, LabItem[]][]).map(([groupTitle, items]) => (
            <div key={groupTitle} className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-2xs">
              {/* Group Header */}
              <div className="bg-slate-50/80 px-4 py-2.5 border-b border-slate-200 flex items-center justify-between">
                <h4 className="text-xs font-bold text-slate-800 flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-indigo-500"></span>
                  {groupTitle}
                </h4>
                <span className="text-[11px] text-slate-500 font-medium">
                  {items.length} parameter
                </span>
              </div>

              {/* Parameter Table */}
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead>
                    <tr className="bg-slate-100/50 text-[11px] font-semibold text-slate-600 border-b border-slate-200">
                      <th className="py-2.5 px-4 w-1/3">Parameter Pemeriksaan</th>
                      <th className="py-2.5 px-4 w-1/4">Hasil Terukur</th>
                      <th className="py-2.5 px-4 w-20">Satuan</th>
                      <th className="py-2.5 px-4 w-1/4">Nilai Rujukan Normal</th>
                      <th className="py-2.5 px-4 text-right">Status Evaluasi</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {items.map((item) => {
                      const isItemNormal = item.status === 'Normal';
                      return (
                        <tr
                          key={item.id}
                          className={`hover:bg-slate-50/80 transition-colors ${
                            !isItemNormal ? 'bg-rose-50/30' : ''
                          }`}
                        >
                          <td className="py-2.5 px-4 font-semibold text-slate-900">
                            {item.name}
                          </td>
                          <td className="py-2.5 px-4">
                            <input
                              type="text"
                              value={item.value}
                              onChange={(e) => handleValueChange(item.id, e.target.value)}
                              className={`w-36 px-2.5 py-1 bg-white border rounded-lg text-xs font-mono font-semibold transition-all focus:outline-none ${
                                isItemNormal
                                  ? 'border-slate-300 text-slate-900 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500'
                                  : 'border-rose-300 text-rose-800 bg-rose-50/50 focus:border-rose-500 focus:ring-1 focus:ring-rose-500'
                              }`}
                            />
                          </td>
                          <td className="py-2.5 px-4 text-slate-500 font-mono text-[11px]">
                            {item.unit}
                          </td>
                          <td className="py-2.5 px-4 text-slate-600 font-mono text-[11px]">
                            {item.refRange}
                          </td>
                          <td className="py-2.5 px-4 text-right">
                            <select
                              value={item.status}
                              onChange={(e) => handleStatusChange(item.id, e.target.value as any)}
                              className={`px-2.5 py-1 rounded-lg text-[11px] font-bold border transition-colors cursor-pointer ${
                                item.status === 'Normal'
                                  ? 'bg-emerald-50 text-emerald-700 border-emerald-300'
                                  : item.status === 'Tinggi'
                                  ? 'bg-rose-50 text-rose-700 border-rose-300'
                                  : item.status === 'Rendah'
                                  ? 'bg-amber-50 text-amber-700 border-amber-300'
                                  : 'bg-purple-50 text-purple-700 border-purple-300'
                              }`}
                            >
                              <option value="Normal">Normal</option>
                              <option value="Tinggi">Tinggi (High)</option>
                              <option value="Rendah">Rendah (Low)</option>
                              <option value="Abnormal">Abnormal / Positif</option>
                            </select>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          ))
        )}
      </div>

      {/* 4. Kesimpulan & Verifikasi Dokter Sp.PK */}
      <div className="bg-slate-50 border border-slate-200 rounded-2xl p-5 space-y-4 shadow-2xs">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-xs font-bold text-slate-800">
            <FileText className="w-4 h-4 text-indigo-600" />
            <span>Kesimpulan &amp; Catatan Khusus Dokter Patologi Klinik</span>
          </div>
          <span className="text-[11px] text-slate-500">
            Tercetak pada Lembar Hasil MCU
          </span>
        </div>

        <textarea
          rows={3}
          value={kesimpulanCustom || generatedSummary}
          onChange={(e) => setKesimpulanCustom(e.target.value)}
          className="w-full p-3 bg-white border border-slate-300 rounded-xl text-xs text-slate-800 focus:outline-none focus:border-indigo-500 leading-relaxed font-sans shadow-2xs"
          placeholder="Tuliskan catatan khusus hasil laboratorium di sini..."
        />

        <div className="flex flex-wrap items-center justify-between gap-3 pt-1">
          <div className="flex items-center gap-2 text-[11px] text-slate-500">
            <Info className="w-3.5 h-3.5 text-indigo-500" />
            <span>
              Semua hasil terintegrasi: Hematologi, Kimia Darah, dan Urinalisis telah disatukan dalam satu dokumen rekam medis.
            </span>
          </div>

          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={handleSave}
              className="px-6 py-2.5 bg-gradient-to-r from-indigo-600 to-cyan-600 hover:from-indigo-500 hover:to-cyan-500 text-white font-bold text-xs rounded-xl shadow-md shadow-indigo-600/20 transition-all cursor-pointer active:scale-95 flex items-center gap-2"
            >
              <CheckCircle2 className="w-4 h-4" />
              <span>Simpan Hasil Laboratorium</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
