import React, { useState, useMemo } from 'react';
import {
  Activity,
  Eye,
  HeartPulse,
  User,
  CheckCircle2,
  AlertTriangle,
  FileText,
  Save,
  RotateCcw,
  Sparkles,
  Stethoscope,
  Info,
  Scale,
} from 'lucide-react';
import { AttendanceRecord, MedicalAdviceMaster } from '../types';
import { initialMedicalAdvices } from '../data/initialData';
import { saveAutoGeneratedResume } from '../utils/medicalResumeGenerator';
import { saveExamResultToCloud } from '../lib/firebase';

interface PemeriksaanFisikFormProps {
  patient: AttendanceRecord;
  examinerDoctor?: string;
  onSave?: (data: any) => void;
  onNotify: (message: string) => void;
}

export interface FisikMataData {
  // Vital Signs
  tensiSistole: number;
  tensiDiastole: number;
  nadi: number;
  pernapasan: number;
  suhu: number;
  spo2: number;
  
  // Antropometri
  tinggiBadan: number;
  beratBadan: number;
  lingkarPerut: number;

  // Mata & Penglihatan (Terintegrasi)
  visusOdTanpaKacamata: string;
  visusOsTanpaKacamata: string;
  visusOdKacamata: string;
  visusOsKacamata: string;
  visusDekat: string;
  ishiharaButaWarna: 'Normal' | 'Buta Warna Parsial' | 'Buta Warna Total';
  konjungtiva: 'Normal (Tidak Anemis)' | 'Anemis' | 'Hiperemis';
  sklera: 'Normal (Tidak Ikterik)' | 'Ikterik';
  kornea: 'Jernih' | 'Keruh' | 'Sikatriks';
  lensa: 'Jernih' | 'Katarak Imatur' | 'Katarak Matur';
  lapangPandang: 'Normal' | 'Menyempit';
  gerakBolaMata: 'Bebas ke Segala Arah' | 'Terbatas';

  // Status Generalis
  kepalaLeher: string;
  tht: string;
  gigiMulut: string;
  jantung: string;
  paru: string;
  abdomen: string;
  ekstremitas: string;
  kulit: string;

  // Kesimpulan & Saran
  kesimpulan: string;
  catatanKhusus: string;
  saranDokter: string;
}

export const DEFAULT_FISIK_MATA: FisikMataData = {
  tensiSistole: 120,
  tensiDiastole: 80,
  nadi: 78,
  pernapasan: 18,
  suhu: 36.5,
  spo2: 99,

  tinggiBadan: 170,
  beratBadan: 65,
  lingkarPerut: 78,

  visusOdTanpaKacamata: '6/6',
  visusOsTanpaKacamata: '6/6',
  visusOdKacamata: '-',
  visusOsKacamata: '-',
  visusDekat: 'J1 (Normal)',
  ishiharaButaWarna: 'Normal',
  konjungtiva: 'Normal (Tidak Anemis)',
  sklera: 'Normal (Tidak Ikterik)',
  kornea: 'Jernih',
  lensa: 'Jernih',
  lapangPandang: 'Normal',
  gerakBolaMata: 'Bebas ke Segala Arah',

  kepalaLeher: 'Normocephal, Pembesaran KGB (-), Pembesaran Kelenjar Tiroid (-), JVP normal.',
  tht: 'Telinga: Membran timpani intak kanan/kiri, serumen (-). Hidung: Septum deviasi (-). Tenggorokan: Faring hiperemis (-), Tonsil T1-T1.',
  gigiMulut: 'Higienis baik, karies gigi (-), karang gigi minimal, gigi berlubang (-).',
  jantung: 'Inspeksi & palpasi ictus cordis tidak bergeser. Auskultasi: Bunyi jantung I - II murni reguler, murmur (-), gallop (-).',
  paru: 'Gerakan dinding dada simetris statis/dinamis. Auskultasi: Suara nafas dasar vesikuler +/+, rhonki -/-, wheezing -/-.',
  abdomen: 'Dinding perut supel, datar, bising usus normal (8x/m), hepar & lien tidak teraba membesar, nyeri tekan (-).',
  ekstremitas: 'Akral hangat, CRT < 2 detik, tidak ada edema pada kedua tungkai, varises (-), refleks fisiologis +/+, patologis -/-.',
  kulit: 'Turgor kulit baik, kelainan dermatologis (-), ruam/alergi (-).',

  kesimpulan: 'Pemeriksaan fisik umum dan fungsi mata/visus dalam batas normal (Fit to Work).',
  catatanKhusus: 'Tidak ditemukan kelainan fisik bermakna.',
  saranDokter: 'Pertahankan pola hidup sehat, olahraga rutin, konsumsi makanan bergizi seimbang, dan istirahatkan mata secara berkala saat bekerja di depan layar monitor.',
};

export const PemeriksaanFisikForm: React.FC<PemeriksaanFisikFormProps> = ({
  patient,
  examinerDoctor,
  onSave,
  onNotify,
}) => {
  const [formData, setFormData] = useState<FisikMataData>(() => {
    try {
      const saved = localStorage.getItem(`simreg_fisik_${patient.mcuNo}`);
      if (saved) return JSON.parse(saved);
    } catch (e) {}
    return DEFAULT_FISIK_MATA;
  });

  const [doctorName, setDoctorName] = useState<string>(
    examinerDoctor || 'dr. Anisa Rahmawati'
  );

  React.useEffect(() => {
    try {
      const saved = localStorage.getItem(`simreg_fisik_${patient.mcuNo}`);
      if (saved) {
        setFormData(JSON.parse(saved));
        return;
      }
    } catch (e) {}
    setFormData(DEFAULT_FISIK_MATA);
  }, [patient.mcuNo]);

  React.useEffect(() => {
    if (examinerDoctor) {
      setDoctorName(examinerDoctor);
    }
  }, [examinerDoctor]);

  // Ambil data Master Saran dari LocalStorage atau default data
  const getStoredAdvices = (): MedicalAdviceMaster[] => {
    try {
      const raw = localStorage.getItem('simreg_medical_advices');
      if (raw) {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed) && parsed.length > 0) return parsed;
      }
    } catch (e) {}
    return initialMedicalAdvices;
  };

  // Kalkulasi IMT / BMI otomatis sesuai Standar Asia Pasifik (WPRO)
  const bmiInfo = useMemo(() => {
    const tbMeter = formData.tinggiBadan / 100;
    if (tbMeter <= 0) return { value: '0.0', category: 'Tidak valid', color: 'text-slate-500', badgeBg: 'bg-slate-100 text-slate-700' };
    const bmiVal = formData.beratBadan / (tbMeter * tbMeter);
    const rounded = bmiVal.toFixed(1);

    if (bmiVal < 18.5) {
      return { value: rounded, category: 'Berat Badan Kurang (Underweight)', color: 'text-amber-600', badgeBg: 'bg-amber-100 text-amber-800' };
    } else if (bmiVal <= 22.9) {
      return { value: rounded, category: '🟢 Normal / Ideal', color: 'text-emerald-600', badgeBg: 'bg-emerald-100 text-emerald-800' };
    } else if (bmiVal <= 24.9) {
      return { value: rounded, category: '🟡 Kelebihan Berat Badan (Overweight)', color: 'text-yellow-700', badgeBg: 'bg-yellow-100 text-yellow-900' };
    } else if (bmiVal <= 29.9) {
      return { value: rounded, category: '🟠 Obesitas Tingkat I', color: 'text-orange-700', badgeBg: 'bg-orange-100 text-orange-900' };
    } else {
      return { value: rounded, category: '🔴 Obesitas Tingkat II', color: 'text-rose-600', badgeBg: 'bg-rose-100 text-rose-800' };
    }
  }, [formData.tinggiBadan, formData.beratBadan]);

  // Klasifikasi Tekanan Darah sesuai Standar JNC VII:
  // Normal: Sistolik < 120 mmHg dan Diastolik < 80 mmHg
  // Prehipertensi: 120 - 139 mmHg atau 80 - 89 mmHg
  // Hipertensi Derajat 1: 140 - 159 mmHg atau 90 - 99 mmHg
  // Hipertensi Derajat 2: >= 160 mmHg atau >= 100 mmHg
  const bpInfo = useMemo(() => {
    const s = formData.tensiSistole;
    const d = formData.tensiDiastole;
    if (s >= 160 || d >= 100) {
      return { label: 'Hipertensi Derajat 2 (≥160 atau ≥100 mmHg)', bg: 'bg-rose-200 text-rose-900 border-rose-300' };
    } else if (s >= 140 || d >= 90) {
      return { label: 'Hipertensi Derajat 1 (140-159 atau 90-99 mmHg)', bg: 'bg-rose-100 text-rose-800 border-rose-200' };
    } else if (s >= 120 || d >= 80) {
      return { label: 'Prehipertensi (120-139 atau 80-89 mmHg)', bg: 'bg-amber-100 text-amber-800 border-amber-200' };
    } else {
      return { label: 'Normal (<120 dan <80 mmHg)', bg: 'bg-emerald-100 text-emerald-800 border-emerald-200' };
    }
  }, [formData.tensiSistole, formData.tensiDiastole]);

  // Otomatisasi Kesimpulan & Saran Medis Merujuk pada Master Saran Medis
  const handleAutoGenerateFromMaster = (showToast: boolean = true) => {
    const advices = getStoredAdvices();
    const tbMeter = formData.tinggiBadan / 100;
    const bmiVal = tbMeter > 0 ? Number((formData.beratBadan / (tbMeter * tbMeter)).toFixed(1)) : 0;

    const findings: string[] = [];
    const adviceList: string[] = [];

    // 1. BMI Logic Standar Asia Pasifik:
    // < 18.5: Underweight
    // 18.5 - 22.9: Normal
    // 23.0 - 24.9: Overweight
    // 25.0 - 29.9: Obesitas Tk I
    // >= 30.0: Obesitas Tk II
    if (bmiVal > 0) {
      if (bmiVal >= 23.0 && bmiVal <= 24.9) {
        findings.push(`Kelebihan Berat Badan / Overweight (BMI ${bmiVal} kg/m² - BB ${formData.beratBadan} kg, TB ${formData.tinggiBadan} cm)`);
        const masterItem = advices.find(
          (a) => a.kode === 'SARAN-BMI-01' || a.judulMasalah.toLowerCase().includes('overweight')
        );
        if (masterItem) {
          adviceList.push(`• [Overweight]: ${masterItem.saranMedis}`);
        } else {
          adviceList.push(
            `• [Overweight]: Pola makan gizi seimbang dengan defisit kalori terukur (300-500 kkal/hari). Batasi karbohidrat sederhana, gorengan, dan minuman manis. Tingkatkan aktivitas fisik aerobik minimal 150 menit/minggu (jalan cepat, bersepeda, berenang). Kontrol berat badan berkala setiap bulan.`
          );
        }
      } else if (bmiVal >= 25.0 && bmiVal <= 29.9) {
        findings.push(`Obesitas Tingkat I (BMI ${bmiVal} kg/m² - BB ${formData.beratBadan} kg, TB ${formData.tinggiBadan} cm)`);
        const masterItem = advices.find(
          (a) => a.kode === 'SARAN-BMI-02' || a.judulMasalah.toLowerCase().includes('obesitas tingkat i')
        );
        if (masterItem) {
          adviceList.push(`• [Obesitas Tingkat I]: ${masterItem.saranMedis}`);
        } else {
          adviceList.push(`• [Obesitas Tingkat I]: Modifikasi gaya hidup sehat, batasi asupan lemak jenuh dan gula, serta rutin olahraga aerobik 150 menit/minggu.`);
        }
      } else if (bmiVal >= 30.0) {
        findings.push(`Obesitas Tingkat II (BMI ${bmiVal} kg/m² - BB ${formData.beratBadan} kg, TB ${formData.tinggiBadan} cm)`);
        const masterItem = advices.find(
          (a) => a.kode === 'SARAN-BMI-04' || a.judulMasalah.toLowerCase().includes('obesitas tingkat ii') || a.kode === 'SARAN-BMI-02'
        );
        if (masterItem) {
          adviceList.push(`• [Obesitas Tingkat II]: ${masterItem.saranMedis}`);
        } else {
          adviceList.push(`• [Obesitas Tingkat II]: Rujukan konsultasi dokter spesialis gizi klinis untuk penanganan komprehensif risiko kardiovaskular.`);
        }
      } else if (bmiVal < 18.5) {
        findings.push(`Berat Badan Kurang (Underweight) (BMI ${bmiVal} kg/m² - BB ${formData.beratBadan} kg, TB ${formData.tinggiBadan} cm)`);
        const masterItem = advices.find(
          (a) => a.kode === 'SARAN-BMI-03' || a.judulMasalah.toLowerCase().includes('underweight')
        );
        if (masterItem) adviceList.push(`• [Underweight]: ${masterItem.saranMedis}`);
      }
    }

    // 2. Tekanan Darah Standar JNC VII:
    // Normal: Sistolik < 120 dan Diastolik < 80 mmHg
    // Prehipertensi: 120 - 139 atau 80 - 89 mmHg
    // Hipertensi Derajat 1: 140 - 159 atau 90 - 99 mmHg
    // Hipertensi Derajat 2: >= 160 atau >= 100 mmHg
    if (formData.tensiSistole >= 160 || formData.tensiDiastole >= 100) {
      findings.push(`Hipertensi Derajat 2 (${formData.tensiSistole}/${formData.tensiDiastole} mmHg)`);
      const masterItem = advices.find((a) => a.kode === 'SARAN-HT-03' || a.judulMasalah.toLowerCase().includes('hipertensi derajat 2'));
      if (masterItem) {
        adviceList.push(`• [Hipertensi Derajat 2]: ${masterItem.saranMedis}`);
      } else {
        adviceList.push(`• [Hipertensi Derajat 2]: Rujukan dokter spesialis penyakit dalam untuk evaluasi pengobatan antihipertensi segera.`);
      }
    } else if (formData.tensiSistole >= 140 || formData.tensiDiastole >= 90) {
      findings.push(`Hipertensi Derajat 1 (${formData.tensiSistole}/${formData.tensiDiastole} mmHg)`);
      const masterItem = advices.find((a) => a.kode === 'SARAN-HT-02' || a.judulMasalah.toLowerCase().includes('hipertensi derajat 1'));
      if (masterItem) {
        adviceList.push(`• [Hipertensi Derajat 1]: ${masterItem.saranMedis}`);
      } else {
        adviceList.push(`• [Hipertensi Derajat 1]: Evaluasi tensi berkala, batasi konsumsi garam, dan konsultasi dokter faskes/Sp.PD.`);
      }
    } else if (formData.tensiSistole >= 120 || formData.tensiDiastole >= 80) {
      findings.push(`Prehipertensi (${formData.tensiSistole}/${formData.tensiDiastole} mmHg)`);
      const masterItem = advices.find((a) => a.kode === 'SARAN-HT-01' || a.judulMasalah.toLowerCase().includes('prehipertensi'));
      if (masterItem) {
        adviceList.push(`• [Prehipertensi]: ${masterItem.saranMedis}`);
      } else {
        adviceList.push(`• [Prehipertensi]: Kurangi konsumsi garam, hindari stres, istirahat cukup, dan kontrol tensi berkala tiap 1-3 bulan.`);
      }
    }

    // 3. Buta Warna & Visus
    if (formData.ishiharaButaWarna && formData.ishiharaButaWarna !== 'Normal') {
      findings.push(`Buta Warna: ${formData.ishiharaButaWarna}`);
      adviceList.push(`• [Buta Warna]: Penyesuaian tugas kerja yang tidak memerlukan pembacaan kode warna kritis.`);
    }
    if ((formData.visusOdTanpaKacamata !== '6/6' && formData.visusOdTanpaKacamata !== '-' && formData.visusOdTanpaKacamata !== '') ||
        (formData.visusOsTanpaKacamata !== '6/6' && formData.visusOsTanpaKacamata !== '-' && formData.visusOsTanpaKacamata !== '')) {
      findings.push(`Penurunan Visus OD: ${formData.visusOdTanpaKacamata}, OS: ${formData.visusOsTanpaKacamata}`);
      const masterItem = advices.find((a) => a.kode === 'SARAN-VISUS-01');
      if (masterItem && !adviceList.some(a => a.includes('[Visus]'))) {
        adviceList.push(`• [Visus / Mata]: ${masterItem.saranMedis}`);
      }
    }

    // 4. Konjungtiva & Sklera Mata
    if (formData.konjungtiva === 'Anemis') {
      findings.push('Konjungtiva Anemis (Suspek Anemia Klinis)');
      adviceList.push('• [Mata / Anemia]: Konsumsi makanan tinggi zat besi dan evaluasi kadar hemoglobin darah.');
    } else if (formData.konjungtiva === 'Hiperemis') {
      findings.push('Konjungtiva Hiperemis / Konjungtivitis');
      adviceList.push('• [Mata]: Konsultasi dokter spesialis mata atau faskes untuk evaluasi konjungtivitis/iritasi mata.');
    }

    if (formData.sklera && (formData.sklera.includes('Ikterik') || formData.sklera.includes('Ikterus')) && !formData.sklera.includes('Tidak') && !formData.sklera.includes('Anikterik')) {
      findings.push('Sklera Ikterik / Ikterus (Suspek Kelainan Hepatobilier)');
      adviceList.push('• [Mata / Hepatobilier]: Konsultasi dokter spesialis penyakit dalam untuk evaluasi hepar dan empedu.');
    }

    let newKesimpulan = '';
    let newSaran = '';

    if (findings.length === 0) {
      newKesimpulan = 'Pemeriksaan fisik umum, tanda vital, dan antropometri dalam batas normal (Fit to Work).';
      newSaran = 'Pertahankan pola hidup sehat, konsumsi gizi seimbang, lakukan olahraga rutin minimal 30 menit 3x seminggu, dan cukup istirahat.';
    } else {
      newKesimpulan = findings.join('; ') + '.';
      newSaran = adviceList.join('\n\n');
    }

    setFormData((prev) => ({
      ...prev,
      kesimpulan: newKesimpulan,
      saranDokter: newSaran,
    }));

    if (showToast) {
      onNotify('⚡ Otomatisasi aktif: Kesimpulan & Saran Medis berhasil disinkronkan merujuk pada Master Saran Medis!');
    }
  };

  // Preset Cepat
  const handleApplyPreset = (preset: 'normal' | 'prehipertensi' | 'butawarnaparsial') => {
    if (preset === 'normal') {
      setFormData(DEFAULT_FISIK_MATA);
      onNotify('Preset Pemeriksaan Fisik & Mata NORMAL berhasil diterapkan.');
    } else if (preset === 'prehipertensi') {
      setFormData((prev) => ({
        ...prev,
        tensiSistole: 135,
        tensiDiastole: 88,
        kesimpulan: 'Pemeriksaan fisik dalam batas wajar dengan kecenderungan Pre-Hipertensi (135/88 mmHg). Mata dalam batas normal.',
        saranDokter: '• [Pre-Hipertensi]: Diet rendah garam (kurangi natrium <2000 mg/hari), hindari makanan berpengawet, kendalikan stres, olahraga kardio teratur 30 menit/hari, dan kontrol tensi rutin mingguan.',
      }));
      onNotify('Preset Pre-Hipertensi diterapkan.');
    } else if (preset === 'butawarnaparsial') {
      setFormData((prev) => ({
        ...prev,
        ishiharaButaWarna: 'Buta Warna Parsial',
        kesimpulan: 'Pemeriksaan fisik umum baik. Terdapat temuan Buta Warna Parsial (Merah-Hijau) pada tes Ishihara.',
        saranDokter: '• [Buta Warna]: Perhatikan penempatan tugas kerja yang membutuhkan pembedaan kode warna kritis (kabel listrik / indikator LED).',
      }));
      onNotify('Preset Buta Warna Parsial diterapkan.');
    }
  };

  const handleSaveForm = (e: React.FormEvent) => {
    e.preventDefault();
    const finalData = {
      ...formData,
      bmi: bmiInfo.value,
      bmiCategory: bmiInfo.category,
      doctorName,
      updatedAt: new Date().toISOString(),
    };
    try {
      localStorage.setItem(`simreg_fisik_${patient.mcuNo}`, JSON.stringify(finalData));
      saveExamResultToCloud(patient.mcuNo, 'fisik', finalData).catch(console.error);
      // Otomatis sinkronkan dan perbarui Resume Medis & Diagnosa Klinis (Kesimpulan Temuan) serta Saran Dokter
      saveAutoGeneratedResume(patient.mcuNo);
    } catch (e) {}
    if (onSave) {
      onSave(finalData);
    }
    onNotify(
      `Hasil Pemeriksaan Fisik & Mata untuk [${patient.mcuNo} - ${patient.nama}] berhasil disimpan & Resume Medis otomatis diperbarui!`
    );
  };

  return (
    <form onSubmit={handleSaveForm} className="space-y-6">
      {/* Header Info Peserta & Penugasan Dokter */}
      <div className="bg-gradient-to-r from-teal-50 via-cyan-50 to-blue-50 border border-teal-200 rounded-2xl p-4 md:p-5 flex flex-wrap items-center justify-between gap-4 shadow-xs">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-teal-700 text-white flex items-center justify-center shadow-md shadow-teal-700/20">
            <Activity className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="px-2 py-0.5 rounded text-[11px] font-extrabold bg-teal-700 text-white font-mono">
                {patient.mcuNo}
              </span>
              <h3 className="text-[17px] font-extrabold text-slate-900">
                {patient.nama}
              </h3>
              <span className="text-[12px] text-slate-500">
                ({patient.jk}, {patient.tglLahir})
              </span>
            </div>
            <p className="text-[12px] text-slate-600 mt-0.5">
              PT: <b className="text-slate-800">{patient.pt}</b> &bull; Bagian:{' '}
              <b className="text-slate-800">{patient.dept || '-'}</b> &bull; Paket:{' '}
              <span className="text-teal-800 font-bold">{patient.paket}</span>
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <div className="text-right">
            <span className="text-[11px] text-teal-700 font-medium block">
              Dokter Pemeriksa Fisik:
            </span>
            <input
              type="text"
              value={doctorName}
              onChange={(e) => setDoctorName(e.target.value)}
              className="text-[13px] font-bold text-slate-900 bg-white border border-teal-300 rounded-lg px-2.5 py-1 text-right focus:ring-2 focus:ring-teal-500/20"
            />
          </div>
          <div className="flex gap-1.5">
            <button
              type="button"
              onClick={() => handleApplyPreset('normal')}
              className="px-2.5 py-1.5 bg-white hover:bg-teal-50 border border-teal-300 text-teal-800 text-[11px] font-bold rounded-lg flex items-center gap-1 shadow-2xs transition-colors"
              title="Set semua nilai fisik & mata ke kondisi Normal Ideal"
            >
              <Sparkles className="w-3.5 h-3.5 text-teal-600" />
              Preset Normal
            </button>
          </div>
        </div>
      </div>

      {/* SECTION 1: TANDA-TANDA VITAL & ANTROPOMETRI */}
      <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2">
            <HeartPulse className="w-5 h-5 text-rose-600" />
            <h4 className="text-[15px] font-extrabold text-slate-900">
              1. Tanda-Tanda Vital &amp; Antropometri (Status Fisik)
            </h4>
          </div>
          <span className={`text-[11px] font-bold px-2.5 py-0.5 rounded-full ${bpInfo.bg}`}>
            Status TD: {bpInfo.label}
          </span>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3.5">
          {/* TD Sistole */}
          <div>
            <label className="block text-[11px] font-bold text-slate-600 mb-1">
              TD Sistole (mmHg)
            </label>
            <input
              type="number"
              value={formData.tensiSistole}
              onChange={(e) => setFormData({ ...formData, tensiSistole: Number(e.target.value) })}
              className="w-full px-3 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[13px] font-bold text-slate-800 text-center"
            />
            <span className="text-[10px] text-slate-400 block text-center mt-0.5">Ref: 100 - 120</span>
          </div>

          {/* TD Diastole */}
          <div>
            <label className="block text-[11px] font-bold text-slate-600 mb-1">
              TD Diastole (mmHg)
            </label>
            <input
              type="number"
              value={formData.tensiDiastole}
              onChange={(e) => setFormData({ ...formData, tensiDiastole: Number(e.target.value) })}
              className="w-full px-3 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[13px] font-bold text-slate-800 text-center"
            />
            <span className="text-[10px] text-slate-400 block text-center mt-0.5">Ref: 70 - 80</span>
          </div>

          {/* Nadi */}
          <div>
            <label className="block text-[11px] font-bold text-slate-600 mb-1">
              Denyut Nadi (x/mnt)
            </label>
            <input
              type="number"
              value={formData.nadi}
              onChange={(e) => setFormData({ ...formData, nadi: Number(e.target.value) })}
              className="w-full px-3 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[13px] font-bold text-slate-800 text-center"
            />
            <span className="text-[10px] text-slate-400 block text-center mt-0.5">Ref: 60 - 100</span>
          </div>

          {/* Pernapasan */}
          <div>
            <label className="block text-[11px] font-bold text-slate-600 mb-1">
              Pernapasan (x/mnt)
            </label>
            <input
              type="number"
              value={formData.pernapasan}
              onChange={(e) => setFormData({ ...formData, pernapasan: Number(e.target.value) })}
              className="w-full px-3 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[13px] font-bold text-slate-800 text-center"
            />
            <span className="text-[10px] text-slate-400 block text-center mt-0.5">Ref: 12 - 20</span>
          </div>

          {/* Suhu */}
          <div>
            <label className="block text-[11px] font-bold text-slate-600 mb-1">
              Suhu Tubuh (°C)
            </label>
            <input
              type="number"
              step="0.1"
              value={formData.suhu}
              onChange={(e) => setFormData({ ...formData, suhu: Number(e.target.value) })}
              className="w-full px-3 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[13px] font-bold text-slate-800 text-center"
            />
            <span className="text-[10px] text-slate-400 block text-center mt-0.5">Ref: 36.0 - 37.5</span>
          </div>

          {/* SpO2 */}
          <div>
            <label className="block text-[11px] font-bold text-slate-600 mb-1">
              Saturasi O2 (%)
            </label>
            <input
              type="number"
              value={formData.spo2}
              onChange={(e) => setFormData({ ...formData, spo2: Number(e.target.value) })}
              className="w-full px-3 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[13px] font-bold text-slate-800 text-center"
            />
            <span className="text-[10px] text-slate-400 block text-center mt-0.5">Ref: 95 - 100%</span>
          </div>
        </div>

        {/* Antropometri Bar */}
        <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-xl grid grid-cols-1 sm:grid-cols-4 gap-3 items-center">
          <div>
            <label className="block text-[11px] font-bold text-slate-600 mb-1">
              Tinggi Badan (cm)
            </label>
            <input
              type="number"
              value={formData.tinggiBadan}
              onChange={(e) => setFormData({ ...formData, tinggiBadan: Number(e.target.value) })}
              className="w-full px-3 py-1.5 bg-white border border-slate-300 rounded-lg text-[13px] font-bold text-slate-800 text-center"
            />
          </div>

          <div>
            <label className="block text-[11px] font-bold text-slate-600 mb-1">
              Berat Badan (kg)
            </label>
            <input
              type="number"
              value={formData.beratBadan}
              onChange={(e) => setFormData({ ...formData, beratBadan: Number(e.target.value) })}
              className="w-full px-3 py-1.5 bg-white border border-slate-300 rounded-lg text-[13px] font-bold text-slate-800 text-center"
            />
          </div>

          <div>
            <label className="block text-[11px] font-bold text-slate-600 mb-1">
              Lingkar Perut (cm)
            </label>
            <input
              type="number"
              value={formData.lingkarPerut}
              onChange={(e) => setFormData({ ...formData, lingkarPerut: Number(e.target.value) })}
              className="w-full px-3 py-1.5 bg-white border border-slate-300 rounded-lg text-[13px] font-bold text-slate-800 text-center"
            />
            <span className="text-[10px] text-slate-400 block text-center mt-0.5">Pria &lt;90, Wnt &lt;80</span>
          </div>

          <div className="bg-white p-2.5 rounded-lg border border-slate-200 text-center">
            <span className="text-[10.5px] font-semibold text-slate-500 block">
              Indeks Massa Tubuh (IMT / BMI)
            </span>
            <div className="flex items-center justify-center gap-1.5 mt-0.5">
              <span className="text-[18px] font-black text-slate-900 font-mono">
                {bmiInfo.value}
              </span>
              <span className="text-[11px] text-slate-500 font-medium">kg/m²</span>
            </div>
            <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full inline-block mt-0.5 ${bmiInfo.badgeBg}`}>
              {bmiInfo.category}
            </span>
          </div>
        </div>
      </div>

      {/* SECTION 2: PEMERIKSAAN MATA & PENGLIHATAN (TERINTEGRASI DENGAN PEMERIKSAAN FISIK) */}
      <div className="bg-white border-2 border-cyan-200 rounded-2xl p-5 shadow-xs space-y-4">
        <div className="flex flex-wrap items-center justify-between border-b border-cyan-100 pb-3 gap-2">
          <div className="flex items-center gap-2">
            <Eye className="w-5 h-5 text-cyan-700" />
            <div>
              <h4 className="text-[15px] font-extrabold text-slate-900">
                2. Pemeriksaan Mata, Visus &amp; Buta Warna (Tergabung dalam Pemeriksaan Fisik)
              </h4>
              <p className="text-[11.5px] text-slate-500">
                Pemeriksaan tajam penglihatan (visus jauh &amp; dekat), uji buta warna Ishihara, dan inspeksi segmen anterior bola mata.
              </p>
            </div>
          </div>
          <span className="text-[11px] font-extrabold px-3 py-1 rounded-full bg-cyan-100 text-cyan-800 border border-cyan-300">
            Terintegrasi dengan Pemeriksaan Fisik
          </span>
        </div>

        {/* Visus & Ishihara Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 bg-cyan-50/40 p-4 rounded-xl border border-cyan-100">
          {/* Visus OD Tanpa Kacamata */}
          <div>
            <label className="block text-[11px] font-bold text-slate-700 mb-1">
              Visus OD (Mata Kanan) Tanpa Kacamata
            </label>
            <input
              type="text"
              value={formData.visusOdTanpaKacamata}
              onChange={(e) => setFormData({ ...formData, visusOdTanpaKacamata: e.target.value })}
              className="w-full px-3 py-1.5 bg-white border border-slate-300 rounded-lg text-[13px] font-bold text-center text-slate-800"
              placeholder="Contoh: 6/6 atau 20/20"
            />
            <span className="text-[10.5px] text-slate-400 block text-center mt-0.5">Nilai Rujukan: 6/6</span>
          </div>

          {/* Visus OS Tanpa Kacamata */}
          <div>
            <label className="block text-[11px] font-bold text-slate-700 mb-1">
              Visus OS (Mata Kiri) Tanpa Kacamata
            </label>
            <input
              type="text"
              value={formData.visusOsTanpaKacamata}
              onChange={(e) => setFormData({ ...formData, visusOsTanpaKacamata: e.target.value })}
              className="w-full px-3 py-1.5 bg-white border border-slate-300 rounded-lg text-[13px] font-bold text-center text-slate-800"
              placeholder="Contoh: 6/6 atau 20/20"
            />
            <span className="text-[10.5px] text-slate-400 block text-center mt-0.5">Nilai Rujukan: 6/6</span>
          </div>

          {/* Visus Koreksi Kacamata */}
          <div>
            <label className="block text-[11px] font-bold text-slate-700 mb-1">
              Koreksi Kacamata (OD / OS)
            </label>
            <div className="grid grid-cols-2 gap-1.5">
              <input
                type="text"
                value={formData.visusOdKacamata}
                onChange={(e) => setFormData({ ...formData, visusOdKacamata: e.target.value })}
                className="w-full px-2 py-1.5 bg-white border border-slate-300 rounded-lg text-[12px] font-semibold text-center"
                placeholder="OD: -"
              />
              <input
                type="text"
                value={formData.visusOsKacamata}
                onChange={(e) => setFormData({ ...formData, visusOsKacamata: e.target.value })}
                className="w-full px-2 py-1.5 bg-white border border-slate-300 rounded-lg text-[12px] font-semibold text-center"
                placeholder="OS: -"
              />
            </div>
            <span className="text-[10.5px] text-slate-400 block text-center mt-0.5">Isi jika memakai kacamata</span>
          </div>

          {/* Uji Buta Warna Ishihara */}
          <div>
            <label className="block text-[11px] font-bold text-slate-700 mb-1">
              Tes Buta Warna (Ishihara Plate)
            </label>
            <select
              value={formData.ishiharaButaWarna}
              onChange={(e) => setFormData({ ...formData, ishiharaButaWarna: e.target.value as any })}
              className={`w-full px-3 py-1.5 bg-white border rounded-lg text-[12.5px] font-bold ${
                formData.ishiharaButaWarna === 'Normal'
                  ? 'border-emerald-300 text-emerald-800'
                  : 'border-rose-400 text-rose-800 bg-rose-50'
              }`}
            >
              <option value="Normal">Normal (Bisa Baca Semua Piringan)</option>
              <option value="Buta Warna Parsial">Buta Warna Parsial (Merah-Hijau)</option>
              <option value="Buta Warna Total">Buta Warna Total (Monokromasi)</option>
            </select>
            <span className="text-[10.5px] text-slate-400 block text-center mt-0.5">Standar K3 Industri</span>
          </div>
        </div>

        {/* Inspeksi Segmen Anterior Mata */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
          <div>
            <label className="block text-[11px] font-semibold text-slate-600 mb-1">
              Konjungtiva
            </label>
            <select
              value={formData.konjungtiva}
              onChange={(e) => setFormData({ ...formData, konjungtiva: e.target.value as any })}
              className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[12px]"
            >
              <option value="Normal (Tidak Anemis)">Normal (Tidak Anemis)</option>
              <option value="Anemis">Anemis (Pucat)</option>
              <option value="Hiperemis">Hiperemis (Merah / Konjungtivitis)</option>
            </select>
          </div>

          <div>
            <label className="block text-[11px] font-semibold text-slate-600 mb-1">
              Sklera
            </label>
            <select
              value={formData.sklera}
              onChange={(e) => setFormData({ ...formData, sklera: e.target.value as any })}
              className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[12px]"
            >
              <option value="Normal (Tidak Ikterik)">Normal (Tidak Ikterik / Tidak Ikterus)</option>
              <option value="Anikterik (Normal)">Anikterik (Normal)</option>
              <option value="Ikterik">Ikterik / Ikterus (Kuning)</option>
            </select>
          </div>

          <div>
            <label className="block text-[11px] font-semibold text-slate-600 mb-1">
              Lensa Mata
            </label>
            <select
              value={formData.lensa}
              onChange={(e) => setFormData({ ...formData, lensa: e.target.value as any })}
              className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[12px]"
            >
              <option value="Jernih">Jernih (Normal)</option>
              <option value="Katarak Imatur">Kekeruhan Lensa / Katarak Imatur</option>
              <option value="Katarak Matur">Katarak Matur</option>
            </select>
          </div>

          <div>
            <label className="block text-[11px] font-semibold text-slate-600 mb-1">
              Lapang Pandang &amp; Gerak Bola Mata
            </label>
            <select
              value={formData.gerakBolaMata}
              onChange={(e) => setFormData({ ...formData, gerakBolaMata: e.target.value as any })}
              className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[12px]"
            >
              <option value="Bebas ke Segala Arah">Bebas ke Segala Arah (Normal)</option>
              <option value="Terbatas">Terbatas / Paresis Otot Okular</option>
            </select>
          </div>
        </div>
      </div>

      {/* SECTION 3: STATUS GENERALIS KLINIS SISTEM ORGAN */}
      <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs space-y-4">
        <div className="flex items-center gap-2 border-b border-slate-100 pb-3">
          <Stethoscope className="w-5 h-5 text-teal-700" />
          <h4 className="text-[15px] font-extrabold text-slate-900">
            3. Status Generalis Klinis (Pemeriksaan Organ &amp; Fisik Lengkap)
          </h4>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-[12.5px]">
          {/* Kepala & Leher */}
          <div>
            <label className="block font-bold text-slate-700 mb-1">
              Kepala, Leher, KGB &amp; Tiroid:
            </label>
            <textarea
              rows={2}
              value={formData.kepalaLeher}
              onChange={(e) => setFormData({ ...formData, kepalaLeher: e.target.value })}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[12.5px] focus:ring-2 focus:ring-teal-500/20"
            />
          </div>

          {/* THT */}
          <div>
            <label className="block font-bold text-slate-700 mb-1">
              Telinga, Hidung &amp; Tenggorokan (THT):
            </label>
            <textarea
              rows={2}
              value={formData.tht}
              onChange={(e) => setFormData({ ...formData, tht: e.target.value })}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[12.5px] focus:ring-2 focus:ring-teal-500/20"
            />
          </div>

          {/* Gigi & Mulut */}
          <div>
            <label className="block font-bold text-slate-700 mb-1">
              Gigi &amp; Mulut:
            </label>
            <textarea
              rows={2}
              value={formData.gigiMulut}
              onChange={(e) => setFormData({ ...formData, gigiMulut: e.target.value })}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[12.5px] focus:ring-2 focus:ring-teal-500/20"
            />
          </div>

          {/* Jantung */}
          <div>
            <label className="block font-bold text-slate-700 mb-1">
              Thorax - Jantung (Cor):
            </label>
            <textarea
              rows={2}
              value={formData.jantung}
              onChange={(e) => setFormData({ ...formData, jantung: e.target.value })}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[12.5px] focus:ring-2 focus:ring-teal-500/20"
            />
          </div>

          {/* Paru */}
          <div>
            <label className="block font-bold text-slate-700 mb-1">
              Thorax - Paru-Paru (Pulmo):
            </label>
            <textarea
              rows={2}
              value={formData.paru}
              onChange={(e) => setFormData({ ...formData, paru: e.target.value })}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[12.5px] focus:ring-2 focus:ring-teal-500/20"
            />
          </div>

          {/* Abdomen */}
          <div>
            <label className="block font-bold text-slate-700 mb-1">
              Abdomen &amp; Saluran Cerna:
            </label>
            <textarea
              rows={2}
              value={formData.abdomen}
              onChange={(e) => setFormData({ ...formData, abdomen: e.target.value })}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[12.5px] focus:ring-2 focus:ring-teal-500/20"
            />
          </div>

          {/* Ekstremitas */}
          <div>
            <label className="block font-bold text-slate-700 mb-1">
              Ekstremitas &amp; Neurologis:
            </label>
            <textarea
              rows={2}
              value={formData.ekstremitas}
              onChange={(e) => setFormData({ ...formData, ekstremitas: e.target.value })}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[12.5px] focus:ring-2 focus:ring-teal-500/20"
            />
          </div>

          {/* Kulit */}
          <div>
            <label className="block font-bold text-slate-700 mb-1">
              Kulit &amp; Integumen:
            </label>
            <textarea
              rows={2}
              value={formData.kulit}
              onChange={(e) => setFormData({ ...formData, kulit: e.target.value })}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[12.5px] focus:ring-2 focus:ring-teal-500/20"
            />
          </div>
        </div>
      </div>

      {/* Tombol Simpan */}
      <div className="flex items-center justify-between pt-2">
        <button
          type="button"
          onClick={() => setFormData(DEFAULT_FISIK_MATA)}
          className="px-4 py-2.5 rounded-xl border border-slate-300 bg-white hover:bg-slate-50 text-slate-700 text-[13px] font-bold flex items-center gap-1.5 transition-colors shadow-xs"
        >
          <RotateCcw className="w-4 h-4 text-slate-500" />
          Reset Nilai Standar
        </button>

        <button
          type="submit"
          className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-teal-700 to-cyan-700 hover:from-teal-800 hover:to-cyan-800 text-white text-[13px] font-bold flex items-center gap-2 shadow-md shadow-teal-700/20 transition-all hover:scale-[1.01]"
        >
          <Save className="w-4 h-4" />
          Simpan Hasil Pemeriksaan Fisik &amp; Mata
        </button>
      </div>
    </form>
  );
};
