import React, { useState, useMemo } from 'react';
import {
  FileText,
  Copy,
  Check,
  RotateCcw,
  Sparkles,
  CheckCircle2,
  AlertTriangle,
  Activity,
  Info,
  Layers,
  FileImage,
} from 'lucide-react';
import { AttendanceRecord } from '../types';
import { ChestXrayViewer, XrayPresetType } from './ChestXrayViewer';
import { saveAutoGeneratedResume } from '../utils/medicalResumeGenerator';

interface RontgenFormProps {
  patient: AttendanceRecord;
  examinerDoctor?: string;
  onSave?: (data: any) => void;
  onNotify: (message: string) => void;
}

export interface RontgenData {
  corDesc: string;
  corStatus: 'Normal' | 'Kardiomegali';
  pulmoDesc: string;
  pulmoStatus: 'Normal' | 'Infiltrat' | 'Lainnya';
  diafragmaDesc: string;
  diafragmaStatus: 'Normal' | 'Sinus Tumpul' | 'Efusi Pleura';
  skeletalDesc: string;
  skeletalStatus: 'Normal' | 'Fraktur' | 'Kelainan Struktur';
  kesanCustom?: string;
  saranCustom?: string;
  // Fitur Foto Rontgen Thorax
  photoUrl?: string | null;
  photoName?: string;
  projection?: string;
}

// Nilai DEFAULT NORMAL baku SIMREG
export const DEFAULT_NORMAL_RONTGEN: RontgenData = {
  corDesc: 'Ukuran dan bentuk normal, CTR < 50%',
  corStatus: 'Normal',
  pulmoDesc: 'Corakan bronkovaskular normal, tidak tampak infiltrat/kondensasi',
  pulmoStatus: 'Normal',
  diafragmaDesc: 'Diafragma licin, sinus kostofrenikus kanan-kiri tajam',
  diafragmaStatus: 'Normal',
  skeletalDesc: 'Tulang-tulang dan soft tissue intak/normal',
  skeletalStatus: 'Normal',
  kesanCustom: '',
  saranCustom: '',
  photoUrl: 'preset:normal',
  photoName: 'Thorax_PA_Normal_Simulasi.dcm',
  projection: 'PA Erektil (Thorax)',
};

export const RontgenForm: React.FC<RontgenFormProps> = ({
  patient,
  examinerDoctor,
  onSave,
  onNotify,
}) => {
  const [data, setData] = useState<RontgenData>(DEFAULT_NORMAL_RONTGEN);
  const [doctorName, setDoctorName] = useState<string>(
    examinerDoctor || 'dr. Farida Hanum, Sp.Rad'
  );
  const [quickInputText, setQuickInputText] = useState<string>('NORMAL');
  const [copied, setCopied] = useState<boolean>(false);

  React.useEffect(() => {
    if (examinerDoctor) {
      setDoctorName(examinerDoctor);
    }
  }, [examinerDoctor]);

  React.useEffect(() => {
    if (!patient?.mcuNo) return;
    try {
      const saved = localStorage.getItem(`simreg_rontgen_${patient.mcuNo}`);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed.data) {
          setData(parsed.data);
        }
      }
    } catch (e) {}
  }, [patient?.mcuNo]);

  // Status Evaluasi Keseluruhan
  const isOverallNormal = useMemo(() => {
    return (
      data.corStatus === 'Normal' &&
      data.pulmoStatus === 'Normal' &&
      data.diafragmaStatus === 'Normal' &&
      data.skeletalStatus === 'Normal'
    );
  }, [data.corStatus, data.pulmoStatus, data.diafragmaStatus, data.skeletalStatus]);

  // Interpretasi Strings untuk Tabel
  const corStatusStr = useMemo(() => {
    return `${data.corStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      data.corStatus === 'Kardiomegali' ? '[X]' : '[ ]'
    } Kardiomegali (Pembesaran)`;
  }, [data.corStatus]);

  const pulmoStatusStr = useMemo(() => {
    return `${data.pulmoStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      data.pulmoStatus === 'Infiltrat' ? '[X]' : '[ ]'
    } Ada Infiltrat / ${data.pulmoStatus === 'Lainnya' ? '[X]' : '[ ]'} Lainnya`;
  }, [data.pulmoStatus]);

  const diafragmaStatusStr = useMemo(() => {
    return `${data.diafragmaStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      data.diafragmaStatus === 'Sinus Tumpul' ? '[X]' : '[ ]'
    } Sinus Tumpul / ${data.diafragmaStatus === 'Efusi Pleura' ? '[X]' : '[ ]'} Efusi Pleura`;
  }, [data.diafragmaStatus]);

  const skeletalStatusStr = useMemo(() => {
    return `${data.skeletalStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      data.skeletalStatus === 'Fraktur' ? '[X]' : '[ ]'
    } Fraktur / ${data.skeletalStatus === 'Kelainan Struktur' ? '[X]' : '[ ]'} Kelainan Struktur`;
  }, [data.skeletalStatus]);

  // Kesimpulan Akhir String
  const kesimpulanAkhirStr = useMemo(() => {
    return isOverallNormal
      ? '[X] RONTGEN THORAX NORMAL (Cor & Pulmo dalam batas normal) <br> [ ] RONTGEN THORAX ABNORMAL (Ditemukan Kelainan Radiologis)'
      : '[ ] RONTGEN THORAX NORMAL (Cor & Pulmo dalam batas normal) <br> [X] RONTGEN THORAX ABNORMAL (Ditemukan Kelainan Radiologis)';
  }, [isOverallNormal]);

  // Kesan Radiologis Otomatis SIMREG
  const autoKesan = useMemo(() => {
    if (data.kesanCustom && data.kesanCustom.trim() !== '') {
      return data.kesanCustom;
    }
    if (isOverallNormal) {
      return 'Cor dan Pulmo dalam batas normal.';
    }

    const findings: string[] = [];
    if (data.corStatus === 'Kardiomegali') {
      findings.push('Kardiomegali (Pembesaran Jantung)');
    }
    if (data.pulmoStatus === 'Infiltrat') {
      findings.push('Infiltrat pada lapang paru (Suspek Proses Spesifik / Bronkopneumonia)');
    } else if (data.pulmoStatus === 'Lainnya') {
      findings.push('Kelainan parenkim paru');
    }
    if (data.diafragmaStatus === 'Sinus Tumpul') {
      findings.push('Sinus kostofrenikus tumpul (Suspek Penebalan Pleura)');
    } else if (data.diafragmaStatus === 'Efusi Pleura') {
      findings.push('Efusi Pleura');
    }
    if (data.skeletalStatus === 'Fraktur') {
      findings.push('Fraktur pada sistem tulang thoraks');
    } else if (data.skeletalStatus === 'Kelainan Struktur') {
      findings.push('Kelainan struktur skeletal (Skoliosis / Deformitas)');
    }

    return findings.join('; ') + '.';
  }, [
    data.kesanCustom,
    isOverallNormal,
    data.corStatus,
    data.pulmoStatus,
    data.diafragmaStatus,
    data.skeletalStatus,
  ]);

  // Saran & Tindak Lanjut Otomatis SIMREG
  const autoSaran = useMemo(() => {
    if (data.saranCustom && data.saranCustom.trim() !== '') {
      return data.saranCustom;
    }
    if (isOverallNormal) {
      return 'Hasil dalam batas normal, evaluasi klinis berkala jika ada keluhan.';
    }
    if (data.pulmoStatus === 'Infiltrat') {
      return 'Konsultasi lebih lanjut dengan Dokter Spesialis Paru (Sp.P), pemeriksaan dahak (TCM/BTA), serta foto rontgen thorax evaluasi berkala.';
    }
    if (data.corStatus === 'Kardiomegali') {
      return 'Konsultasi dengan Dokter Spesialis Jantung & Pembuluh Darah (Sp.JP) atau Spesialis Penyakit Dalam (Sp.PD), kontrol tekanan darah, dan lakukan pemeriksaan Echocardiografi.';
    }
    return 'Konsultasikan temuan radiologis dengan dokter spesialis terkait untuk penatalaksanaan klinis lebih lanjut.';
  }, [data.saranCustom, isOverallNormal, data.pulmoStatus, data.corStatus]);

  // Handler Proses Quick Input Text (e.g. "NORMAL" or custom text)
  const handleApplyQuickInput = (textToProcess?: string) => {
    const raw = (textToProcess ?? quickInputText).trim();
    if (!raw || raw.toUpperCase() === 'NORMAL') {
      setData(DEFAULT_NORMAL_RONTGEN);
      onNotify('SIMREG: Parameter Rontgen diisi otomatis dengan nilai DEFAULT NORMAL baku!');
      return;
    }

    const next = { ...data };
    const lower = raw.toLowerCase();

    // Cek kata kunci kelainan
    if (lower.includes('kardiomegali') || lower.includes('ctr >') || lower.includes('pembesaran jantung')) {
      next.corStatus = 'Kardiomegali';
      next.corDesc = 'Kardiomegali, CTR > 50%, apeks jantung bergeser ke laterokaudal';
    }
    if (lower.includes('infiltrat') || lower.includes('kondensasi') || lower.includes('kp') || lower.includes('tb')) {
      next.pulmoStatus = 'Infiltrat';
      next.pulmoDesc = 'Tampak bercak infiltrat/perselubungan pada lapang paru';
    }
    if (lower.includes('tumpul')) {
      next.diafragmaStatus = 'Sinus Tumpul';
      next.diafragmaDesc = 'Sinus kostofrenikus tampak tumpul';
    } else if (lower.includes('efusi')) {
      next.diafragmaStatus = 'Efusi Pleura';
      next.diafragmaDesc = 'Tampak perselubungan homogen menutupi sinus (meniscus sign, curiga efusi pleura)';
    }
    if (lower.includes('fraktur') || lower.includes('patah')) {
      next.skeletalStatus = 'Fraktur';
      next.skeletalDesc = 'Tampak diskontinuitas tulang / suspek fraktur kosta';
    } else if (lower.includes('skoliosis') || lower.includes('deformitas')) {
      next.skeletalStatus = 'Kelainan Struktur';
      next.skeletalDesc = 'Tampak deviasi / kurvatura skoliosis thorakalis';
    }

    setData(next);
    onNotify('SIMREG: Temuan rontgen thorax kustom berhasil diterapkan!');
  };

  // Sinkronisasi Temuan dari Preset Foto Rontgen
  const handleApplyPresetFindings = (preset: XrayPresetType) => {
    if (preset === 'normal') {
      setData({
        ...DEFAULT_NORMAL_RONTGEN,
        photoUrl: 'preset:normal',
        photoName: 'Thorax_PA_Normal_Simulasi.dcm',
      });
      onNotify('SIMREG: Preset Foto Normal & temuan klinis baku dimuat!');
    } else if (preset === 'infiltrat') {
      setData((prev) => ({
        ...prev,
        photoUrl: 'preset:infiltrat',
        photoName: 'Thorax_PA_Infiltrat_Apeks.dcm',
        pulmoDesc: 'Tampak bercak berawan infiltrat pada apeks pulmo kanan (suspek KP aktif)',
        pulmoStatus: 'Infiltrat',
        kesanCustom: 'Infiltrat pada lapang atas pulmo kanan (Suspek KP Duplex)',
        saranCustom: 'Konsultasi Spesialis Paru (Sp.P), pemeriksaan dahak TCM/BTA.',
      }));
      onNotify('SIMREG: Preset Foto Infiltrat & temuan klinis diperbarui!');
    } else if (preset === 'kardiomegali') {
      setData((prev) => ({
        ...prev,
        photoUrl: 'preset:kardiomegali',
        photoName: 'Thorax_PA_Kardiomegali_CTR56.dcm',
        corDesc: 'Kardiomegali, CTR 56%, apeks jantung membesar ke laterokaudal',
        corStatus: 'Kardiomegali',
        kesanCustom: 'Kardiomegali (CTR 56%), Pulmo dalam batas normal.',
        saranCustom: 'Konsultasi Spesialis Jantung (Sp.JP), evaluasi hipertensi.',
      }));
      onNotify('SIMREG: Preset Foto Kardiomegali (CTR 56%) & temuan klinis diperbarui!');
    } else if (preset === 'efusi') {
      setData((prev) => ({
        ...prev,
        photoUrl: 'preset:efusi',
        photoName: 'Thorax_PA_Efusi_Pleura_Dextra.dcm',
        diafragmaDesc: 'Sinus kostofrenikus kanan tampak tumpul dengan gambaran meniscus sign (efusi pleura minimal)',
        diafragmaStatus: 'Sinus Tumpul',
        kesanCustom: 'Sinus kostofrenikus kanan tumpul (Suspek Penebalan Pleura / Efusi Minimal).',
        saranCustom: 'Pemeriksaan lanjutan foto rontgen thoraks lateral / USG thorax.',
      }));
      onNotify('SIMREG: Preset Foto Efusi Pleura / Sinus Tumpul diperbarui!');
    }
  };

  // Generate exact Markdown matching SIMREG specification
  const generateMarkdownOutput = (): string => {
    return `### [SIMREG] Modul Hasil Pemeriksaan Rontgen Thorax

| Organ / Parameter | Hasil Pengamatan / Eksplorasi | Status Sistem |
| :--- | :--- | :--- |
| **Foto Radiograf** | ${data.photoName || 'Thorax PA Pasien'} (${data.projection || 'PA Erektil'}) | [X] Terlampir & Terverifikasi |
| **Cor (Jantung)** | ${data.corDesc} | ${corStatusStr} |
| **Pulmo (Paru)** | ${data.pulmoDesc} | ${pulmoStatusStr} |
| **Diafragma & Sinus** | ${data.diafragmaDesc} | ${diafragmaStatusStr} |
| **Sistem Skeletal** | ${data.skeletalDesc} | ${skeletalStatusStr} |

### 📋 KESIMPULAN DIAGNOSIS FINAL (SIMREG-AUTOMATION)

| Kesimpulan Akhir: | ${kesimpulanAkhirStr} |
| :--- | :--- |
| **Dokter Radiologi:** | ${doctorName} |
| **Kesan Radiologis:** | ${autoKesan} |
| **Saran & Tindak Lanjut:** | ${autoSaran} |
`;
  };

  const handleCopyMarkdown = async () => {
    try {
      await navigator.clipboard.writeText(generateMarkdownOutput());
      setCopied(true);
      onNotify('Laporan Rontgen Thorax format SIMREG berhasil disalin ke clipboard!');
      setTimeout(() => setCopied(false), 2500);
    } catch {
      onNotify('Gagal menyalin otomatis ke clipboard.');
    }
  };

  const handleSaveToRecord = () => {
    const payload = {
      data,
      isOverallNormal,
      kesan: autoKesan,
      saran: autoSaran,
      markdown: generateMarkdownOutput(),
    };
    try {
      localStorage.setItem(`simreg_rontgen_${patient.mcuNo}`, JSON.stringify(payload));
      saveAutoGeneratedResume(patient.mcuNo);
    } catch (e) {}

    onSave?.(payload);
    onNotify(
      `SIMREG: Hasil Rontgen Thorax (${isOverallNormal ? 'Normal' : 'Abnormal'}) untuk ${patient.nama} (#${patient.mcuNo}) berhasil disimpan ke Rekam Medis!`
    );
  };

  return (
    <div className="space-y-6">
      {/* 1. ANTARMUKA AWAL SIMREG (Menunggu Input) */}
      <div className="p-4 sm:p-5 rounded-2xl bg-gradient-to-r from-blue-50 via-indigo-50 to-sky-50 border border-blue-200 shadow-xs">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-xl bg-blue-600 text-white flex items-center justify-center shrink-0 shadow-md">
            <Layers className="w-5 h-5" />
          </div>
          <div className="space-y-2 flex-1">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <h4 className="font-extrabold text-[15px] text-blue-950 flex items-center gap-2">
                [SIMREG] Modul Hasil Pemeriksaan Radiologi (Rontgen Thorax PA)
              </h4>
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-1 rounded-lg text-[11.5px] font-bold bg-white text-blue-900 border border-blue-200 shadow-2xs flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                  Dokter Radiologi: <b>{doctorName}</b>
                </span>
                <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-blue-100 text-blue-800 border border-blue-300 font-mono">
                  SIMREG-AUTOMATION v2.5
                </span>
              </div>
            </div>
            <p className="text-[13px] text-slate-700 leading-relaxed">
              Halo Operator SIMREG! Silakan masukkan data bacaan rontgen thorax pasien di bawah ini (Cor, Pulmo, Diafragma &amp; Sinus, Skeletal), atau cukup ketik{' '}
              <b className="font-mono text-blue-800 bg-blue-100/90 px-1.5 py-0.5 rounded">
                "NORMAL"
              </b>{' '}
              untuk otomatis mengisi seluruh parameter dengan temuan normal baku (Cor dan Pulmo dalam batas normal).
            </p>

            {/* Quick Action Bar */}
            <div className="flex flex-wrap items-center gap-2 pt-2">
              <input
                type="text"
                value={quickInputText}
                onChange={(e) => setQuickInputText(e.target.value)}
                placeholder='Ketik "NORMAL" atau contoh "ada infiltrat", "kardiomegali"'
                className="px-3 py-1.5 bg-white border border-blue-300 rounded-xl text-xs font-mono font-bold text-slate-800 w-64 focus:ring-2 focus:ring-blue-500 shadow-2xs"
              />
              <button
                type="button"
                onClick={() => handleApplyQuickInput()}
                className="px-3.5 py-1.5 rounded-xl bg-blue-700 hover:bg-blue-800 text-white font-bold text-xs flex items-center gap-1.5 shadow-xs cursor-pointer"
              >
                <Activity className="w-3.5 h-3.5" />
                Proses Data SIMREG
              </button>
              <button
                type="button"
                onClick={() => {
                  setQuickInputText('NORMAL');
                  handleApplyQuickInput('NORMAL');
                }}
                className="px-3.5 py-1.5 rounded-xl bg-white hover:bg-blue-100 text-blue-800 border border-blue-300 font-bold text-xs flex items-center gap-1 cursor-pointer"
              >
                <Sparkles className="w-3.5 h-3.5 text-blue-600" />
                Isi Default NORMAL
              </button>
            </div>
          </div>
        </div>

        {/* Contoh Preset Klinis SIMREG */}
        <div className="mt-4 pt-3 border-t border-blue-200/60 flex flex-wrap items-center gap-2">
          <span className="text-xs font-bold text-blue-900 flex items-center gap-1">
            <Sparkles className="w-3.5 h-3.5 text-blue-600" />
            Simulasi Temuan Klinis:
          </span>
          <button
            type="button"
            onClick={() => {
              setData({
                corDesc: 'Ukuran dan bentuk normal, CTR < 50%',
                corStatus: 'Normal',
                pulmoDesc: 'Tampak bercak berawan infiltrat pada apeks pulmo kanan (suspek KP aktif)',
                pulmoStatus: 'Infiltrat',
                diafragmaDesc: 'Diafragma licin, sinus kostofrenikus tajam',
                diafragmaStatus: 'Normal',
                skeletalDesc: 'Tulang-tulang dan soft tissue intak',
                skeletalStatus: 'Normal',
                kesanCustom: 'Infiltrat pada lapang atas pulmo kanan (Suspek KP Duplex)',
                saranCustom: 'Konsultasi Spesialis Paru (Sp.P), pemeriksaan dahak TCM/BTA.',
              });
              onNotify('SIMREG: Memuat simulasi temuan Infiltrat Paru / Suspek KP');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-blue-100 text-slate-800 border border-blue-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Ada Infiltrat (Suspek KP)
          </button>
          <button
            type="button"
            onClick={() => {
              setData({
                corDesc: 'Kardiomegali, CTR 56%, apeks jantung membesar ke laterokaudal',
                corStatus: 'Kardiomegali',
                pulmoDesc: 'Corakan bronkovaskular dalam batas normal',
                pulmoStatus: 'Normal',
                diafragmaDesc: 'Diafragma licin, sinus kostofrenikus tajam',
                diafragmaStatus: 'Normal',
                skeletalDesc: 'Tulang-tulang thoraks intak',
                skeletalStatus: 'Normal',
                kesanCustom: 'Kardiomegali (CTR 56%), Pulmo dalam batas normal.',
                saranCustom: 'Konsultasi Spesialis Jantung (Sp.JP), evaluasi hipertensi.',
              });
              onNotify('SIMREG: Memuat simulasi Kardiomegali (CTR > 50%)');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-blue-100 text-slate-800 border border-blue-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Kardiomegali (Pembesaran)
          </button>
          <button
            type="button"
            onClick={() => {
              setData({
                corDesc: 'Ukuran dan bentuk normal, CTR < 50%',
                corStatus: 'Normal',
                pulmoDesc: 'Corakan bronkovaskular normal',
                pulmoStatus: 'Normal',
                diafragmaDesc: 'Sinus kostofrenikus kanan tampak tumpul (curiga efusi pleura minimal)',
                diafragmaStatus: 'Sinus Tumpul',
                skeletalDesc: 'Tulang-tulang thoraks intak',
                skeletalStatus: 'Normal',
                kesanCustom: 'Sinus kostofrenikus kanan tumpul (Suspek Penebalan Pleura / Efusi Minimal).',
                saranCustom: 'Pemeriksaan lanjutan foto rontgen thoraks lateral / USG thorax.',
              });
              onNotify('SIMREG: Memuat simulasi Sinus Kostofrenikus Tumpul');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-blue-100 text-slate-800 border border-blue-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Sinus Kostofrenikus Tumpul
          </button>
        </div>
      </div>

      {/* 2. FITUR FOTO RONTGEN & PACS LIGHTBOX VIEWER */}
      <div className="space-y-3">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-blue-600 text-white flex items-center justify-center shadow-xs">
              <FileImage className="w-4 h-4" />
            </div>
            <div>
              <h4 className="font-extrabold text-[15px] text-slate-900 flex items-center gap-2">
                Foto Citra Rontgen Thorax (PACS Radiography Lightbox)
              </h4>
              <p className="text-[12px] text-slate-500">
                Unggah berkas foto rontgen pasien (JPG/PNG/DICOM) atau eksplorasi citra radiograf interaktif dengan Zoom, Mode Negatif/Invert, dan Penggaris CTR.
              </p>
            </div>
          </div>
        </div>

        <ChestXrayViewer
          patient={patient}
          photoUrl={data.photoUrl ?? 'preset:normal'}
          photoName={data.photoName ?? 'Thorax_PA_Normal_Simulasi.dcm'}
          projection={data.projection ?? 'PA Erektil (Thorax)'}
          onPhotoChange={(url, name) => {
            setData((prev) => ({ ...prev, photoUrl: url, photoName: name }));
          }}
          onApplyPresetFindings={handleApplyPresetFindings}
          onNotify={onNotify}
        />
      </div>

      {/* 3. TABEL INPUT & INTERPRETASI RONTGEN THORAX */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h4 className="font-extrabold text-[15px] text-slate-900 flex items-center gap-2">
            <span>🩻</span>
            Tabel Hasil Pengamatan &amp; Eksplorasi Radiologi
          </h4>
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="px-3.5 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-bold flex items-center gap-1.5 border border-slate-300 cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Tersalin!' : 'Salin Laporan Markdown SIMREG'}
          </button>
        </div>

        <div className="overflow-x-auto rounded-xl border border-slate-200 shadow-2xs">
          <table className="w-full text-left text-[13px] border-collapse min-w-[720px]">
            <thead>
              <tr className="bg-slate-800 text-white font-bold text-[12px]">
                <th className="py-3 px-4 w-52">Organ / Parameter</th>
                <th className="py-3 px-4">Hasil Pengamatan / Eksplorasi</th>
                <th className="py-3 px-4 w-72">Status Sistem</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 bg-white">
              {/* 0. Foto Radiograf Thorax */}
              <tr className="bg-blue-50/40">
                <td className="py-3 px-4 font-bold text-slate-900 flex items-center gap-1.5">
                  <FileImage className="w-4 h-4 text-blue-600" />
                  Foto Radiograf
                </td>
                <td className="py-2.5 px-4">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-bold text-slate-800 bg-white px-2.5 py-1 rounded border border-blue-200 shadow-2xs">
                      {data.photoName || 'Thorax_PA_Normal_Simulasi.dcm'}
                    </span>
                    <span className="text-[11px] text-slate-500 font-mono">
                      (Proyeksi: {data.projection || 'PA Erektil'})
                    </span>
                  </div>
                </td>
                <td className="py-3 px-4">
                  <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs font-mono font-bold bg-emerald-100 text-emerald-800 border border-emerald-300">
                    <Check className="w-3.5 h-3.5 text-emerald-600" />
                    [X] Terlampir &amp; Terverifikasi
                  </span>
                </td>
              </tr>
              {/* 1. Cor (Jantung) */}
              <tr className={`hover:bg-slate-50/80 ${data.corStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Cor (Jantung)</td>
                <td className="py-2.5 px-4">
                  <input
                    type="text"
                    value={data.corDesc}
                    onChange={(e) =>
                      setData((prev) => ({
                        ...prev,
                        corDesc: e.target.value,
                        kesanCustom: '',
                      }))
                    }
                    className="w-full px-3 py-1.5 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  />
                </td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-2 text-xs font-mono">
                    <button
                      type="button"
                      onClick={() => setData((prev) => ({ ...prev, corStatus: 'Normal', kesanCustom: '' }))}
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.corStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.corStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, corStatus: 'Kardiomegali', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.corStatus === 'Kardiomegali'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.corStatus === 'Kardiomegali' ? '[X]' : '[ ]'} Kardiomegali (Pembesaran)
                    </button>
                  </div>
                </td>
              </tr>

              {/* 2. Pulmo (Paru) */}
              <tr className={`hover:bg-slate-50/80 ${data.pulmoStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Pulmo (Paru)</td>
                <td className="py-2.5 px-4">
                  <input
                    type="text"
                    value={data.pulmoDesc}
                    onChange={(e) =>
                      setData((prev) => ({
                        ...prev,
                        pulmoDesc: e.target.value,
                        kesanCustom: '',
                      }))
                    }
                    className="w-full px-3 py-1.5 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  />
                </td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-1.5 text-xs font-mono">
                    <button
                      type="button"
                      onClick={() => setData((prev) => ({ ...prev, pulmoStatus: 'Normal', kesanCustom: '' }))}
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.pulmoStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.pulmoStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, pulmoStatus: 'Infiltrat', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.pulmoStatus === 'Infiltrat'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.pulmoStatus === 'Infiltrat' ? '[X]' : '[ ]'} Ada Infiltrat
                    </button>
                    <button
                      type="button"
                      onClick={() => setData((prev) => ({ ...prev, pulmoStatus: 'Lainnya', kesanCustom: '' }))}
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.pulmoStatus === 'Lainnya'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.pulmoStatus === 'Lainnya' ? '[X]' : '[ ]'} Lainnya
                    </button>
                  </div>
                </td>
              </tr>

              {/* 3. Diafragma & Sinus */}
              <tr className={`hover:bg-slate-50/80 ${data.diafragmaStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Diafragma &amp; Sinus</td>
                <td className="py-2.5 px-4">
                  <input
                    type="text"
                    value={data.diafragmaDesc}
                    onChange={(e) =>
                      setData((prev) => ({
                        ...prev,
                        diafragmaDesc: e.target.value,
                        kesanCustom: '',
                      }))
                    }
                    className="w-full px-3 py-1.5 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  />
                </td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-1.5 text-xs font-mono">
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, diafragmaStatus: 'Normal', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.diafragmaStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.diafragmaStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, diafragmaStatus: 'Sinus Tumpul', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.diafragmaStatus === 'Sinus Tumpul'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.diafragmaStatus === 'Sinus Tumpul' ? '[X]' : '[ ]'} Sinus Tumpul
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, diafragmaStatus: 'Efusi Pleura', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.diafragmaStatus === 'Efusi Pleura'
                          ? 'bg-red-100 text-red-800 border border-red-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.diafragmaStatus === 'Efusi Pleura' ? '[X]' : '[ ]'} Efusi Pleura
                    </button>
                  </div>
                </td>
              </tr>

              {/* 4. Sistem Skeletal */}
              <tr className={`hover:bg-slate-50/80 ${data.skeletalStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Sistem Skeletal</td>
                <td className="py-2.5 px-4">
                  <input
                    type="text"
                    value={data.skeletalDesc}
                    onChange={(e) =>
                      setData((prev) => ({
                        ...prev,
                        skeletalDesc: e.target.value,
                        kesanCustom: '',
                      }))
                    }
                    className="w-full px-3 py-1.5 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  />
                </td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-1.5 text-xs font-mono">
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, skeletalStatus: 'Normal', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.skeletalStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.skeletalStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, skeletalStatus: 'Fraktur', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.skeletalStatus === 'Fraktur'
                          ? 'bg-red-100 text-red-800 border border-red-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.skeletalStatus === 'Fraktur' ? '[X]' : '[ ]'} Fraktur
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, skeletalStatus: 'Kelainan Struktur', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.skeletalStatus === 'Kelainan Struktur'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.skeletalStatus === 'Kelainan Struktur' ? '[X]' : '[ ]'} Kelainan Struktur
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* 4. 📋 KESIMPULAN DIAGNOSIS FINAL (SIMREG-AUTOMATION) */}
      <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-4">
        <h4 className="font-extrabold text-[15px] text-slate-900 flex items-center gap-2 border-b border-slate-200 pb-2">
          <span>📋</span>
          KESIMPULAN DIAGNOSIS FINAL (SIMREG-AUTOMATION)
        </h4>

        <div className="overflow-x-auto rounded-xl border border-slate-200">
          <table className="w-full text-left text-[13px]">
            <tbody className="divide-y divide-slate-200 bg-white">
              {/* Kesimpulan Akhir */}
              <tr>
                <td className="py-3.5 px-4 font-bold text-slate-900 w-52 bg-slate-50/80 align-top">
                  Kesimpulan Akhir:
                </td>
                <td className="py-3.5 px-4 font-mono text-[12.5px]">
                  <div className="flex flex-col gap-1.5">
                    <span
                      className={`px-2.5 py-1 rounded border w-fit font-bold ${
                        isOverallNormal
                          ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                          : 'text-slate-400 border-transparent'
                      }`}
                    >
                      {isOverallNormal ? '[X]' : '[ ]'} RONTGEN THORAX NORMAL (Cor &amp; Pulmo dalam batas normal)
                    </span>
                    <span
                      className={`px-2.5 py-1 rounded border w-fit font-bold ${
                        !isOverallNormal
                          ? 'bg-rose-50 text-rose-800 border-rose-200'
                          : 'text-slate-400 border-transparent'
                      }`}
                    >
                      {!isOverallNormal ? '[X]' : '[ ]'} RONTGEN THORAX ABNORMAL (Ditemukan Kelainan Radiologis)
                    </span>
                  </div>
                </td>
              </tr>

              {/* Kesan Radiologis */}
              <tr>
                <td className="py-3 px-4 font-bold text-slate-900 bg-slate-50/80">
                  Kesan Radiologis:
                </td>
                <td className="py-3 px-4">
                  <div className="space-y-1.5">
                    <input
                      type="text"
                      value={autoKesan}
                      onChange={(e) =>
                        setData((prev) => ({
                          ...prev,
                          kesanCustom: e.target.value,
                        }))
                      }
                      className="w-full px-3 py-1.5 font-bold text-slate-900 bg-slate-50 border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500"
                    />
                    <div className="text-[11px] text-slate-500">
                      Kesan dapat disunting manual atau mengikuti resume otomatis dari data pengamatan.
                    </div>
                  </div>
                </td>
              </tr>

              {/* Saran & Tindak Lanjut */}
              <tr>
                <td className="py-3 px-4 font-bold text-slate-900 bg-slate-50/80">
                  Saran &amp; Tindak Lanjut:
                </td>
                <td className="py-3 px-4">
                  <div className="space-y-1.5">
                    <input
                      type="text"
                      value={autoSaran}
                      onChange={(e) =>
                        setData((prev) => ({
                          ...prev,
                          saranCustom: e.target.value,
                        }))
                      }
                      className="w-full px-3 py-1.5 text-slate-900 bg-slate-50 border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-blue-500"
                    />
                    <div className="text-[11px] text-slate-500">
                      Rekomendasi otomatis aplikasi SIMREG untuk dokter pemeriksa &amp; rekam medis.
                    </div>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="pt-2 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200">
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleSaveToRecord}
            className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-blue-700 to-indigo-700 hover:from-blue-800 hover:to-indigo-800 text-white font-bold text-xs flex items-center gap-2 shadow-md shadow-blue-900/20 cursor-pointer"
          >
            <CheckCircle2 className="w-4 h-4" />
            Simpan Hasil Rontgen #{patient.mcuNo}
          </button>
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="px-4 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold text-xs flex items-center gap-1.5 border border-slate-300 cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            Salin Laporan Markdown SIMREG
          </button>
        </div>

        <div className="text-xs text-slate-500 font-medium">
          Pasien: <b className="text-slate-800">{patient.nama}</b> ({patient.pt}) • No. MCU #{patient.mcuNo}
        </div>
      </div>
    </div>
  );
};
