import React, { useState, useMemo } from 'react';
import {
  Wind,
  Copy,
  Check,
  RotateCcw,
  Sparkles,
  CheckCircle2,
  AlertTriangle,
  FileText,
  Activity,
  Info,
} from 'lucide-react';
import { AttendanceRecord } from '../types';
import { saveAutoGeneratedResume } from '../utils/medicalResumeGenerator';

interface SpirometriFormProps {
  patient: AttendanceRecord;
  examinerDoctor?: string;
  onSave?: (data: any) => void;
  onNotify: (message: string) => void;
}

export interface SpirometriData {
  fvc: number; // % Prediksi (Normal >= 80)
  fev1: number; // % Prediksi (Normal >= 80)
  rasio: number; // % Rasio Aktual FEV1/FVC (Normal >= 70)
  diagnosisCustom?: string;
  saranCustom?: string;
}

// Nilai DEFAULT NORMAL baku sistem SIMREG
export const DEFAULT_NORMAL_SPIROMETRI: SpirometriData = {
  fvc: 95,
  fev1: 92,
  rasio: 82,
  diagnosisCustom: '',
  saranCustom: '',
};

export const SpirometriForm: React.FC<SpirometriFormProps> = ({
  patient,
  examinerDoctor,
  onSave,
  onNotify,
}) => {
  const [data, setData] = useState<SpirometriData>(DEFAULT_NORMAL_SPIROMETRI);
  const [doctorName, setDoctorName] = useState<string>(
    examinerDoctor || 'dr. Rina Setyowati, Sp.P, FAPSR'
  );
  const [quickInputText, setQuickInputText] = useState<string>('NORMAL');
  const [copied, setCopied] = useState<boolean>(false);

  React.useEffect(() => {
    if (examinerDoctor) {
      setDoctorName(examinerDoctor);
    }
  }, [examinerDoctor]);

  React.useEffect(() => {
    if (!patient?.mcuNo) return;
    try {
      const saved = localStorage.getItem(`simreg_spirometri_${patient.mcuNo}`);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed.data) setData(parsed.data);
      }
    } catch (e) {}
  }, [patient?.mcuNo]);

  // Status Parameter Evaluasi
  const fvcIsNormal = data.fvc >= 80;
  const fev1IsNormal = data.fev1 >= 80;
  const rasioIsNormal = data.rasio >= 70;

  // Pola Gangguan Ventilasi
  // Restriksi: FVC < 80 & Rasio >= 70
  // Obstruksi: Rasio < 70 & FVC >= 80
  // Campuran: FVC < 80 & Rasio < 70
  // Normal: FVC >= 80 & Rasio >= 70
  const isNormal = fvcIsNormal && rasioIsNormal;
  const isRestriksi = !fvcIsNormal && rasioIsNormal;
  const isObstruksi = fvcIsNormal && !rasioIsNormal;
  const isCampuran = !fvcIsNormal && !rasioIsNormal;

  // Derajat Keparahan (berdasarkan FEV1)
  const severityLevel = useMemo<'none' | 'ringan' | 'sedang' | 'berat'>(() => {
    if (isNormal) return 'none';
    if (data.fev1 >= 60) return 'ringan';
    if (data.fev1 >= 40) return 'sedang';
    return 'berat';
  }, [isNormal, data.fev1]);

  // Interpretasi Parameter Strings
  const fvcInterpretasiStr = fvcIsNormal
    ? '[X] Normal (≥80%) / [ ] Menurun'
    : '[ ] Normal (≥80%) / [X] Menurun';

  const fev1InterpretasiStr = fev1IsNormal
    ? '[X] Normal (≥80%) / [ ] Menurun'
    : '[ ] Normal (≥80%) / [X] Menurun';

  const rasioInterpretasiStr = rasioIsNormal
    ? '[X] Normal (≥70%) / [ ] Menurun'
    : '[ ] Normal (≥70%) / [X] Menurun';

  // Kesimpulan Akhir String
  const kesimpulanAkhirStr = useMemo(() => {
    const normalTag = isNormal ? '[X]' : '[ ]';
    const restriksiTag = isRestriksi ? '[X]' : '[ ]';
    const obstruksiTag = isObstruksi ? '[X]' : '[ ]';
    const campuranTag = isCampuran ? '[X]' : '[ ]';

    return `${normalTag} FUNGSI PARU NORMAL <br> ${restriksiTag} GANGGUAN RESTRIKSI (FVC menurun, Rasio Normal) <br> ${obstruksiTag} GANGGUAN OBSTRUKSI (Rasio menurun) <br> ${campuranTag} GANGGUAN CAMPURAN (FVC & Rasio menurun)`;
  }, [isNormal, isRestriksi, isObstruksi, isCampuran]);

  // Derajat Keparahan String
  const derajatKeparahanStr = useMemo(() => {
    const noneTag = severityLevel === 'none' ? '[X]' : '[ ]';
    const ringanTag = severityLevel === 'ringan' ? '[X]' : '[ ]';
    const sedangTag = severityLevel === 'sedang' ? '[X]' : '[ ]';
    const beratTag = severityLevel === 'berat' ? '[X]' : '[ ]';

    return `${noneTag} Tidak Ada Gangguan <br> ${ringanTag} Ringan (60-79% Prediksi) <br> ${sedangTag} Sedang (40-59% Prediksi) <br> ${beratTag} Berat (<40% Prediksi)`;
  }, [severityLevel]);

  // Diagnosis Otomatis SIMREG
  const autoDiagnosis = useMemo(() => {
    if (data.diagnosisCustom && data.diagnosisCustom.trim() !== '') {
      return data.diagnosisCustom;
    }
    if (isNormal) {
      return 'Fungsi ventilasi paru normal, tidak ditemukan tanda obstruksi maupun restriksi.';
    }
    const derajatText =
      severityLevel === 'ringan'
        ? 'Derajat Ringan'
        : severityLevel === 'sedang'
        ? 'Derajat Sedang'
        : 'Derajat Berat';

    if (isRestriksi) {
      return `Gangguan Fungsi Paru Restriktif ${derajatText} (Penurunan Kapasitas Vital Paksa).`;
    }
    if (isObstruksi) {
      return `Gangguan Fungsi Paru Obstruktif ${derajatText} (Penurunan Aliran Udara Ekspirasi / Rasio FEV1/FVC).`;
    }
    return `Gangguan Fungsi Paru Campuran (Restriksi + Obstruksi) ${derajatText}.`;
  }, [data.diagnosisCustom, isNormal, isRestriksi, isObstruksi, severityLevel]);

  // Saran Otomatis SIMREG
  const autoSaran = useMemo(() => {
    if (data.saranCustom && data.saranCustom.trim() !== '') {
      return data.saranCustom;
    }
    if (isNormal) {
      return 'Hasil dalam batas normal. Pertahankan higienitas saluran napas dan hindari paparan polutan/rokok.';
    }
    if (isObstruksi) {
      return 'Konsultasikan ke Dokter Spesialis Paru (Sp.P), evaluasi uji bronkodilator reversibilitas, dan wajib gunakan masker respirator saat terpapar debu/kimia industri.';
    }
    if (isRestriksi) {
      return 'Konsultasikan ke Dokter Spesialis Paru (Sp.P), evaluasi foto rontgen thorax berkala, latihan pernapasan, dan kurangi paparan debu respirabel.';
    }
    return 'Rujuk ke Dokter Spesialis Paru (Sp.P) untuk evaluasi fungsi paru komprehensif dan tindak lanjut kelaikan kerja okupasi.';
  }, [data.saranCustom, isNormal, isObstruksi, isRestriksi]);

  // Handler Proses Quick Input Text
  const handleApplyQuickInput = (textToProcess?: string) => {
    const raw = (textToProcess ?? quickInputText).trim();
    if (!raw || raw.toUpperCase() === 'NORMAL') {
      setData(DEFAULT_NORMAL_SPIROMETRI);
      onNotify('SIMREG: Parameter Spirometri diisi otomatis dengan nilai DEFAULT NORMAL baku (FVC 95%, FEV1 92%, Rasio 82%)!');
      return;
    }

    const next = { ...data };
    // Cari pola FVC
    const fvcMatch = raw.match(/fvc\s*[:=]?\s*(\d+)/i);
    if (fvcMatch) next.fvc = parseInt(fvcMatch[1], 10);

    // Cari pola FEV1
    const fev1Match = raw.match(/fev1\s*[:=]?\s*(\d+)/i);
    if (fev1Match) next.fev1 = parseInt(fev1Match[1], 10);

    // Cari pola Rasio
    const rasioMatch = raw.match(/rasio\s*[:=]?\s*(\d+)/i) || raw.match(/fev1\/fvc\s*[:=]?\s*(\d+)/i);
    if (rasioMatch) next.rasio = parseInt(rasioMatch[1], 10);

    setData(next);
    onNotify('SIMREG: Data Spirometri kustom berhasil dihitung ulang!');
  };

  // Generate exact Markdown matching SIMREG specification
  const generateMarkdownOutput = (): string => {
    return `### [SIMREG] Modul Hasil Pemeriksaan Spirometri

| Parameter Fungsi Paru | % Prediksi / Hasil | Nilai Rujukan (Cut-off) | Interpretasi Sistem |
| :--- | :---: | :--- | :--- |
| **FVC** (Kapasitas Vital Paksa) | ${data.fvc}% | ≥ 80% dari Prediksi | ${fvcInterpretasiStr} |
| **FEV1** (Vol. Ekspirasi Paksa 1s) | ${data.fev1}% | ≥ 80% dari Prediksi | ${fev1InterpretasiStr} |
| **FEV1 / FVC** (Rasio Aktual) | ${data.rasio}% | ≥ 70% (Atau ≥ LLN) | ${rasioInterpretasiStr} |

### 📋 KESIMPULAN DIAGNOSIS FINAL (SIMREG-AUTOMATION)

| Kesimpulan Akhir: | ${kesimpulanAkhirStr} |
| :--- | :--- |
| **Dokter Spesialis Paru (Sp.P):** | ${doctorName} |
| **Derajat Keparahan:** | ${derajatKeparahanStr} |
| **Diagnosis Klinis:** | ${autoDiagnosis} |
| **Saran & Tindak Lanjut:** | ${autoSaran} |
`;
  };

  const handleCopyMarkdown = async () => {
    try {
      await navigator.clipboard.writeText(generateMarkdownOutput());
      setCopied(true);
      onNotify('Laporan Spirometri format SIMREG berhasil disalin ke clipboard!');
      setTimeout(() => setCopied(false), 2500);
    } catch {
      onNotify('Gagal menyalin otomatis ke clipboard.');
    }
  };

  const handleSaveToRecord = () => {
    const payload = {
      data,
      isNormal,
      isRestriksi,
      isObstruksi,
      isCampuran,
      severityLevel,
      diagnosis: autoDiagnosis,
      saran: autoSaran,
      markdown: generateMarkdownOutput(),
    };
    try {
      localStorage.setItem(`simreg_spirometri_${patient.mcuNo}`, JSON.stringify(payload));
      saveAutoGeneratedResume(patient.mcuNo);
    } catch (e) {}

    onSave?.(payload);
    onNotify(
      `SIMREG: Hasil Spirometri (${isNormal ? 'Normal' : 'Abnormal'}) untuk ${patient.nama} (#${patient.mcuNo}) berhasil disimpan ke Rekam Medis!`
    );
  };

  return (
    <div className="space-y-6">
      {/* 1. ANTARMUKA AWAL SIMREG (Menunggu Input) */}
      <div className="p-4 sm:p-5 rounded-2xl bg-gradient-to-r from-teal-50 via-cyan-50 to-sky-50 border border-teal-200 shadow-xs">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-xl bg-teal-600 text-white flex items-center justify-center shrink-0 shadow-md">
            <Wind className="w-5 h-5" />
          </div>
          <div className="space-y-2 flex-1">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <h4 className="font-extrabold text-[15px] text-teal-950 flex items-center gap-2">
                [SIMREG] Modul Pemeriksaan Spirometri &amp; Uji Fungsi Paru
              </h4>
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-1 rounded-lg text-[11.5px] font-bold bg-white text-teal-900 border border-teal-200 shadow-2xs flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                  Spesialis Paru (Sp.P): <b>{doctorName}</b>
                </span>
                <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-teal-100 text-teal-800 border border-teal-300 font-mono">
                  SIMREG-AUTOMATION v2.5
                </span>
              </div>
            </div>
            <p className="text-[13px] text-slate-700 leading-relaxed">
              Halo Operator SIMREG! Silakan masukkan data hasil uji fungsi paru (FVC, FEV1, Rasio FEV1/FVC) pasien di bawah ini, atau cukup ketik{' '}
              <b className="font-mono text-teal-800 bg-teal-100/90 px-1.5 py-0.5 rounded">
                "NORMAL"
              </b>{' '}
              untuk mengisi otomatis sistem dengan parameter ideal baku (FVC: 95%, FEV1: 92%, Rasio FEV1/FVC: 82%).
            </p>

            {/* Quick Action Bar */}
            <div className="flex flex-wrap items-center gap-2 pt-2">
              <input
                type="text"
                value={quickInputText}
                onChange={(e) => setQuickInputText(e.target.value)}
                placeholder='Ketik "NORMAL" atau contoh "FVC:70 FEV1:60 Rasio:65"'
                className="px-3 py-1.5 bg-white border border-teal-300 rounded-xl text-xs font-mono font-bold text-slate-800 w-64 focus:ring-2 focus:ring-teal-500 shadow-2xs"
              />
              <button
                type="button"
                onClick={() => handleApplyQuickInput()}
                className="px-3.5 py-1.5 rounded-xl bg-teal-700 hover:bg-teal-800 text-white font-bold text-xs flex items-center gap-1.5 shadow-xs cursor-pointer"
              >
                <Activity className="w-3.5 h-3.5" />
                Proses Data SIMREG
              </button>
              <button
                type="button"
                onClick={() => {
                  setQuickInputText('NORMAL');
                  handleApplyQuickInput('NORMAL');
                }}
                className="px-3.5 py-1.5 rounded-xl bg-white hover:bg-teal-100 text-teal-800 border border-teal-300 font-bold text-xs flex items-center gap-1 cursor-pointer"
              >
                <Sparkles className="w-3.5 h-3.5 text-teal-600" />
                Isi Default NORMAL
              </button>
            </div>
          </div>
        </div>

        {/* Contoh Preset Klinis SIMREG */}
        <div className="mt-4 pt-3 border-t border-teal-200/60 flex flex-wrap items-center gap-2">
          <span className="text-xs font-bold text-teal-900 flex items-center gap-1">
            <Sparkles className="w-3.5 h-3.5 text-teal-600" />
            Simulasi Kasus Klinis:
          </span>
          <button
            type="button"
            onClick={() => {
              setData({
                fvc: 68,
                fev1: 72,
                rasio: 85,
                diagnosisCustom: '',
                saranCustom: '',
              });
              onNotify('SIMREG: Memuat simulasi Gangguan Restriksi (FVC 68%, Rasio 85%)');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-teal-100 text-slate-800 border border-teal-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Gangguan Restriksi
          </button>
          <button
            type="button"
            onClick={() => {
              setData({
                fvc: 85,
                fev1: 58,
                rasio: 62,
                diagnosisCustom: '',
                saranCustom: '',
              });
              onNotify('SIMREG: Memuat simulasi Gangguan Obstruksi (Rasio 62%, FEV1 58%)');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-teal-100 text-slate-800 border border-teal-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Gangguan Obstruksi
          </button>
          <button
            type="button"
            onClick={() => {
              setData({
                fvc: 65,
                fev1: 48,
                rasio: 64,
                diagnosisCustom: '',
                saranCustom: '',
              });
              onNotify('SIMREG: Memuat simulasi Gangguan Campuran (FVC 65%, Rasio 64%)');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-teal-100 text-slate-800 border border-teal-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Gangguan Campuran
          </button>
        </div>
      </div>

      {/* 2 & 3. TABEL INPUT & INTERPRETASI SPIROMETRI */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h4 className="font-extrabold text-[15px] text-slate-900 flex items-center gap-2">
            <span>🫁</span>
            Tabel Input &amp; Interpretasi Spirometri
          </h4>
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="px-3.5 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-bold flex items-center gap-1.5 border border-slate-300 cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Tersalin!' : 'Salin Laporan Markdown SIMREG'}
          </button>
        </div>

        <div className="overflow-x-auto rounded-xl border border-slate-200 shadow-2xs">
          <table className="w-full text-left text-[13px] border-collapse min-w-[700px]">
            <thead>
              <tr className="bg-slate-800 text-white font-bold text-[12px]">
                <th className="py-3 px-4 w-60">Parameter Fungsi Paru</th>
                <th className="py-3 px-4 w-44 text-center">% Prediksi / Hasil</th>
                <th className="py-3 px-4 w-48">Nilai Rujukan (Cut-off)</th>
                <th className="py-3 px-4">Interpretasi Sistem</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 bg-white">
              {/* 1. FVC */}
              <tr className={`hover:bg-slate-50/80 ${!fvcIsNormal ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">
                  FVC <span className="font-normal text-slate-600">(Kapasitas Vital Paksa)</span>
                </td>
                <td className="py-2.5 px-4 text-center">
                  <div className="inline-flex items-center gap-1.5">
                    <input
                      type="number"
                      min="10"
                      max="150"
                      value={data.fvc}
                      onChange={(e) =>
                        setData((prev) => ({
                          ...prev,
                          fvc: parseInt(e.target.value, 10) || 0,
                          diagnosisCustom: '',
                        }))
                      }
                      className="w-20 px-2 py-1 text-center font-mono font-bold text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-teal-500"
                    />
                    <span className="text-xs text-slate-600 font-bold">%</span>
                  </div>
                </td>
                <td className="py-3 px-4 text-slate-600 font-mono text-xs">≥ 80% dari Prediksi</td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-2 text-xs font-mono">
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        fvcIsNormal
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {fvcIsNormal ? '[X]' : '[ ]'} Normal (≥80%)
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        !fvcIsNormal
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {!fvcIsNormal ? '[X]' : '[ ]'} Menurun
                    </span>
                  </div>
                </td>
              </tr>

              {/* 2. FEV1 */}
              <tr className={`hover:bg-slate-50/80 ${!fev1IsNormal ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">
                  FEV1 <span className="font-normal text-slate-600">(Vol. Ekspirasi Paksa 1s)</span>
                </td>
                <td className="py-2.5 px-4 text-center">
                  <div className="inline-flex items-center gap-1.5">
                    <input
                      type="number"
                      min="10"
                      max="150"
                      value={data.fev1}
                      onChange={(e) =>
                        setData((prev) => ({
                          ...prev,
                          fev1: parseInt(e.target.value, 10) || 0,
                          diagnosisCustom: '',
                        }))
                      }
                      className="w-20 px-2 py-1 text-center font-mono font-bold text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-teal-500"
                    />
                    <span className="text-xs text-slate-600 font-bold">%</span>
                  </div>
                </td>
                <td className="py-3 px-4 text-slate-600 font-mono text-xs">≥ 80% dari Prediksi</td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-2 text-xs font-mono">
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        fev1IsNormal
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {fev1IsNormal ? '[X]' : '[ ]'} Normal (≥80%)
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        !fev1IsNormal
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {!fev1IsNormal ? '[X]' : '[ ]'} Menurun
                    </span>
                  </div>
                </td>
              </tr>

              {/* 3. FEV1 / FVC */}
              <tr className={`hover:bg-slate-50/80 ${!rasioIsNormal ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">
                  FEV1 / FVC <span className="font-normal text-slate-600">(Rasio Aktual)</span>
                </td>
                <td className="py-2.5 px-4 text-center">
                  <div className="inline-flex items-center gap-1.5">
                    <input
                      type="number"
                      min="10"
                      max="100"
                      value={data.rasio}
                      onChange={(e) =>
                        setData((prev) => ({
                          ...prev,
                          rasio: parseInt(e.target.value, 10) || 0,
                          diagnosisCustom: '',
                        }))
                      }
                      className="w-20 px-2 py-1 text-center font-mono font-bold text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-teal-500"
                    />
                    <span className="text-xs text-slate-600 font-bold">%</span>
                  </div>
                </td>
                <td className="py-3 px-4 text-slate-600 font-mono text-xs">≥ 70% (Atau ≥ LLN)</td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-2 text-xs font-mono">
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        rasioIsNormal
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {rasioIsNormal ? '[X]' : '[ ]'} Normal (≥70%)
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded font-bold ${
                        !rasioIsNormal
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400'
                      }`}
                    >
                      {!rasioIsNormal ? '[X]' : '[ ]'} Menurun
                    </span>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* 4. 📋 KESIMPULAN DIAGNOSIS FINAL (SIMREG-AUTOMATION) */}
      <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-4">
        <h4 className="font-extrabold text-[15px] text-slate-900 flex items-center gap-2 border-b border-slate-200 pb-2">
          <span>📋</span>
          KESIMPULAN DIAGNOSIS FINAL (SIMREG-AUTOMATION)
        </h4>

        <div className="overflow-x-auto rounded-xl border border-slate-200">
          <table className="w-full text-left text-[13px]">
            <tbody className="divide-y divide-slate-200 bg-white">
              {/* Kesimpulan Akhir */}
              <tr>
                <td className="py-3.5 px-4 font-bold text-slate-900 w-52 bg-slate-50/80 align-top">
                  Kesimpulan Akhir:
                </td>
                <td className="py-3.5 px-4 font-mono text-[12.5px]">
                  <div className="flex flex-col gap-1.5">
                    <span
                      className={`px-2 py-0.5 rounded border w-fit font-bold ${
                        isNormal
                          ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                          : 'text-slate-400 border-transparent'
                      }`}
                    >
                      {isNormal ? '[X]' : '[ ]'} FUNGSI PARU NORMAL
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded border w-fit font-bold ${
                        isRestriksi
                          ? 'bg-amber-50 text-amber-800 border-amber-200'
                          : 'text-slate-400 border-transparent'
                      }`}
                    >
                      {isRestriksi ? '[X]' : '[ ]'} GANGGUAN RESTRIKSI (FVC menurun, Rasio Normal)
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded border w-fit font-bold ${
                        isObstruksi
                          ? 'bg-amber-50 text-amber-800 border-amber-200'
                          : 'text-slate-400 border-transparent'
                      }`}
                    >
                      {isObstruksi ? '[X]' : '[ ]'} GANGGUAN OBSTRUKSI (Rasio menurun)
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded border w-fit font-bold ${
                        isCampuran
                          ? 'bg-red-50 text-red-800 border-red-200'
                          : 'text-slate-400 border-transparent'
                      }`}
                    >
                      {isCampuran ? '[X]' : '[ ]'} GANGGUAN CAMPURAN (FVC &amp; Rasio menurun)
                    </span>
                  </div>
                </td>
              </tr>

              {/* Derajat Keparahan */}
              <tr>
                <td className="py-3.5 px-4 font-bold text-slate-900 bg-slate-50/80 align-top">
                  Derajat Keparahan:
                </td>
                <td className="py-3.5 px-4 font-mono text-[12.5px]">
                  <div className="flex flex-wrap items-center gap-2">
                    <span
                      className={`px-2 py-0.5 rounded border font-bold ${
                        severityLevel === 'none'
                          ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                          : 'text-slate-400 border-transparent'
                      }`}
                    >
                      {severityLevel === 'none' ? '[X]' : '[ ]'} Tidak Ada Gangguan
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded border font-bold ${
                        severityLevel === 'ringan'
                          ? 'bg-amber-50 text-amber-800 border-amber-200'
                          : 'text-slate-400 border-transparent'
                      }`}
                    >
                      {severityLevel === 'ringan' ? '[X]' : '[ ]'} Ringan (60-79% Prediksi)
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded border font-bold ${
                        severityLevel === 'sedang'
                          ? 'bg-orange-50 text-orange-800 border-orange-200'
                          : 'text-slate-400 border-transparent'
                      }`}
                    >
                      {severityLevel === 'sedang' ? '[X]' : '[ ]'} Sedang (40-59% Prediksi)
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded border font-bold ${
                        severityLevel === 'berat'
                          ? 'bg-red-50 text-red-800 border-red-200'
                          : 'text-slate-400 border-transparent'
                      }`}
                    >
                      {severityLevel === 'berat' ? '[X]' : '[ ]'} Berat (&lt;40% Prediksi)
                    </span>
                  </div>
                </td>
              </tr>

              {/* Diagnosis Klinis */}
              <tr>
                <td className="py-3 px-4 font-bold text-slate-900 bg-slate-50/80">
                  Diagnosis Klinis:
                </td>
                <td className="py-3 px-4">
                  <div className="space-y-1.5">
                    <input
                      type="text"
                      value={autoDiagnosis}
                      onChange={(e) =>
                        setData((prev) => ({
                          ...prev,
                          diagnosisCustom: e.target.value,
                        }))
                      }
                      className="w-full px-3 py-1.5 font-bold text-slate-900 bg-slate-50 border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-teal-500"
                    />
                    <div className="text-[11px] text-slate-500">
                      Diagnosis dapat disunting manual atau mengikuti kalkulasi otomatis SIMREG.
                    </div>
                  </div>
                </td>
              </tr>

              {/* Saran & Tindak Lanjut */}
              <tr>
                <td className="py-3 px-4 font-bold text-slate-900 bg-slate-50/80">
                  Saran &amp; Tindak Lanjut:
                </td>
                <td className="py-3 px-4">
                  <div className="space-y-1.5">
                    <input
                      type="text"
                      value={autoSaran}
                      onChange={(e) =>
                        setData((prev) => ({
                          ...prev,
                          saranCustom: e.target.value,
                        }))
                      }
                      className="w-full px-3 py-1.5 text-slate-900 bg-slate-50 border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-teal-500"
                    />
                    <div className="text-[11px] text-slate-500">
                      Rekomendasi tindak lanjut bagi dokter penguji kesehatan kerja.
                    </div>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="pt-2 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200">
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleSaveToRecord}
            className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-teal-700 to-cyan-700 hover:from-teal-800 hover:to-cyan-800 text-white font-bold text-xs flex items-center gap-2 shadow-md shadow-teal-900/20 cursor-pointer"
          >
            <CheckCircle2 className="w-4 h-4" />
            Simpan Hasil Spirometri #{patient.mcuNo}
          </button>
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="px-4 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold text-xs flex items-center gap-1.5 border border-slate-300 cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            Salin Laporan Markdown SIMREG
          </button>
        </div>

        <div className="text-xs text-slate-500 font-medium">
          Pasien: <b className="text-slate-800">{patient.nama}</b> ({patient.pt}) • No. MCU #{patient.mcuNo}
        </div>
      </div>
    </div>
  );
};
