import React, { useState, useMemo } from 'react';
import {
  Activity,
  HeartPulse,
  Clock,
  Zap,
  CheckCircle2,
  AlertTriangle,
  FileText,
  RotateCcw,
  Sparkles,
  Save,
  Gauge,
} from 'lucide-react';
import { AttendanceRecord } from '../types';
import { saveAutoGeneratedResume } from '../utils/medicalResumeGenerator';

interface TreadmillFormProps {
  patient: AttendanceRecord;
  examinerDoctor?: string;
  onSave?: (data: any) => void;
  onNotify: (message: string) => void;
}

export interface TreadmillData {
  protokol: string;
  durasiMenit: number;
  durasiDetik: number;
  mets: number;
  
  // Heart Rate
  restingHr: number;
  peakHr: number;
  recovery1Hr: number;
  recovery3Hr: number;
  targetHr85: number;
  maxHrUsia: number;
  
  // Blood Pressure
  restingBp: string;
  peakBp: string;
  recoveryBp: string;

  // Respon EKG & Klinis
  stSegmentChange: 'Tidak Ada Deviasi ST (Normal)' | 'ST Depresi Horizontal/Downsloping' | 'ST Elevasi';
  aritmia: 'Sinus Rhythm Normal (Tidak Ada Aritmia)' | 'VPC Terisolasi' | 'SVT / Takikardia' | 'Aritmia Lainnya';
  keluhanKlinis: 'Tidak Ada Keluhan (Asimptomatik)' | 'Nyeri Dada Tipikal Angina' | 'Sesak Napas Berat' | 'Kelelahan Ekstrem' | 'Pusing / Presinkop';
  alasanBerhenti: 'Target Heart Rate Tercapai (>85% Max HR)' | 'Kelelahan Fisik Maksimal' | 'Kriteria Penghentian Medis';

  // Hasil Akhir
  kesimpulan: string;
  kategoriHasil: 'Negatif Iskemik (Normal)' | 'Positif Iskemik' | 'Inconclusive (Submaksimal)';
  kapasitasFungsional: 'Sangat Baik' | 'Baik' | 'Cukup' | 'Kurang';
  saranDokter: string;
}

export const TreadmillForm: React.FC<TreadmillFormProps> = ({
  patient,
  examinerDoctor,
  onSave,
  onNotify,
}) => {
  // Hitung usia pasien
  const age = useMemo(() => {
    if (!patient.tglLahir) return 35;
    const yearMatch = patient.tglLahir.match(/\b(19\d{2}|20\d{2})\b/);
    if (yearMatch) {
      return new Date().getFullYear() - parseInt(yearMatch[0], 10);
    }
    return 35;
  }, [patient.tglLahir]);

  // Max HR = 220 - Usia
  const maxHrCalc = 220 - age;
  const target85Calc = Math.round(maxHrCalc * 0.85);

  const defaultData: TreadmillData = {
    protokol: 'Bruce Protocol',
    durasiMenit: 9,
    durasiDetik: 45,
    mets: 10.2,
    restingHr: 72,
    peakHr: target85Calc + 8,
    recovery1Hr: 120,
    recovery3Hr: 86,
    maxHrUsia: maxHrCalc,
    targetHr85: target85Calc,
    restingBp: '120/80',
    peakBp: '155/85',
    recoveryBp: '125/80',
    stSegmentChange: 'Tidak Ada Deviasi ST (Normal)',
    aritmia: 'Sinus Rhythm Normal (Tidak Ada Aritmia)',
    keluhanKlinis: 'Tidak Ada Keluhan (Asimptomatik)',
    alasanBerhenti: 'Target Heart Rate Tercapai (>85% Max HR)',
    kesimpulan: 'Uji Latih Jantung Beban (Treadmill Test) Negatif untuk iskemia miokard. Respon kronotropik dan hemodinamik adekuat.',
    kategoriHasil: 'Negatif Iskemik (Normal)',
    kapasitasFungsional: 'Baik',
    saranDokter: 'Kapasitas fungsional kardiovaskular baik (METs > 10). Pertahankan aktivitas fisik teratur dan pola hidup sehat.',
  };

  const [formData, setFormData] = useState<TreadmillData>(defaultData);
  const [doctorName, setDoctorName] = useState<string>(
    examinerDoctor || 'dr. Hendra Wijaya, Sp.JP'
  );

  React.useEffect(() => {
    if (examinerDoctor) {
      setDoctorName(examinerDoctor);
    }
  }, [examinerDoctor]);

  React.useEffect(() => {
    if (!patient?.mcuNo) return;
    try {
      const saved = localStorage.getItem(`simreg_treadmill_${patient.mcuNo}`);
      if (saved) {
        const parsed = JSON.parse(saved);
        setFormData((prev) => ({ ...prev, ...parsed }));
        if (parsed.doctorName) setDoctorName(parsed.doctorName);
      }
    } catch (e) {}
  }, [patient?.mcuNo]);

  // % Target HR tercapai
  const pctHrAchieved = useMemo(() => {
    if (!maxHrCalc) return 0;
    return Math.round((formData.peakHr / maxHrCalc) * 100);
  }, [formData.peakHr, maxHrCalc]);

  const handleApplyPreset = (preset: 'normal' | 'positif') => {
    if (preset === 'normal') {
      setFormData(defaultData);
      onNotify('Preset Treadmill Normal (Negatif Iskemik) berhasil diterapkan.');
    } else {
      setFormData((prev) => ({
        ...prev,
        stSegmentChange: 'ST Depresi Horizontal/Downsloping',
        keluhanKlinis: 'Nyeri Dada Tipikal Angina',
        kategoriHasil: 'Positif Iskemik',
        kesimpulan: 'Uji Latih Jantung Beban (Treadmill Test) Positif Iskemik. Ditemukan ST Depresi horizontal > 1.5 mm pada lead II, III, aVF, V4-V6 disertai keluhan angina pada stadium 3.',
        saranDokter: 'Konsultasi lanjutan ke Dokter Spesialis Jantung & Pembuluh Darah (Sp.JP) untuk evaluasi angiografi koroner / MSCT kardiak.',
      }));
      onNotify('Preset Treadmill Positif Iskemik diterapkan.');
    }
  };

  const handleSaveForm = (e: React.FormEvent) => {
    e.preventDefault();
    const payload = {
      ...formData,
      doctorName,
    };
    try {
      localStorage.setItem(`simreg_treadmill_${patient.mcuNo}`, JSON.stringify(payload));
      saveAutoGeneratedResume(patient.mcuNo);
    } catch (err) {}
    if (onSave) {
      onSave(payload);
    }
    onNotify(
      `Hasil Treadmill Test untuk [${patient.mcuNo} - ${patient.nama}] berhasil disimpan!`
    );
  };

  return (
    <form onSubmit={handleSaveForm} className="space-y-6">
      {/* Header Info Peserta & Penugasan Dokter */}
      <div className="bg-gradient-to-r from-blue-50 via-indigo-50 to-cyan-50 border border-blue-200 rounded-2xl p-4 md:p-5 flex flex-wrap items-center justify-between gap-4 shadow-xs">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-indigo-700 text-white flex items-center justify-center shadow-md shadow-indigo-700/20">
            <Zap className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="px-2 py-0.5 rounded text-[11px] font-extrabold bg-indigo-700 text-white font-mono">
                {patient.mcuNo}
              </span>
              <h3 className="text-[17px] font-extrabold text-slate-900">
                {patient.nama}
              </h3>
              <span className="text-[12px] text-slate-500">
                (Usia: {age} thn, {patient.jk})
              </span>
            </div>
            <p className="text-[12px] text-slate-600 mt-0.5">
              PT: <b className="text-slate-800">{patient.pt}</b> &bull; Paket:{' '}
              <span className="text-indigo-800 font-bold">{patient.paket}</span>
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <div className="text-right">
            <span className="text-[11px] text-indigo-700 font-medium block">
              Dokter Penilai Treadmill:
            </span>
            <input
              type="text"
              value={doctorName}
              onChange={(e) => setDoctorName(e.target.value)}
              className="text-[13px] font-bold text-slate-900 bg-white border border-indigo-300 rounded-lg px-2.5 py-1 text-right focus:ring-2 focus:ring-indigo-500/20"
            />
          </div>
          <div className="flex gap-1.5">
            <button
              type="button"
              onClick={() => handleApplyPreset('normal')}
              className="px-2.5 py-1.5 bg-white hover:bg-indigo-50 border border-indigo-300 text-indigo-800 text-[11px] font-bold rounded-lg flex items-center gap-1 shadow-2xs transition-colors"
            >
              <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
              Preset Negatif (Normal)
            </button>
          </div>
        </div>
      </div>

      {/* SECTION 1: PROTOKOL & STATISTIK JANTUNG */}
      <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2">
            <Gauge className="w-5 h-5 text-indigo-600" />
            <h4 className="text-[15px] font-extrabold text-slate-900">
              1. Protokol Uji &amp; Dinamika Denyut Jantung (Heart Rate)
            </h4>
          </div>
          <span
            className={`text-[11px] font-bold px-2.5 py-0.5 rounded-full ${
              pctHrAchieved >= 85
                ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                : 'bg-amber-100 text-amber-800 border border-amber-300'
            }`}
          >
            Target HR: {pctHrAchieved}% Tercapai ({formData.peakHr}/{maxHrCalc} bpm)
          </span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div>
            <label className="block text-[11px] font-bold text-slate-700 mb-1">
              Protokol Uji
            </label>
            <select
              value={formData.protokol}
              onChange={(e) => setFormData({ ...formData, protokol: e.target.value })}
              className="w-full px-3 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[13px] font-semibold"
            >
              <option value="Bruce Protocol">Bruce Protocol (Standar)</option>
              <option value="Modified Bruce">Modified Bruce Protocol</option>
              <option value="Naughton Protocol">Naughton Protocol</option>
            </select>
          </div>

          <div>
            <label className="block text-[11px] font-bold text-slate-700 mb-1">
              Durasi Latihan (Menit : Detik)
            </label>
            <div className="flex items-center gap-1.5">
              <input
                type="number"
                value={formData.durasiMenit}
                onChange={(e) => setFormData({ ...formData, durasiMenit: Number(e.target.value) })}
                className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[13px] font-bold text-center"
              />
              <span>:</span>
              <input
                type="number"
                value={formData.durasiDetik}
                onChange={(e) => setFormData({ ...formData, durasiDetik: Number(e.target.value) })}
                className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[13px] font-bold text-center"
              />
            </div>
          </div>

          <div>
            <label className="block text-[11px] font-bold text-slate-700 mb-1">
              Kapasitas Fungsional (METs)
            </label>
            <input
              type="number"
              step="0.1"
              value={formData.mets}
              onChange={(e) => setFormData({ ...formData, mets: Number(e.target.value) })}
              className="w-full px-3 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[13px] font-bold text-slate-800 text-center"
            />
            <span className="text-[10.5px] text-slate-400 block text-center mt-0.5">Norma: &gt;10 METs (Sangat Baik)</span>
          </div>

          <div>
            <label className="block text-[11px] font-bold text-slate-700 mb-1">
              Alasan Penghentian
            </label>
            <select
              value={formData.alasanBerhenti}
              onChange={(e) => setFormData({ ...formData, alasanBerhenti: e.target.value as any })}
              className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-300 rounded-lg text-[12px]"
            >
              <option value="Target Heart Rate Tercapai (>85% Max HR)">Target HR Tercapai (&gt;85%)</option>
              <option value="Kelelahan Fisik Maksimal">Kelelahan Fisik Maksimal</option>
              <option value="Kriteria Penghentian Medis">Kriteria Medis (Angina / ST Shift)</option>
            </select>
          </div>
        </div>

        {/* HR & BP Track */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50/80 p-3.5 rounded-xl border border-slate-200">
          <div>
            <span className="text-[11px] text-slate-500 block">Resting HR / BP</span>
            <div className="flex items-center gap-2 mt-1">
              <input
                type="number"
                value={formData.restingHr}
                onChange={(e) => setFormData({ ...formData, restingHr: Number(e.target.value) })}
                className="w-16 px-2 py-1 bg-white border rounded text-xs font-bold text-center"
              />
              <span className="text-xs">bpm</span>
              <input
                type="text"
                value={formData.restingBp}
                onChange={(e) => setFormData({ ...formData, restingBp: e.target.value })}
                className="w-20 px-2 py-1 bg-white border rounded text-xs text-center"
              />
            </div>
          </div>

          <div>
            <span className="text-[11px] text-slate-500 block">Peak Exercise HR / BP</span>
            <div className="flex items-center gap-2 mt-1">
              <input
                type="number"
                value={formData.peakHr}
                onChange={(e) => setFormData({ ...formData, peakHr: Number(e.target.value) })}
                className="w-16 px-2 py-1 bg-white border rounded text-xs font-bold text-center text-indigo-700"
              />
              <span className="text-xs">bpm</span>
              <input
                type="text"
                value={formData.peakBp}
                onChange={(e) => setFormData({ ...formData, peakBp: e.target.value })}
                className="w-20 px-2 py-1 bg-white border rounded text-xs text-center font-bold"
              />
            </div>
          </div>

          <div>
            <span className="text-[11px] text-slate-500 block">Recovery Menit ke-1 HR</span>
            <div className="flex items-center gap-2 mt-1">
              <input
                type="number"
                value={formData.recovery1Hr}
                onChange={(e) => setFormData({ ...formData, recovery1Hr: Number(e.target.value) })}
                className="w-16 px-2 py-1 bg-white border rounded text-xs font-semibold text-center"
              />
              <span className="text-xs">bpm</span>
            </div>
          </div>

          <div>
            <span className="text-[11px] text-slate-500 block">Recovery Menit ke-3 HR / BP</span>
            <div className="flex items-center gap-2 mt-1">
              <input
                type="number"
                value={formData.recovery3Hr}
                onChange={(e) => setFormData({ ...formData, recovery3Hr: Number(e.target.value) })}
                className="w-16 px-2 py-1 bg-white border rounded text-xs font-semibold text-center"
              />
              <span className="text-xs">bpm</span>
              <input
                type="text"
                value={formData.recoveryBp}
                onChange={(e) => setFormData({ ...formData, recoveryBp: e.target.value })}
                className="w-20 px-2 py-1 bg-white border rounded text-xs text-center"
              />
            </div>
          </div>
        </div>
      </div>

      {/* SECTION 2: EVALUASI EKG & RESPON KLINIS */}
      <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs space-y-4">
        <div className="flex items-center gap-2 border-b border-slate-100 pb-3">
          <HeartPulse className="w-5 h-5 text-indigo-600" />
          <h4 className="text-[15px] font-extrabold text-slate-900">
            2. Perubahan Segmen ST, Irama &amp; Respon Klinis
          </h4>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label className="block text-[11.5px] font-bold text-slate-700 mb-1">
              Perubahan Segmen ST
            </label>
            <select
              value={formData.stSegmentChange}
              onChange={(e) => setFormData({ ...formData, stSegmentChange: e.target.value as any })}
              className={`w-full px-3 py-2 bg-slate-50 border rounded-lg text-[12.5px] font-semibold ${
                formData.stSegmentChange.includes('Normal')
                  ? 'border-slate-300 text-slate-800'
                  : 'border-rose-300 text-rose-800 bg-rose-50'
              }`}
            >
              <option value="Tidak Ada Deviasi ST (Normal)">Tidak Ada Deviasi ST (Normal / Isoelektris)</option>
              <option value="ST Depresi Horizontal/Downsloping">ST Depresi Horizontal/Downsloping (&gt; 1 mm)</option>
              <option value="ST Elevasi">ST Elevasi</option>
            </select>
          </div>

          <div>
            <label className="block text-[11.5px] font-bold text-slate-700 mb-1">
              Irama / Aritmia
            </label>
            <select
              value={formData.aritmia}
              onChange={(e) => setFormData({ ...formData, aritmia: e.target.value as any })}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[12.5px] font-semibold"
            >
              <option value="Sinus Rhythm Normal (Tidak Ada Aritmia)">Sinus Rhythm Normal (Tidak Ada Aritmia)</option>
              <option value="VPC Terisolasi">Ventricular Premature Contraction (VPC) Terisolasi</option>
              <option value="SVT / Takikardia">Supraventrikular Takikardia (SVT)</option>
              <option value="Aritmia Lainnya">Aritmia Lainnya</option>
            </select>
          </div>

          <div>
            <label className="block text-[11.5px] font-bold text-slate-700 mb-1">
              Gejala / Keluhan Klinis Pasien
            </label>
            <select
              value={formData.keluhanKlinis}
              onChange={(e) => setFormData({ ...formData, keluhanKlinis: e.target.value as any })}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[12.5px] font-semibold"
            >
              <option value="Tidak Ada Keluhan (Asimptomatik)">Tidak Ada Keluhan (Asimptomatik)</option>
              <option value="Nyeri Dada Tipikal Angina">Nyeri Dada Tipikal Angina</option>
              <option value="Sesak Napas Berat">Sesak Napas Berat (Dyspnea)</option>
              <option value="Kelelahan Ekstrem">Kelelahan Fisik Ekstrem (Fatigue)</option>
              <option value="Pusing / Presinkop">Pusing / Dizziness</option>
            </select>
          </div>
        </div>
      </div>

      {/* SECTION 3: KESIMPULAN & SARAN */}
      <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs space-y-4">
        <div className="flex items-center gap-2 border-b border-slate-100 pb-3">
          <FileText className="w-5 h-5 text-indigo-600" />
          <h4 className="text-[15px] font-extrabold text-slate-900">
            3. Kesimpulan Uji Latih Jantung &amp; Saran Dokter
          </h4>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-[12px] font-bold text-slate-700 mb-1">
              Kategori Hasil Treadmill:
            </label>
            <select
              value={formData.kategoriHasil}
              onChange={(e) => setFormData({ ...formData, kategoriHasil: e.target.value as any })}
              className={`w-full px-3 py-2 rounded-lg text-[13px] font-bold border ${
                formData.kategoriHasil === 'Negatif Iskemik (Normal)'
                  ? 'bg-emerald-50 border-emerald-300 text-emerald-900'
                  : 'bg-rose-50 border-rose-300 text-rose-900'
              }`}
            >
              <option value="Negatif Iskemik (Normal)">Negatif Iskemik (Normal - Respon Iskemik (-))</option>
              <option value="Positif Iskemik">Positif Iskemik (Tanda Iskemia Miokard (+))</option>
              <option value="Inconclusive (Submaksimal)">Inconclusive / Submaksimal</option>
            </select>

            <div className="mt-3">
              <label className="block text-[12px] font-bold text-slate-700 mb-1">
                Deskripsi Kesimpulan:
              </label>
              <textarea
                rows={3}
                value={formData.kesimpulan}
                onChange={(e) => setFormData({ ...formData, kesimpulan: e.target.value })}
                className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[12.5px] focus:ring-2 focus:ring-indigo-500/20"
              />
            </div>
          </div>

          <div>
            <label className="block text-[12px] font-bold text-slate-700 mb-1">
              Kapasitas Fungsional Kebugaran:
            </label>
            <select
              value={formData.kapasitasFungsional}
              onChange={(e) => setFormData({ ...formData, kapasitasFungsional: e.target.value as any })}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[13px] font-semibold"
            >
              <option value="Sangat Baik">Sangat Baik (&gt;12 METs)</option>
              <option value="Baik">Baik (10 - 12 METs)</option>
              <option value="Cukup">Cukup (7 - 10 METs)</option>
              <option value="Kurang">Kurang (&lt;7 METs)</option>
            </select>

            <div className="mt-3">
              <label className="block text-[12px] font-bold text-slate-700 mb-1">
                Saran &amp; Anjuran Dokter:
              </label>
              <textarea
                rows={3}
                value={formData.saranDokter}
                onChange={(e) => setFormData({ ...formData, saranDokter: e.target.value })}
                className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-[12.5px] focus:ring-2 focus:ring-indigo-500/20"
              />
            </div>
          </div>
        </div>
      </div>

      {/* Tombol Simpan */}
      <div className="flex items-center justify-between pt-2">
        <button
          type="button"
          onClick={() => setFormData(defaultData)}
          className="px-4 py-2.5 rounded-xl border border-slate-300 bg-white hover:bg-slate-50 text-slate-700 text-[13px] font-bold flex items-center gap-1.5 transition-colors shadow-xs"
        >
          <RotateCcw className="w-4 h-4 text-slate-500" />
          Reset Nilai Standar
        </button>

        <button
          type="submit"
          className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-indigo-700 to-blue-700 hover:from-indigo-800 hover:to-blue-800 text-white text-[13px] font-bold flex items-center gap-2 shadow-md shadow-indigo-700/20 transition-all hover:scale-[1.01]"
        >
          <Save className="w-4 h-4" />
          Simpan Hasil Treadmill Test
        </button>
      </div>
    </form>
  );
};
