import React, { useState, useMemo } from 'react';
import {
  Copy,
  Check,
  Sparkles,
  CheckCircle2,
  Activity,
  Microscope,
} from 'lucide-react';
import { AttendanceRecord } from '../types';
import { saveAutoGeneratedResume } from '../utils/medicalResumeGenerator';

interface USGAbdomenFormProps {
  patient: AttendanceRecord;
  examinerDoctor?: string;
  onSave?: (data: any) => void;
  onNotify: (message: string) => void;
}

export interface USGAbdomenData {
  heparDesc: string;
  heparStatus: 'Normal' | 'Fatty Liver' | 'Lainnya';
  vesicaFelleaDesc: string;
  vesicaFelleaStatus: 'Normal' | 'Kolelitiasis' | 'Kolesistitis';
  pankreasLienDesc: string;
  pankreasLienStatus: 'Normal' | 'Splenomegali' | 'Lainnya';
  renDesc: string;
  renStatus: 'Normal' | 'Nefrolitiasis' | 'Kista/Massa';
  vesicaUrinariaDesc: string;
  vesicaUrinariaStatus: 'Normal' | 'Sistitis' | 'Batu/Massa';
  reproduksiDesc: string;
  reproduksiStatus: 'Normal' | 'Hipertrofi' | 'Lainnya';
  kesanCustom?: string;
  saranCustom?: string;
}

// Nilai DEFAULT NORMAL baku SIMREG
export const DEFAULT_NORMAL_USG: USGAbdomenData = {
  heparDesc: 'Ukuran normal, permukaan rata, pinggir tajam, echostruktur homogen, tak tampak massa/kista',
  heparStatus: 'Normal',
  vesicaFelleaDesc: 'Ukuran normal, dinding tidak menebal, tak tampak batu/sludge',
  vesicaFelleaStatus: 'Normal',
  pankreasLienDesc: 'Ukuran dan echostruktur normal, tak tampak massa, vena lienalis tidak melebar',
  pankreasLienStatus: 'Normal',
  renDesc: 'Ukuran normal, batas kortikomeduler tegas, sistem pelviokalises tidak melebar, tak tampak batu/massa',
  renStatus: 'Normal',
  vesicaUrinariaDesc: 'Dinding tidak menebal, permukaan rata, tak tampak batu/massa',
  vesicaUrinariaStatus: 'Normal',
  reproduksiDesc: 'Ukuran dan echostruktur normal, tak tampak kelainan/massa',
  reproduksiStatus: 'Normal',
  kesanCustom: '',
  saranCustom: '',
};

export const USGAbdomenForm: React.FC<USGAbdomenFormProps> = ({
  patient,
  examinerDoctor,
  onSave,
  onNotify,
}) => {
  const [data, setData] = useState<USGAbdomenData>(DEFAULT_NORMAL_USG);
  const [doctorName, setDoctorName] = useState<string>(
    examinerDoctor || 'dr. Farida Hanum, Sp.Rad'
  );
  const [quickInputText, setQuickInputText] = useState<string>('NORMAL');
  const [copied, setCopied] = useState<boolean>(false);

  React.useEffect(() => {
    if (examinerDoctor) {
      setDoctorName(examinerDoctor);
    }
  }, [examinerDoctor]);

  React.useEffect(() => {
    if (!patient?.mcuNo) return;
    try {
      const saved = localStorage.getItem(`simreg_usg_${patient.mcuNo}`);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed.data) setData(parsed.data);
      }
    } catch (e) {}
  }, [patient?.mcuNo]);

  // Status Evaluasi Keseluruhan Organ
  const isOverallNormal = useMemo(() => {
    return (
      data.heparStatus === 'Normal' &&
      data.vesicaFelleaStatus === 'Normal' &&
      data.pankreasLienStatus === 'Normal' &&
      data.renStatus === 'Normal' &&
      data.vesicaUrinariaStatus === 'Normal' &&
      data.reproduksiStatus === 'Normal'
    );
  }, [
    data.heparStatus,
    data.vesicaFelleaStatus,
    data.pankreasLienStatus,
    data.renStatus,
    data.vesicaUrinariaStatus,
    data.reproduksiStatus,
  ]);

  // Interpretasi Strings untuk Tabel SIMREG
  const heparStatusStr = useMemo(() => {
    return `${data.heparStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      data.heparStatus === 'Fatty Liver' ? '[X]' : '[ ]'
    } Fatty Liver / ${data.heparStatus === 'Lainnya' ? '[X]' : '[ ]'} Lainnya`;
  }, [data.heparStatus]);

  const vesicaFelleaStatusStr = useMemo(() => {
    return `${data.vesicaFelleaStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      data.vesicaFelleaStatus === 'Kolelitiasis' ? '[X]' : '[ ]'
    } Kolelitiasis (Batu) / ${
      data.vesicaFelleaStatus === 'Kolesistitis' ? '[X]' : '[ ]'
    } Kolesistitis`;
  }, [data.vesicaFelleaStatus]);

  const pankreasLienStatusStr = useMemo(() => {
    return `${data.pankreasLienStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      data.pankreasLienStatus === 'Splenomegali' ? '[X]' : '[ ]'
    } Splenomegali / ${data.pankreasLienStatus === 'Lainnya' ? '[X]' : '[ ]'} Lainnya`;
  }, [data.pankreasLienStatus]);

  const renStatusStr = useMemo(() => {
    return `${data.renStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      data.renStatus === 'Nefrolitiasis' ? '[X]' : '[ ]'
    } Nefrolitiasis (Batu) / ${
      data.renStatus === 'Kista/Massa' ? '[X]' : '[ ]'
    } Kista/Massa`;
  }, [data.renStatus]);

  const vesicaUrinariaStatusStr = useMemo(() => {
    return `${data.vesicaUrinariaStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      data.vesicaUrinariaStatus === 'Sistitis' ? '[X]' : '[ ]'
    } Sistitis / ${data.vesicaUrinariaStatus === 'Batu/Massa' ? '[X]' : '[ ]'} Batu/Massa`;
  }, [data.vesicaUrinariaStatus]);

  const organReproduksiTitle =
    patient.jk === 'P' || patient.jk?.toLowerCase() === 'wanita'
      ? 'Uterus & Adneksa (Wanita)'
      : 'Prostat (Pria) / Uterus (Wanita)';

  const reproduksiStatusStr = useMemo(() => {
    return `${data.reproduksiStatus === 'Normal' ? '[X]' : '[ ]'} Normal / ${
      data.reproduksiStatus === 'Hipertrofi' ? '[X]' : '[ ]'
    } Hipertrofi (BPH/Mioma) / ${
      data.reproduksiStatus === 'Lainnya' ? '[X]' : '[ ]'
    } Lainnya`;
  }, [data.reproduksiStatus]);

  // Kesimpulan Akhir String
  const kesimpulanAkhirStr = useMemo(() => {
    return isOverallNormal
      ? '[X] USG ABDOMEN NORMAL (Seluruh organ abdomen dalam batas normal) <br> [ ] USG ABDOMEN ABNORMAL (Ditemukan Kelainan Sonografis)'
      : '[ ] USG ABDOMEN NORMAL (Seluruh organ abdomen dalam batas normal) <br> [X] USG ABDOMEN ABNORMAL (Ditemukan Kelainan Sonografis)';
  }, [isOverallNormal]);

  // Kesan Sonografis Otomatis SIMREG
  const autoKesan = useMemo(() => {
    if (data.kesanCustom && data.kesanCustom.trim() !== '') {
      return data.kesanCustom;
    }
    if (isOverallNormal) {
      return 'Sonografi organ-organ intraabdomen dalam batas normal.';
    }

    const findings: string[] = [];
    if (data.heparStatus === 'Fatty Liver') {
      findings.push('Fatty Liver (Perlemakan Hati)');
    } else if (data.heparStatus === 'Lainnya') {
      findings.push('Kelainan sonografis hepar');
    }

    if (data.vesicaFelleaStatus === 'Kolelitiasis') {
      findings.push('Kolelitiasis (Batu Kandung Empedu)');
    } else if (data.vesicaFelleaStatus === 'Kolesistitis') {
      findings.push('Kolesistitis (Penebalan Dinding Empedu)');
    }

    if (data.pankreasLienStatus === 'Splenomegali') {
      findings.push('Splenomegali');
    } else if (data.pankreasLienStatus === 'Lainnya') {
      findings.push('Kelainan sonografis pankreas/lien');
    }

    if (data.renStatus === 'Nefrolitiasis') {
      findings.push('Nefrolitiasis (Batu Ginjal)');
    } else if (data.renStatus === 'Kista/Massa') {
      findings.push('Kista / Massa Renal');
    }

    if (data.vesicaUrinariaStatus === 'Sistitis') {
      findings.push('Sistitis (Penebalan Dinding Kandung Kemih)');
    } else if (data.vesicaUrinariaStatus === 'Batu/Massa') {
      findings.push('Batu / Massa Vesica Urinaria');
    }

    if (data.reproduksiStatus === 'Hipertrofi') {
      findings.push(
        patient.jk === 'P'
          ? 'Suspek Mioma Uteri'
          : 'Benign Prostatic Hyperplasia (BPH)'
      );
    } else if (data.reproduksiStatus === 'Lainnya') {
      findings.push('Kelainan organ pelvis/reproduksi');
    }

    return findings.join('; ') + '.';
  }, [
    data.kesanCustom,
    isOverallNormal,
    data.heparStatus,
    data.vesicaFelleaStatus,
    data.pankreasLienStatus,
    data.renStatus,
    data.vesicaUrinariaStatus,
    data.reproduksiStatus,
    patient.jk,
  ]);

  // Saran Otomatis SIMREG
  const autoSaran = useMemo(() => {
    if (data.saranCustom && data.saranCustom.trim() !== '') {
      return data.saranCustom;
    }
    if (isOverallNormal) {
      return 'Hasil dalam batas normal, pertahankan pola makan sehat dan evaluasi klinis berkala.';
    }
    if (data.heparStatus === 'Fatty Liver') {
      return 'Modifikasi gaya hidup, diet rendah lemak dan karbohidrat sederhana, olahraga teratur 150 menit/minggu, dan evaluasi profil lipid darah serta enzim hati (SGOT/SGPT).';
    }
    if (data.vesicaFelleaStatus === 'Kolelitiasis') {
      return 'Konsultasikan ke Dokter Spesialis Bedah Digestif (Sp.B-KBD), hindari makanan berlemak/santan tinggi, dan pantau gejala nyeri perut kanan atas.';
    }
    if (data.renStatus === 'Nefrolitiasis') {
      return 'Konsultasikan ke Dokter Spesialis Urologi (Sp.U), tingkatkan asupan cairan minimal 2.5–3 L/hari, kurangi konsumsi garam dan purin/oksalat tinggi.';
    }
    return 'Konsultasikan temuan sonografis dengan dokter spesialis terkait untuk penatalaksanaan klinis dan evaluasi berkala.';
  }, [
    data.saranCustom,
    isOverallNormal,
    data.heparStatus,
    data.vesicaFelleaStatus,
    data.renStatus,
  ]);

  // Handler Quick Input Text
  const handleApplyQuickInput = (textToProcess?: string) => {
    const raw = (textToProcess ?? quickInputText).trim();
    if (!raw || raw.toUpperCase() === 'NORMAL') {
      setData(DEFAULT_NORMAL_USG);
      onNotify('SIMREG: Parameter USG Abdomen diisi otomatis dengan nilai DEFAULT NORMAL baku!');
      return;
    }

    const next = { ...data };
    const lower = raw.toLowerCase();

    // Deteksi kata kunci
    if (lower.includes('fatty') || lower.includes('perlemakan') || lower.includes('steatosis')) {
      next.heparStatus = 'Fatty Liver';
      next.heparDesc = 'Echogenisitas parenkim hepar meningkat difus (gambaran bright liver), vaskularisasi perifer kabur';
    }
    if (lower.includes('batu empedu') || lower.includes('kolelitiasis')) {
      next.vesicaFelleaStatus = 'Kolelitiasis';
      next.vesicaFelleaDesc = 'Tampak bayangan hiperekoik disertai acoustic shadow di dalam lumen vesica fellea';
    }
    if (lower.includes('batu ginjal') || lower.includes('nefrolitiasis')) {
      next.renStatus = 'Nefrolitiasis';
      next.renDesc = 'Tampak fokus hiperekoik berukuran kalsifikasi disertai posterior acoustic shadow pada kaliks ginjal';
    }
    if (lower.includes('kista ginjal') || lower.includes('kista')) {
      next.renStatus = 'Kista/Massa';
      next.renDesc = 'Tampak lesi anekoik berdinding tipis dan tegas (kista korteks ginjal)';
    }
    if (lower.includes('bph') || lower.includes('prostat') || lower.includes('mioma')) {
      next.reproduksiStatus = 'Hipertrofi';
      next.reproduksiDesc =
        patient.jk === 'P'
          ? 'Tampak lesi hipoekoik berbatas tegas pada miometrium (suspek mioma)'
          : 'Pembesaran volume prostat (> 25-30 cc), menonjol ke dasar vesica urinaria (BPH)';
    }
    if (lower.includes('splenomegali')) {
      next.pankreasLienStatus = 'Splenomegali';
      next.pankreasLienDesc = 'Ukuran limpa membesar (> 12-13 cm), echostruktur homogen';
    }

    setData(next);
    onNotify('SIMREG: Temuan USG Abdomen kustom berhasil diterapkan ke tabel organ!');
  };

  // Generate exact Markdown matching SIMREG specification
  const generateMarkdownOutput = (): string => {
    return `### [SIMREG] Modul Hasil Pemeriksaan USG Abdomen

| Organ Pemeriksaan | Hasil Pengamatan / Eksplorasi | Status Sistem |
| :--- | :--- | :--- |
| **Hepar (Hati)** | ${data.heparDesc} | ${heparStatusStr} |
| **Vesica Fellea (Empedu)** | ${data.vesicaFelleaDesc} | ${vesicaFelleaStatusStr} |
| **Pankreas & Lien (Limpa)** | ${data.pankreasLienDesc} | ${pankreasLienStatusStr} |
| **Ren (Ginjal Kanan & Kiri)** | ${data.renDesc} | ${renStatusStr} |
| **Vesica Urinaria (Kandung Kemih)** | ${data.vesicaUrinariaDesc} | ${vesicaUrinariaStatusStr} |
| **Prostat (Pria) / Uterus (Wanita)** | ${data.reproduksiDesc} | ${reproduksiStatusStr} |

### 📋 KESIMPULAN DIAGNOSIS FINAL (SIMREG-AUTOMATION)

| Kesimpulan Akhir: | ${kesimpulanAkhirStr} |
| :--- | :--- |
| **Dokter Radiologi (USG):** | ${doctorName} |
| **Kesan / Kesimpulan:** | ${autoKesan} |
| **Saran & Tindak Lanjut:** | ${autoSaran} |
`;
  };

  const handleCopyMarkdown = async () => {
    try {
      await navigator.clipboard.writeText(generateMarkdownOutput());
      setCopied(true);
      onNotify('Laporan USG Abdomen format SIMREG berhasil disalin ke clipboard!');
      setTimeout(() => setCopied(false), 2500);
    } catch {
      onNotify('Gagal menyalin otomatis ke clipboard.');
    }
  };

  const handleSaveToRecord = () => {
    const payload = {
      data,
      isOverallNormal,
      kesan: autoKesan,
      saran: autoSaran,
      markdown: generateMarkdownOutput(),
    };
    try {
      localStorage.setItem(`simreg_usg_${patient.mcuNo}`, JSON.stringify(payload));
      saveAutoGeneratedResume(patient.mcuNo);
    } catch (e) {}

    onSave?.(payload);
    onNotify(
      `SIMREG: Hasil USG Abdomen (${isOverallNormal ? 'Normal' : 'Abnormal'}) untuk ${patient.nama} (#${patient.mcuNo}) berhasil disimpan ke Rekam Medis!`
    );
  };

  return (
    <div className="space-y-6">
      {/* 1. ANTARMUKA AWAL SIMREG (Menunggu Input) */}
      <div className="p-4 sm:p-5 rounded-2xl bg-gradient-to-r from-emerald-50 via-teal-50 to-cyan-50 border border-emerald-200 shadow-xs">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-xl bg-emerald-600 text-white flex items-center justify-center shrink-0 shadow-md">
            <Microscope className="w-5 h-5" />
          </div>
          <div className="space-y-2 flex-1">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <h4 className="font-extrabold text-[15px] text-emerald-950 flex items-center gap-2">
                [SIMREG] Modul Hasil Pemeriksaan Ultrasonografi (USG Abdomen)
              </h4>
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-1 rounded-lg text-[11.5px] font-bold bg-white text-emerald-900 border border-emerald-200 shadow-2xs flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                  Dokter Radiologi: <b>{doctorName}</b>
                </span>
                <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-emerald-100 text-emerald-800 border border-emerald-300 font-mono">
                  SIMREG-AUTOMATION v2.5
                </span>
              </div>
            </div>
            <p className="text-[13px] text-slate-700 leading-relaxed">
              Halo Operator SIMREG! Silakan masukkan data hasil bacaan USG Abdomen pasien di bawah ini (Hepar, Empedu, Pankreas/Limpa, Ginjal, Kandung Kemih, Prostat/Uterus), atau cukup ketik{' '}
              <b className="font-mono text-emerald-800 bg-emerald-100/90 px-1.5 py-0.5 rounded">
                "NORMAL"
              </b>{' '}
              untuk otomatis mengisi seluruh parameter organ dengan temuan normal baku (ukuran, kontur, dan echostruktur normal, tidak tampak massa/batu/kista).
            </p>

            {/* Quick Action Bar */}
            <div className="flex flex-wrap items-center gap-2 pt-2">
              <input
                type="text"
                value={quickInputText}
                onChange={(e) => setQuickInputText(e.target.value)}
                placeholder='Ketik "NORMAL" atau contoh "fatty liver", "batu empedu"'
                className="px-3 py-1.5 bg-white border border-emerald-300 rounded-xl text-xs font-mono font-bold text-slate-800 w-64 focus:ring-2 focus:ring-emerald-500 shadow-2xs"
              />
              <button
                type="button"
                onClick={() => handleApplyQuickInput()}
                className="px-3.5 py-1.5 rounded-xl bg-emerald-700 hover:bg-emerald-800 text-white font-bold text-xs flex items-center gap-1.5 shadow-xs cursor-pointer"
              >
                <Activity className="w-3.5 h-3.5" />
                Proses Data SIMREG
              </button>
              <button
                type="button"
                onClick={() => {
                  setQuickInputText('NORMAL');
                  handleApplyQuickInput('NORMAL');
                }}
                className="px-3.5 py-1.5 rounded-xl bg-white hover:bg-emerald-100 text-emerald-800 border border-emerald-300 font-bold text-xs flex items-center gap-1 cursor-pointer"
              >
                <Sparkles className="w-3.5 h-3.5 text-emerald-600" />
                Isi Default NORMAL
              </button>
            </div>
          </div>
        </div>

        {/* Contoh Preset Simulasi Klinis SIMREG */}
        <div className="mt-4 pt-3 border-t border-emerald-200/60 flex flex-wrap items-center gap-2">
          <span className="text-xs font-bold text-emerald-900 flex items-center gap-1">
            <Sparkles className="w-3.5 h-3.5 text-emerald-600" />
            Simulasi Temuan Klinis:
          </span>
          <button
            type="button"
            onClick={() => {
              setData({
                ...DEFAULT_NORMAL_USG,
                heparStatus: 'Fatty Liver',
                heparDesc: 'Echostruktur hepar meningkat difus (bright liver), atenuasi akustik posterior, tak tampak massa/kista',
                kesanCustom: 'Fatty Liver Grade I-II (Perlemakan Hati). Organ intraabdomen lainnya dalam batas normal.',
                saranCustom: 'Diet rendah lemak/karbohidrat, olahraga teratur, evaluasi profil lipid dan fungsi hati (SGOT/SGPT).',
              });
              onNotify('SIMREG: Memuat simulasi Fatty Liver (Perlemakan Hati)');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-emerald-100 text-slate-800 border border-emerald-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Fatty Liver (Perlemakan Hati)
          </button>
          <button
            type="button"
            onClick={() => {
              setData({
                ...DEFAULT_NORMAL_USG,
                vesicaFelleaStatus: 'Kolelitiasis',
                vesicaFelleaDesc: 'Tampak bayangan hiperekoik multiple uk. 5-8 mm disertai acoustic shadow, dinding tidak menebal',
                kesanCustom: 'Kolelitiasis Multiple (Batu Kandung Empedu). Organ lainnya dalam batas normal.',
                saranCustom: 'Konsultasi Spesialis Bedah Digestif (Sp.B-KBD), batasi makanan berlemak/minyak jenuh.',
              });
              onNotify('SIMREG: Memuat simulasi Kolelitiasis (Batu Empedu)');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-emerald-100 text-slate-800 border border-emerald-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Kolelitiasis (Batu Empedu)
          </button>
          <button
            type="button"
            onClick={() => {
              setData({
                ...DEFAULT_NORMAL_USG,
                renStatus: 'Nefrolitiasis',
                renDesc: 'Ginjal kanan tampak fokus hiperekoik uk. 6 mm di kaliks inferior disertai posterior shadow, ginjal kiri normal',
                kesanCustom: 'Nefrolitiasis Dextra (Batu Ginjal Kanan). Organ intraabdomen lainnya normal.',
                saranCustom: 'Konsultasi Spesialis Urologi (Sp.U), perbanyak konsumsi air putih minimal 2.5-3 Liter/hari.',
              });
              onNotify('SIMREG: Memuat simulasi Nefrolitiasis (Batu Ginjal)');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-emerald-100 text-slate-800 border border-emerald-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Nefrolitiasis (Batu Ginjal)
          </button>
          <button
            type="button"
            onClick={() => {
              setData({
                ...DEFAULT_NORMAL_USG,
                reproduksiStatus: 'Hipertrofi',
                reproduksiDesc:
                  patient.jk === 'P'
                    ? 'Uterus membesar, tampak nodul miometrium berbatas tegas uk. 3x2 cm'
                    : 'Ukuran prostat membesar, estimasi volume 32 cc, menonjol ke dasar buli',
                kesanCustom:
                  patient.jk === 'P'
                    ? 'Suspek Mioma Uteri Intramural.'
                    : 'Benign Prostatic Hyperplasia (BPH) Grade I-II.',
                saranCustom: 'Konsultasi dokter spesialis terkait untuk evaluasi klinis lanjutan.',
              });
              onNotify('SIMREG: Memuat simulasi Hipertrofi Prostat / Mioma');
            }}
            className="px-2.5 py-1 rounded-lg bg-white hover:bg-emerald-100 text-slate-800 border border-emerald-200 text-xs font-semibold cursor-pointer shadow-2xs"
          >
            Hipertrofi Organ Reproduksi
          </button>
        </div>
      </div>

      {/* 2 & 3. TABEL INPUT & INTERPRETASI USG ABDOMEN */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h4 className="font-extrabold text-[15px] text-slate-900 flex items-center gap-2">
            <span>🔬</span>
            Tabel Hasil Pengamatan &amp; Eksplorasi USG Abdomen
          </h4>
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="px-3.5 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-bold flex items-center gap-1.5 border border-slate-300 cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Tersalin!' : 'Salin Laporan Markdown SIMREG'}
          </button>
        </div>

        <div className="overflow-x-auto rounded-xl border border-slate-200 shadow-2xs">
          <table className="w-full text-left text-[13px] border-collapse min-w-[760px]">
            <thead>
              <tr className="bg-slate-800 text-white font-bold text-[12px]">
                <th className="py-3 px-4 w-60">Organ Pemeriksaan</th>
                <th className="py-3 px-4">Hasil Pengamatan / Eksplorasi</th>
                <th className="py-3 px-4 w-72">Status Sistem</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 bg-white">
              {/* 1. Hepar (Hati) */}
              <tr className={`hover:bg-slate-50/80 ${data.heparStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Hepar (Hati)</td>
                <td className="py-2.5 px-4">
                  <input
                    type="text"
                    value={data.heparDesc}
                    onChange={(e) =>
                      setData((prev) => ({
                        ...prev,
                        heparDesc: e.target.value,
                        kesanCustom: '',
                      }))
                    }
                    className="w-full px-3 py-1.5 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500"
                  />
                </td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-1.5 text-xs font-mono">
                    <button
                      type="button"
                      onClick={() => setData((prev) => ({ ...prev, heparStatus: 'Normal', kesanCustom: '' }))}
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.heparStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.heparStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, heparStatus: 'Fatty Liver', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.heparStatus === 'Fatty Liver'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.heparStatus === 'Fatty Liver' ? '[X]' : '[ ]'} Fatty Liver
                    </button>
                    <button
                      type="button"
                      onClick={() => setData((prev) => ({ ...prev, heparStatus: 'Lainnya', kesanCustom: '' }))}
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.heparStatus === 'Lainnya'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.heparStatus === 'Lainnya' ? '[X]' : '[ ]'} Lainnya
                    </button>
                  </div>
                </td>
              </tr>

              {/* 2. Vesica Fellea (Empedu) */}
              <tr className={`hover:bg-slate-50/80 ${data.vesicaFelleaStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Vesica Fellea (Empedu)</td>
                <td className="py-2.5 px-4">
                  <input
                    type="text"
                    value={data.vesicaFelleaDesc}
                    onChange={(e) =>
                      setData((prev) => ({
                        ...prev,
                        vesicaFelleaDesc: e.target.value,
                        kesanCustom: '',
                      }))
                    }
                    className="w-full px-3 py-1.5 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500"
                  />
                </td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-1.5 text-xs font-mono">
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, vesicaFelleaStatus: 'Normal', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.vesicaFelleaStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.vesicaFelleaStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, vesicaFelleaStatus: 'Kolelitiasis', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.vesicaFelleaStatus === 'Kolelitiasis'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.vesicaFelleaStatus === 'Kolelitiasis' ? '[X]' : '[ ]'} Kolelitiasis (Batu)
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, vesicaFelleaStatus: 'Kolesistitis', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.vesicaFelleaStatus === 'Kolesistitis'
                          ? 'bg-red-100 text-red-800 border border-red-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.vesicaFelleaStatus === 'Kolesistitis' ? '[X]' : '[ ]'} Kolesistitis
                    </button>
                  </div>
                </td>
              </tr>

              {/* 3. Pankreas & Lien (Limpa) */}
              <tr className={`hover:bg-slate-50/80 ${data.pankreasLienStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Pankreas &amp; Lien (Limpa)</td>
                <td className="py-2.5 px-4">
                  <input
                    type="text"
                    value={data.pankreasLienDesc}
                    onChange={(e) =>
                      setData((prev) => ({
                        ...prev,
                        pankreasLienDesc: e.target.value,
                        kesanCustom: '',
                      }))
                    }
                    className="w-full px-3 py-1.5 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500"
                  />
                </td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-1.5 text-xs font-mono">
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, pankreasLienStatus: 'Normal', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.pankreasLienStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.pankreasLienStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, pankreasLienStatus: 'Splenomegali', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.pankreasLienStatus === 'Splenomegali'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.pankreasLienStatus === 'Splenomegali' ? '[X]' : '[ ]'} Splenomegali
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, pankreasLienStatus: 'Lainnya', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.pankreasLienStatus === 'Lainnya'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.pankreasLienStatus === 'Lainnya' ? '[X]' : '[ ]'} Lainnya
                    </button>
                  </div>
                </td>
              </tr>

              {/* 4. Ren (Ginjal Kanan & Kiri) */}
              <tr className={`hover:bg-slate-50/80 ${data.renStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Ren (Ginjal Kanan &amp; Kiri)</td>
                <td className="py-2.5 px-4">
                  <input
                    type="text"
                    value={data.renDesc}
                    onChange={(e) =>
                      setData((prev) => ({
                        ...prev,
                        renDesc: e.target.value,
                        kesanCustom: '',
                      }))
                    }
                    className="w-full px-3 py-1.5 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500"
                  />
                </td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-1.5 text-xs font-mono">
                    <button
                      type="button"
                      onClick={() => setData((prev) => ({ ...prev, renStatus: 'Normal', kesanCustom: '' }))}
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.renStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.renStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, renStatus: 'Nefrolitiasis', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.renStatus === 'Nefrolitiasis'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.renStatus === 'Nefrolitiasis' ? '[X]' : '[ ]'} Nefrolitiasis (Batu)
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, renStatus: 'Kista/Massa', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.renStatus === 'Kista/Massa'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.renStatus === 'Kista/Massa' ? '[X]' : '[ ]'} Kista/Massa
                    </button>
                  </div>
                </td>
              </tr>

              {/* 5. Vesica Urinaria (Kandung Kemih) */}
              <tr className={`hover:bg-slate-50/80 ${data.vesicaUrinariaStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">Vesica Urinaria (Kandung Kemih)</td>
                <td className="py-2.5 px-4">
                  <input
                    type="text"
                    value={data.vesicaUrinariaDesc}
                    onChange={(e) =>
                      setData((prev) => ({
                        ...prev,
                        vesicaUrinariaDesc: e.target.value,
                        kesanCustom: '',
                      }))
                    }
                    className="w-full px-3 py-1.5 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500"
                  />
                </td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-1.5 text-xs font-mono">
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, vesicaUrinariaStatus: 'Normal', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.vesicaUrinariaStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.vesicaUrinariaStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, vesicaUrinariaStatus: 'Sistitis', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.vesicaUrinariaStatus === 'Sistitis'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.vesicaUrinariaStatus === 'Sistitis' ? '[X]' : '[ ]'} Sistitis
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, vesicaUrinariaStatus: 'Batu/Massa', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.vesicaUrinariaStatus === 'Batu/Massa'
                          ? 'bg-red-100 text-red-800 border border-red-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.vesicaUrinariaStatus === 'Batu/Massa' ? '[X]' : '[ ]'} Batu/Massa
                    </button>
                  </div>
                </td>
              </tr>

              {/* 6. Prostat (Pria) / Uterus (Wanita) */}
              <tr className={`hover:bg-slate-50/80 ${data.reproduksiStatus !== 'Normal' ? 'bg-amber-50/40' : ''}`}>
                <td className="py-3 px-4 font-bold text-slate-900">
                  {organReproduksiTitle}
                </td>
                <td className="py-2.5 px-4">
                  <input
                    type="text"
                    value={data.reproduksiDesc}
                    onChange={(e) =>
                      setData((prev) => ({
                        ...prev,
                        reproduksiDesc: e.target.value,
                        kesanCustom: '',
                      }))
                    }
                    className="w-full px-3 py-1.5 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500"
                  />
                </td>
                <td className="py-3 px-4">
                  <div className="flex flex-wrap items-center gap-1.5 text-xs font-mono">
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, reproduksiStatus: 'Normal', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.reproduksiStatus === 'Normal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.reproduksiStatus === 'Normal' ? '[X]' : '[ ]'} Normal
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, reproduksiStatus: 'Hipertrofi', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.reproduksiStatus === 'Hipertrofi'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.reproduksiStatus === 'Hipertrofi' ? '[X]' : '[ ]'} Hipertrofi (BPH/Mioma)
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setData((prev) => ({ ...prev, reproduksiStatus: 'Lainnya', kesanCustom: '' }))
                      }
                      className={`px-2 py-0.5 rounded font-bold cursor-pointer transition-colors ${
                        data.reproduksiStatus === 'Lainnya'
                          ? 'bg-amber-100 text-amber-800 border border-amber-300'
                          : 'text-slate-400 hover:text-slate-600'
                      }`}
                    >
                      {data.reproduksiStatus === 'Lainnya' ? '[X]' : '[ ]'} Lainnya
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* 4. 📋 KESIMPULAN DIAGNOSIS FINAL (SIMREG-AUTOMATION) */}
      <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-4">
        <h4 className="font-extrabold text-[15px] text-slate-900 flex items-center gap-2 border-b border-slate-200 pb-2">
          <span>📋</span>
          KESIMPULAN DIAGNOSIS FINAL (SIMREG-AUTOMATION)
        </h4>

        <div className="overflow-x-auto rounded-xl border border-slate-200">
          <table className="w-full text-left text-[13px]">
            <tbody className="divide-y divide-slate-200 bg-white">
              {/* Kesimpulan Akhir */}
              <tr>
                <td className="py-3.5 px-4 font-bold text-slate-900 w-52 bg-slate-50/80 align-top">
                  Kesimpulan Akhir:
                </td>
                <td className="py-3.5 px-4 font-mono text-[12.5px]">
                  <div className="flex flex-col gap-1.5">
                    <span
                      className={`px-2.5 py-1 rounded border w-fit font-bold ${
                        isOverallNormal
                          ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                          : 'text-slate-400 border-transparent'
                      }`}
                    >
                      {isOverallNormal ? '[X]' : '[ ]'} USG ABDOMEN NORMAL (Seluruh organ abdomen dalam batas normal)
                    </span>
                    <span
                      className={`px-2.5 py-1 rounded border w-fit font-bold ${
                        !isOverallNormal
                          ? 'bg-rose-50 text-rose-800 border-rose-200'
                          : 'text-slate-400 border-transparent'
                      }`}
                    >
                      {!isOverallNormal ? '[X]' : '[ ]'} USG ABDOMEN ABNORMAL (Ditemukan Kelainan Sonografis)
                    </span>
                  </div>
                </td>
              </tr>

              {/* Kesan / Kesimpulan */}
              <tr>
                <td className="py-3 px-4 font-bold text-slate-900 bg-slate-50/80">
                  Kesan / Kesimpulan:
                </td>
                <td className="py-3 px-4">
                  <div className="space-y-1.5">
                    <input
                      type="text"
                      value={autoKesan}
                      onChange={(e) =>
                        setData((prev) => ({
                          ...prev,
                          kesanCustom: e.target.value,
                        }))
                      }
                      className="w-full px-3 py-1.5 font-bold text-slate-900 bg-slate-50 border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-emerald-500"
                    />
                    <div className="text-[11px] text-slate-500">
                      Kesan dapat disunting manual atau mengikuti resume otomatis sistem dari temuan organ.
                    </div>
                  </div>
                </td>
              </tr>

              {/* Saran & Tindak Lanjut */}
              <tr>
                <td className="py-3 px-4 font-bold text-slate-900 bg-slate-50/80">
                  Saran &amp; Tindak Lanjut:
                </td>
                <td className="py-3 px-4">
                  <div className="space-y-1.5">
                    <input
                      type="text"
                      value={autoSaran}
                      onChange={(e) =>
                        setData((prev) => ({
                          ...prev,
                          saranCustom: e.target.value,
                        }))
                      }
                      className="w-full px-3 py-1.5 text-slate-900 bg-slate-50 border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-emerald-500"
                    />
                    <div className="text-[11px] text-slate-500">
                      Rekomendasi otomatis aplikasi SIMREG untuk dokter pemeriksa &amp; rekam medis.
                    </div>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="pt-2 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200">
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleSaveToRecord}
            className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-emerald-700 to-teal-700 hover:from-emerald-800 hover:to-teal-800 text-white font-bold text-xs flex items-center gap-2 shadow-md shadow-emerald-900/20 cursor-pointer"
          >
            <CheckCircle2 className="w-4 h-4" />
            Simpan Hasil USG #{patient.mcuNo}
          </button>
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="px-4 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold text-xs flex items-center gap-1.5 border border-slate-300 cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            Salin Laporan Markdown SIMREG
          </button>
        </div>

        <div className="text-xs text-slate-500 font-medium">
          Pasien: <b className="text-slate-800">{patient.nama}</b> ({patient.pt}) • No. MCU #{patient.mcuNo}
        </div>
      </div>
    </div>
  );
};
